function loadHtmlFile(a,b,c,d){(new Request.HTML({url:a+(d?"?version="+d:""),onSuccess:function(a,c,d){b(d)},onFailure:function(){c()}})).get()}
var Dialog=new Class({initialize:function(a,b,c,d,f,e){this.sid=a;this.obj=$(a);this.Width=$(a).offsetWidth;this.Height=$(a).offsetHeight;this.okButton=c==void 0?$("d_confirm"):$(c);this.closeButtion=d==void 0?$("d_close"):$(d);this.isIE=navigator.userAgent.toLowerCase().indexOf("msie")!=-1;this.isIE6=navigator.userAgent.toLowerCase().indexOf("msie 6.0")!=-1;c=document.documentElement.clientWidth;d=document.documentElement.clientHeight;this.Left=((c-this.Width)/2+50>0?(c-this.Width)/2+50:150).round();
this.Top=((d-this.Height)/2-40>0?(d-this.Height)/2-40:100).round();this.hideSelectBoxes=function(){var a=document.getElementsByTagName("SELECT");for(i=0;a&&i<a.length;i++)a[i].style.visibility="hidden";a=this.obj.getElementsByTagName("SELECT");for(i=0;a&&i<a.length;i++)a[i].style.visibility="visible"};var g=function(){var a=document.getElementsByTagName("SELECT");for(i=0;a&&i<a.length;i++)a[i].style.visibility="visible"};this.displaySelectBoxes=g;(c=$(a).getElement(".ui-dialog-icon"))&&(e?c.addEvent("click",
e):c.addEvent("click",function(){this.isIE6&&g();$(a).style.top="-10000px";Site.currentPage.is.videoDetectConfig&&$("video1")&&$("video1").setStyles({top:"0px",left:"0px"});Site.currentPage.is.temperAlarmConfig&&$("video1")&&$("video1").setStyles({top:"0px",left:"0px"});Site.currentPage.is.intellentConfig&&$$("#SceneCover").setStyle("display","none")}));(c=$(a).getElement(".ui-dialog-title h1"))&&c.setProperty("text",f||"");this.okButton&&b&&this.okButton.addEvent("click",b);this.closeButtion&&(e?
this.closeButtion.addEvent("click",e):this.closeButtion.addEvent("click",function(){this.isIE6&&g();$(a).style.top="-10000px";Site.currentPage.is.videoDetectConfig&&$("video1")&&$("video1").setStyles({top:"0px",left:"0px"});Site.currentPage.is.temperAlarmConfig&&$("video1")&&$("video1").setStyles({top:"0px",left:"0px"});Site.currentPage.is.intellentConfig&&$$("#SceneCover").setStyle("display","none")}))},setPosition:function(a,b){this.Left=a;this.Top=b;if(this.isIE6)this.Left=a-20,this.Top=b-130},
setTitle:function(a){var b=$(this.sid).getElement(".ui-dialog-title h1");b&&b.setProperty("text",a)},show:function(){this.isIE6&&this.hideSelectBoxes();this.obj.style.top=this.Top+"px";if(this.Left)this.obj.style.left=this.Left+"px"},close:function(){this.closeButtion?this.closeButtion.fireEvent("click"):(this.isIE6&&displaySelectBoxes(),this.obj.style.top="-10000px",Site.currentPage.is.videoDetectConfig&&$("video1")&&$("video1").setStyles({top:"0px",left:"0px"}),Site.currentPage.is.temperAlarmConfig&&
$("video1")&&$("video1").setStyles({top:"0px",left:"0px"}))}});function jsonCompare(a,b){return $type(a)=="object"&&$type(b)=="object"||$type(a)=="array"&&$type(b)=="array"?Object.getLength(a)==Object.getLength(b)?!Object.some(a,function(a,d){return!jsonCompare(a,b[d])}):!1:a===b}function limit(a,b){var c=a.value;if(c!=""&&(/[^\d]/g.test(c)?a.value=c.replace(/[^\d]/g,"")-0:a.value-=0,c=a.value,c>b))a.value=b}
function limitEx(a,b){var c=a.value;/[^\d]/g.test(c)?(c=c.replace(/[^\d]/g,"")-0,a.value=c):c=a.value-0;if(c>b)a.value=b}function limitMin(a,b){var c=a.value;if(/[^\d]/g.test(c))a.value=c.replace(/[^\d]/g,"")-0;c=a.value;if(c=="")a.value=b;else if(c<b)a.value=b}function limitTime(a,b){var c=a.value,c=c.replace(/[^\d]/g,"");if(c-0>b)a.value=b;c=a.value;c.length>=2&&a.id!=""&&(c=$(a.id).getNext("input"))&&c.select()}function getTable(a){return JSON.decode(a).result?JSON.decode(a).params.table:""}
function hideSelectBoxes(){var a=document.getElementsByTagName("SELECT");for(i=0;a&&i<a.length;i++)a[i].style.visibility="hidden"}function displaySelectBoxes(){var a=document.getElementsByTagName("SELECT");for(i=0;a&&i<a.length;i++)a[i].style.visibility="visible"}function getSelect(a){return $(a).options[$(a).selectedIndex].text}function parsrTime(a){if(a)var b=a.trim().split(" "),c=b[1].split("-"),a=c[0].split(":"),c=c[1].split(":"),a=[b[0],a[0],a[1],c[0],c[1]];else a=[0,0,0,24,0];return a}
function parsrTimeEx(a){if(a)var b=a.trim().split(" "),c=b[1].split("-"),a=c[0].split(":"),c=c[1].split(":"),a=[b[0]-0,a[0]-0,a[1]-0,a[2]-0,c[0]-0,c[1]-0,c[2]-0];else a=[0,0,0,0,24,0,0];return a}function getBit(a,b){var c=a-0&1<<b;c>>=b;return c}function getBitEx(a,b){var c=(a-0).toString(2);return c.charAt(c.length-b-1)=="1"?1:0}function setBit(a,b,c){a-=0;c==1?a|=1<<b:a&=~(1<<b);return a}
function setBitEx(a,b,c){var d=(a-0).toString(2),f=d.length,e=0;f-b-1>=0&&(e=d.charAt(f-b-1));return e-0==c?a:a+(c-e)*Math.pow(2,b)}function pasteChk(){clipboardData.setData("text",clipboardData.getData("text").replace(/[^\d]/g,""))}
function chkTime(a,b,c,d){var d=d||event,f=c.toString().length,e,g=$(a+b);g.value=g.value.replace(/[^\d]/g,"");d=d.keyCode;if(d==37||d==39||d==9)if(g.blur(),d==37&&(e=b-1),d==39&&(e=b+1),d==9){if($(a+(b-1))&&(c=$(a+(b-1)).value-0,c<10))$(a+(b-1)).value="0"+c;$(a+b).select()}else{if(!(e>2||e<0)){c=g.value-0;if(c<10)g.value="0"+c;$(a+e).select()}}else if(g.value.length>=f)if(parseInt(g.value)>c)g.value=c,e=b+1,e>2||e<0||$(a+e).select();else if(parseInt(g.value)<0)g.value="00";else if(g.blur(),e=b+1,
!(e>2||e<0)){c=g.value-0;if(c<10)g.value="0"+c;$(a+e).select()}}function getMonthDay(a){var b=$(a+0).value-0,a=$(a+1).value-0;return a==4||a==6||a==9||a==11?30:a==2&&!(b%4!=0||b%100==0&&b%400!=0)?29:a==2&&(b%4!=0||b%100==0&&b%400!=0)?28:31}
function checkDay(a){if($(a+0).value-0<2E3)$(a+0).value=2E3;var b=$(a+1).value-0;if(b<1)$(a+1).value="01";else if(b<10)$(a+1).value="0"+b;else if(b>12)$(a+1).value=12;var b=$(a+2).value-0,c=getMonthDay(a);if(b<=0)$(a+2).value="01";else if(b<10)$(a+2).value="0"+b;else if(b>c)$(a+2).value=c}function round1(a,b){var c=a%b;return c<b/2?a-c:a+b-c}
function getReference(a,b,c){var b=b>149?50:b,c=getWidthH(c).split("*"),d=c[0]-0,f=c[1]-0,c=(b+3-1)*a*7/b*d*f/101376;c>=4&&(c=round1(c,(1<<Math.log(c)/Math.log(2))/4));a=(b+3-1)*a*40/b*d*f/101376;a>=4&&(a=round1(a,(1<<Math.log(a)/Math.log(2))/4));a>8192&&(a=8192);return[Math.round(c),Math.round(a)]}function checkTime0(a){return a-0<10?"0"+(a-0):""+a}
function getSuggestBRIndex(a,b){for(var c=[32,48,64,80,96,128,160,192,224,256,320,384,448,512,640,768,896,1024,1280,1536,1792,2048],d=(a+b)/2,f=0,f=0;f<c.length;f++)if(c[f]>=d)return c[f];return 2048}
var initInputText=function(){var a=null,b=function(b){this.attrs={inputId:null,tipType:null,tipId:null,deleteId:null};this.attrs=$merge(this.attrs,b);a=this;this.inputId=this.attrs.inputId;this._bind()};b.prototype={_bind:function(){function b(a,c){c===3?$(d.attrs.tipId).innerHTML==d.attrs.tipType&&$(d.attrs.tipId).setStyle("color","#555"):($(d.attrs.tipId).innerHTML==d.attrs.tipType?$(d.attrs.tipId).setStyle("color","#999"):$(d.attrs.tipId).setStyle("color","#555"),a.value!=""?($(d.attrs.deleteId).style.display=
"block",$(d.attrs.tipId).set("text","")):($(d.attrs.tipId).set("text",tl(d.attrs.tipType)),$(d.attrs.tipId).setStyle("color","#999"),$(d.attrs.deleteId).style.display="none"))}var d=this;$(a.attrs.inputId).value==""&&$(d.attrs.tipId).set("text",tl(d.attrs.tipType));$(a.attrs.tipId).addEvent("mouseup",function(){$(d.attrs.inputId).focus()});$(a.attrs.deleteId).addEvent("focus",function(){$(d.attrs.inputId).focus()});$(a.attrs.inputId).addEvents({focus:function(){b(this)},keyup:function(){b(this)},
blur:function(){b(this,3)}});$(d.attrs.deleteId).addEvent("click",function(){if($(d.attrs.inputId).value)$(d.attrs.inputId).value="",$(d.attrs.tipId).innerHTML=d.attrs.tipType,$(d.attrs.deleteId).style.display="none"})}};return b}();
Element.implement({translation:function(a){var b=this.getElements("[t]");b.push(this);b.each(function(b){var d=b.getProperty("t");d&&(d=d.split(";"),d.each(function(d){d=d.split("::");d.length===1&&(d[1]=d[0],d[0]="text");var e="";d[1].split("+").each(function(b){e+=$type(a)=="function"?a(b):$type(a)==!1?typeof tl==="function"?tl(b):b:a[b]});b.setProperty(d[0],e)}))});return this}});
Element.implement({fireDelegatedEvent:function(a,b){this.fireEvent(a,{target:b,stop:function(){},preventDefault:function(){},stopPropagation:function(){}});return this}});
Date.implement({format:function(a){var b=this,c=function(a){a+="";return a.length<2?"0"+a:a},d={yyyy:function(a){return a.getFullYear()},MM:function(a){return c(a.getMonth()+1)},dd:function(a){return c(a.getDate())},HH:function(a){return c(a.getHours())},mm:function(a){return c(a.getMinutes())},ss:function(a){return c(a.getSeconds())}},f=RegExp(Object.keys(d).join("|"),"g");return(a||"yyyy-MM-dd HH:mm:ss").replace(f,function(a){return d[a]&&d[a](b)})}});
var DateTimeField=new Class({Implements:Events,invokeMethods:["FullYear","Month","Date","Hours","Minutes","Seconds"],initialize:function(a){this.element=typeOf(a)=="element"?a:$(a);if(!this.element)throw Error("no element off id : "+a);this.initEvents();this.setMaxValue("2030-12-31 23:59:59");this.setMinValue("2000-01-01 00:00:00");this.setValue(Date.now())},initEvents:function(){this.element.removeEvents();this.element.addEvent("keyup:relay(input)",this._limit.bind(this));this.element.addEvent("change:relay(input)",
this._validate.bind(this))},_limit:function(a,b){var c=/[^\d]/g,d=b.value;if(c.test(d))d=d.replace(c,"")||0,b.value=this._pad(d);var f,e;switch(b.name){case "month":f=1;e=12;break;case "day":f=1;e=this._getMonthDay();break;case "hour":f=0;e=23;break;case "minute":case "second":f=0,e=59}d=parseInt(d,10);if(d>e)b.value=this._pad(e);else if(!a&&d<f)b.value=this._pad(f);a&&this._goNext(b)},_validate:function(){var a=this;this.element.getElements("input").each(function(b){a._limit(null,b);b.value=a._pad(b.value)});
var b=this.getTime();b>this.maxTime?this.setValue(this.maxTime):b<this.minTime&&this.setValue(this.minTime);this.fireEvent("change",this)},_goNext:function(a){var b=this.element.getElements("input"),c=b.indexOf(a);if(c<b.length-1&&(b=b[c+1],a.value.length>=(a.name=="year"?4:2)&&!b.disabled))b.focus(),b.select()},_getMonthDay:function(){var a=this.element.getElements("input"),b=new Date;b.setFullYear(a[0].value-0);b.setMonth(a[1].value-0);b.setDate(0);return b.getDate()},_str2time:function(a){var a=
a.split(" "),b=a[0].split("-").concat(a[1].split(":")),b=b.invoke("toInt"),c=new Date;this.invokeMethods.each(function(a,f){a=="Month"&&b[f]--;c["set"+a](b[f])});return c.getTime()},_pad:function(a){a=parseInt(a,10);return a<10?"0"+a:a},getTime:function(){return this._str2time(this.toString())},setValue:function(a){var b=a,c=this,d=new Date;typeOf(a)=="string"&&(b=this._str2time(a));d.setTime(b);this.element.getElements("input").each(function(a,b){var g=c.invokeMethods[b],h=d["get"+g]();a.value=c._pad(g==
"Month"?h+1:h)});this.fireEvent("change",this);return this},setMaxValue:function(a){this.maxTime=a;if(typeOf(a)=="string")this.maxTime=this._str2time(a);return this},setMinValue:function(a){this.minTime=a;if(typeOf(a)=="string")this.minTime=this._str2time(a);return this},toString:function(){var a={};this.element.getElements("input").each(function(b,c){a[c]=b.value});return"{0}-{1}-{2} {3}:{4}:{5}".substitute(a)},format:function(a){var b=function(a){a+="";return a.length<2?"0"+a:a},c={yyyy:function(a){return b(a.getFullYear(),
2)},MM:function(a){return b(a.getMonth()+1,2)},dd:function(a){return b(a.getDate(),2)},HH:function(a){return b(a.getHours(),2)},mm:function(a){return b(a.getMinutes(),2)},ss:function(a){return b(a.getSeconds(),2)}},d=RegExp(Object.keys(c).join("|"),"g"),f=new Date(this.getTime());return(a||"yyyy-MM-dd HH:mm:ss").replace(d,function(a){return c[a]&&c[a](f)})},displayMode:function(a){var b=this.element.getChildren(),c=b[0].getElements("span"),d=b[0].getElements("input");b[1].getElements("span");b[1].getElements("input");
c={year:c.concat(b[1]).concat(d.slice(1)),month:[c[1],d[2],b[1]],day:[b[1]]};b.setStyle("display","");b.each(function(a){a.getChildren().setStyle("display","")});c[a]&&c[a].each(function(a){a.setStyle("display","none")});return this}});
