(function(){var f,m,n;(function(){var b={},a={};f=function(a,c,e){b[a]={deps:c,callback:e}};n=m=function(d){function c(a){if(a.charAt(0)!==".")return a;for(var a=a.split("/"),b=d.split("/").slice(0,-1),c=0,i=a.length;c<i;c++){var e=a[c];e===".."?b.pop():e!=="."&&b.push(e)}return b.join("/")}n._eak_seen=b;if(a[d])return a[d];a[d]={};if(!b[d])throw Error("Could not find module "+d);for(var e=b[d],i=e.deps,e=e.callback,l=[],h,g=0,f=i.length;g<f;g++)i[g]==="exports"?l.push(h={}):l.push(m(c(i[g])));i=
e.apply(this,l);return a[d]=h||i}})();f("promise/all",["./utils","exports"],function(b,a){var d=b.isArray,c=b.isFunction;a.all=function(a){if(!d(a))throw new TypeError("You must pass an array to all.");return new this(function(b,d){function h(a){return function(c){g[a]=c;--f===0&&b(g)}}var g=[],f=a.length,j;f===0&&b([]);for(var k=0;k<a.length;k++)(j=a[k])&&c(j.then)?j.then(h(k),d):(g[k]=j,--f===0&&b(g))})}});f("promise/asap",["exports"],function(b){function a(){return function(){process.nextTick(e)}}
function d(){var a=0,b=new f(e),c=document.createTextNode("");b.observe(c,{characterData:!0});return function(){c.data=a=++a%2}}function c(){return function(){h.setTimeout(e,1)}}function e(){for(var a=0;a<g.length;a++){var b=g[a];(0,b[0])(b[1])}g=[]}var i=typeof window!=="undefined"?window:{},f=i.MutationObserver||i.WebKitMutationObserver,h=typeof global!=="undefined"?global:this===void 0?window:this,g=[],q;q=typeof process!=="undefined"&&{}.toString.call(process)==="[object process]"?a():f?d():c();
b.asap=function(a,b){g.push([a,b])===1&&q()}});f("promise/config",["exports"],function(b){var a={instrument:!1};b.config=a;b.configure=function(b,c){if(arguments.length===2)a[b]=c;else return a[b]}});f("promise/polyfill",["./promise","./utils","exports"],function(b,a,d){var c=b.Promise,e=a.isFunction;d.polyfill=function(){var a;a=typeof global!=="undefined"?global:typeof window!=="undefined"&&window.document?window:self;if(!("Promise"in a&&"resolve"in a.Promise&&"reject"in a.Promise&&"all"in a.Promise&&
"race"in a.Promise&&function(){var b;new a.Promise(function(a){b=a});return e(b)}()))a.Promise=c}});f("promise/promise",["./config","./utils","./all","./race","./resolve","./reject","./asap","exports"],function(b,a,d,c,e,f,l,h){function g(a){if(!s(a))throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(!(this instanceof g))throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");
this._subscribers=[];q(a,this)}function q(a,b){function c(a){p(b,a)}function d(a){o(b,a)}try{a(c,d)}catch(f){d(f)}}function j(a,b,c,d){var f=s(c),e,g,i,h;if(f)try{e=c(d),i=!0}catch(l){h=!0,g=l}else e=d,i=!0;n(b,e)||(f&&i?p(b,e):h?o(b,g):a===t?p(b,e):a===u&&o(b,e))}function k(a,b,c,d){var a=a._subscribers,e=a.length;a[e]=b;a[e+t]=c;a[e+u]=d}function m(a,b){for(var c,e,d=a._subscribers,f=a._detail,g=0;g<d.length;g+=3)c=d[g],e=d[g+b],j(b,c,e,f);a._subscribers=null}function n(a,b){var c=null,d;try{if(a===
b)throw new TypeError("A promises callback cannot return that same promise.");if(y(b)&&(c=b.then,s(c)))return c.call(b,function(c){if(d)return!0;d=!0;b!==c?p(a,c):v(a,c)},function(b){if(d)return!0;d=!0;o(a,b)}),!0}catch(e){if(d)return!0;o(a,e);return!0}return!1}function p(a,b){a===b?v(a,b):n(a,b)||v(a,b)}function v(a,b){if(a._state===w)a._state=x,a._detail=b,r.async(z,a)}function o(a,b){if(a._state===w)a._state=x,a._detail=b,r.async(A,a)}function z(a){m(a,a._state=t)}function A(a){m(a,a._state=u)}
var r=b.config,y=a.objectOrFunction,s=a.isFunction,b=d.all,c=c.race,e=e.resolve,f=f.reject;r.async=l.asap;var w=void 0,x=0,t=1,u=2;g.prototype={constructor:g,_state:void 0,_detail:void 0,_subscribers:void 0,then:function(a,b){var c=this,d=new this.constructor(function(){});if(this._state){var e=arguments;r.async(function(){j(c._state,d,e[c._state-1],c._detail)})}else k(this,d,a,b);return d},"catch":function(a){return this.then(null,a)}};g.all=b;g.race=c;g.resolve=e;g.reject=f;h.Promise=g});f("promise/race",
["./utils","exports"],function(b,a){var d=b.isArray;a.race=function(a){if(!d(a))throw new TypeError("You must pass an array to race.");return new this(function(b,d){for(var f,h=0;h<a.length;h++)(f=a[h])&&typeof f.then==="function"?f.then(b,d):b(f)})}});f("promise/reject",["exports"],function(b){b.reject=function(a){return new this(function(b,c){c(a)})}});f("promise/resolve",["exports"],function(b){b.resolve=function(a){return a&&typeof a==="object"&&a.constructor===this?a:new this(function(b){b(a)})}});
f("promise/utils",["exports"],function(b){function a(a){return typeof a==="function"}var d=Date.now||function(){return(new Date).getTime()};b.objectOrFunction=function(b){return a(b)||typeof b==="object"&&b!==null};b.isFunction=a;b.isArray=function(a){return Object.prototype.toString.call(a)==="[object Array]"};b.now=d});m("promise/polyfill").polyfill()})();
