var Class1={create:function(){return function(){this.initialize.apply(this,arguments)}}},Extend=function(a,c){for(var b in c)a[b]=c[b]},Bind=function(a,c){return function(){return c.apply(a,arguments)}},BindAsEventListener=function(a,c){var b=Array.prototype.slice.call(arguments).slice(2);return function(d){return c.apply(a,[d||window.event].concat(b))}},CurrentStyle=function(a){return a.currentStyle||document.defaultView.getComputedStyle(a,null)};
function addEventHandler(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent?a.attachEvent("on"+c,b):a["on"+c]=b}function removeEventHandler(a,c,b){a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent?a.detachEvent("on"+c,b):a["on"+c]=null}var Resize=Class1.create();
Resize.prototype={initialize:function(a,c){this._obj=$(a);this._scaleLeft=this._scaleTop=this._fixLeft=this._fixTop=this._sideRight=this._sideDown=this._sideLeft=this._sideUp=this._styleWidth=this._styleHeight=this._styleLeft=this._styleTop=0;this._mxSet=function(){};this._mxScaleWidth=this._mxScaleHeight=this._mxRightWidth=this._mxDownHeight=this._mxUpHeight=this._mxLeftWidth=0;this._fun=function(){};var b=CurrentStyle(this._obj);this._borderX=(parseInt(b.borderLeftWidth)||0)+(parseInt(b.borderRightWidth)||
0);this._borderY=(parseInt(b.borderTopWidth)||0)+(parseInt(b.borderBottomWidth)||0);this._fR=BindAsEventListener(this,this.Resize);this._fS=Bind(this,this.Stop);this.SetOptions(c);this.Max=!!this.options.Max;this._mxContainer=$(this.options.mxContainer)||null;this.mxLeft=Math.round(this.options.mxLeft);this.mxRight=Math.round(this.options.mxRight);this.mxTop=Math.round(this.options.mxTop);this.mxBottom=Math.round(this.options.mxBottom);this.Min=!!this.options.Min;this.minWidth=Math.round(this.options.minWidth);
this.minHeight=Math.round(this.options.minHeight);this.Scale=!!this.options.Scale;this.Ratio=Math.max(this.options.Ratio,0);this.onResize=this.options.onResize;this._obj.style.position="absolute";!this._mxContainer||CurrentStyle(this._mxContainer).position=="relative"||(this._mxContainer.style.position="relative")},SetOptions:function(a){this.options={Max:!1,mxContainer:"",mxLeft:0,mxRight:8191,mxTop:0,mxBottom:8191,Min:!1,minWidth:50,minHeight:50,Scale:!1,Ratio:0,onResize:function(){}};Extend(this.options,
a||{})},Set:function(a,c){var a=$(a),b;if(a){switch(c.toLowerCase()){case "up":b=this.Up;break;case "down":b=this.Down;break;case "left":b=this.Left;break;case "right":b=this.Right;break;case "left-up":b=this.LeftUp;break;case "right-up":b=this.RightUp;break;case "left-down":b=this.LeftDown;break;default:b=this.RightDown}addEventHandler(a,"mousedown",BindAsEventListener(this,this.Start,b))}},Start:function(a,c){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;this._fun=c;this._styleWidth=this._obj.clientWidth;
this._styleHeight=this._obj.clientHeight;this._styleLeft=this._obj.offsetLeft;this._styleTop=this._obj.offsetTop;this._sideLeft=a.clientX-this._styleWidth;this._sideRight=a.clientX+this._styleWidth;this._sideUp=a.clientY-this._styleHeight;this._sideDown=a.clientY+this._styleHeight;this._fixLeft=this._styleLeft+this._styleWidth;this._fixTop=this._styleTop+this._styleHeight;if(this.Scale)this.Ratio=Math.max(this.Ratio,0)||this._styleWidth/this._styleHeight,this._scaleLeft=this._styleLeft+this._styleWidth/
2,this._scaleTop=this._styleTop+this._styleHeight/2;if(this.Max){var b=this.mxLeft,d=this.mxRight,f=this.mxTop,e=this.mxBottom;this._mxContainer&&(b=Math.max(b,0),f=Math.max(f,0),d=Math.min(d,this._mxContainer.clientWidth),e=Math.min(e,this._mxContainer.clientHeight));d=Math.max(d,b+(this.Min?this.minWidth:0)+this._borderX);e=Math.max(e,f+(this.Min?this.minHeight:0)+this._borderY);this._mxSet=function(){this._mxRightWidth=d-this._styleLeft-this._borderX;this._mxDownHeight=e-this._styleTop-this._borderY;
this._mxUpHeight=Math.max(this._fixTop-f,this.Min?this.minHeight:0);this._mxLeftWidth=Math.max(this._fixLeft-b,this.Min?this.minWidth:0)};this._mxSet();if(this.Scale)this._mxScaleWidth=Math.min(this._scaleLeft-b,d-this._scaleLeft-this._borderX)*2,this._mxScaleHeight=Math.min(this._scaleTop-f,e-this._scaleTop-this._borderY)*2}addEventHandler(document,"mousemove",this._fR);addEventHandler(document,"mouseup",this._fS);isIE?(addEventHandler(this._obj,"losecapture",this._fS),this._obj.setCapture()):(addEventHandler(window,
"blur",this._fS),a.preventDefault())},Resize:function(a){window.getSelection?window.getSelection().removeAllRanges():document.selection.empty();this._fun(a);this._obj.style.width=this._styleWidth+"px";this._obj.style.height=this._styleHeight+"px";this._obj.style.top=this._styleTop+"px";this._obj.style.left=this._styleLeft+"px";this.onResize()},Up:function(a){this.RepairY(this._sideDown-a.clientY,this._mxUpHeight);this.RepairTop();this.TurnDown(this.Down)},Down:function(a){this.RepairY(a.clientY-this._sideUp,
this._mxDownHeight);this.TurnUp(this.Up)},Right:function(a){this.RepairX(a.clientX-this._sideLeft,this._mxRightWidth);this.TurnLeft(this.Left)},Left:function(a){this.RepairX(this._sideRight-a.clientX,this._mxLeftWidth);this.RepairLeft();this.TurnRight(this.Right)},RightDown:function(a){this.RepairAngle(a.clientX-this._sideLeft,this._mxRightWidth,a.clientY-this._sideUp,this._mxDownHeight);this.TurnLeft(this.LeftDown)||this.Scale||this.TurnUp(this.RightUp)},RightUp:function(a){this.RepairAngle(a.clientX-
this._sideLeft,this._mxRightWidth,this._sideDown-a.clientY,this._mxUpHeight);this.RepairTop();this.TurnLeft(this.LeftUp)||this.Scale||this.TurnDown(this.RightDown)},LeftDown:function(a){this.RepairAngle(this._sideRight-a.clientX,this._mxLeftWidth,a.clientY-this._sideUp,this._mxDownHeight);this.RepairLeft();this.TurnRight(this.RightDown)||this.Scale||this.TurnUp(this.LeftUp)},LeftUp:function(a){this.RepairAngle(this._sideRight-a.clientX,this._mxLeftWidth,this._sideDown-a.clientY,this._mxUpHeight);
this.RepairTop();this.RepairLeft();this.TurnRight(this.RightUp)||this.Scale||this.TurnDown(this.LeftDown)},RepairX:function(a,c){a=this.RepairWidth(a,c);if(this.Scale){var b=this.RepairScaleHeight(a);if(this.Max&&b>this._mxScaleHeight)b=this._mxScaleHeight,a=this.RepairScaleWidth(b);else if(this.Min&&b<this.minHeight){var d=this.RepairScaleWidth(this.minHeight);if(d<c)b=this.minHeight,a=d}this._styleHeight=b;this._styleTop=this._scaleTop-b/2}this._styleWidth=a},RepairY:function(a,c){a=this.RepairHeight(a,
c);if(this.Scale){var b=this.RepairScaleWidth(a);if(this.Max&&b>this._mxScaleWidth)b=this._mxScaleWidth,a=this.RepairScaleHeight(b);else if(this.Min&&b<this.minWidth){var d=this.RepairScaleHeight(this.minWidth);if(d<c)b=this.minWidth,a=d}this._styleWidth=b;this._styleLeft=this._scaleLeft-b/2}this._styleHeight=a},RepairAngle:function(a,c,b,d){a=this.RepairWidth(a,c);if(this.Scale)if(b=this.RepairScaleHeight(a),this.Max&&b>d)b=d,a=this.RepairScaleWidth(b);else{if(this.Min&&b<this.minHeight&&(d=this.RepairScaleWidth(this.minHeight),
d<c))b=this.minHeight,a=d}else b=this.RepairHeight(b,d);this._styleWidth=a;this._styleHeight=b},RepairTop:function(){this._styleTop=this._fixTop-this._styleHeight},RepairLeft:function(){this._styleLeft=this._fixLeft-this._styleWidth},RepairHeight:function(a,c){a=Math.min(this.Max?c:a,a);return a=Math.max(this.Min?this.minHeight:a,a,0)},RepairWidth:function(a,c){a=Math.min(this.Max?c:a,a);return a=Math.max(this.Min?this.minWidth:a,a,0)},RepairScaleHeight:function(a){return Math.max(Math.round((a+this._borderX)/
this.Ratio-this._borderY),0)},RepairScaleWidth:function(a){return Math.max(Math.round((a+this._borderY)*this.Ratio-this._borderX),0)},TurnRight:function(a){if(!this.Min&&!this._styleWidth)return this._fun=a,this._sideLeft=this._sideRight,this.Max&&this._mxSet(),!0},TurnLeft:function(a){if(!this.Min&&!this._styleWidth)return this._fun=a,this._sideRight=this._sideLeft,this._fixLeft=this._styleLeft,this.Max&&this._mxSet(),!0},TurnUp:function(a){if(!this.Min&&!this._styleHeight)return this._fun=a,this._sideDown=
this._sideUp,this._fixTop=this._styleTop,this.Max&&this._mxSet(),!0},TurnDown:function(a){if(!this.Min&&!this._styleHeight)return this._fun=a,this._sideUp=this._sideDown,this.Max&&this._mxSet(),!0},Stop:function(){removeEventHandler(document,"mousemove",this._fR);removeEventHandler(document,"mouseup",this._fS);isIE?(removeEventHandler(this._obj,"losecapture",this._fS),this._obj.releaseCapture()):removeEventHandler(window,"blur",this._fS);this.ResizeEnd()},ResizeEnd:function(){}};
