var ID_REQUEST=1,rpcCore={sessionID:0},PTZ_REQUEST=0;function getSeq(){var a=parseInt(rpcCore.sessionID).toString(2).slice(-24),b=("00000000"+PTZ_REQUEST.toString(2)).slice(-8);PTZ_REQUEST=(PTZ_REQUEST+1)%256;return parseInt(a+b,2)}
function sendRequest(a,b,c,d,e){d==void 0&&(d="/RPC2");c==void 0&&(c=!0);b==void 0&&(b=function(){});e==void 0&&(e=function(){});return(new Request({url:d,async:c,headers:{"X-Request":"JSON"},onSuccess:function(a){var c=JSON.decode(a);b(a,c)},onFailure:function(){e()}})).send(a)}
var RPCCall=new Class({initialize:function(a){a==void 0?rpcCore.sessionID==0?(a=Cookie.read("DhWebClientSessionID"))?(this.sessionID=a,rpcCore.sessionID=a):this.sessionID=0:this.sessionID=rpcCore.sessionID:this.sessionID=a},setSessionID:function(a){this.sessionID=a},getRequest:function(a,b,c){b==void 0&&(b=null);var d="";return d=c==void 0?'{"method":"'+a+'","params":'+b+',"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}":'{"object":'+c+',"method":"'+a+'","params":'+b+',"session":'+rpcCore.sessionID+
',"id":'+ID_REQUEST++ +"}"},doMutiCall:function(a,b,c){a=this.getRequest("system.multicall","["+a+"]");return sendRequest(a,b,c)}}),System=new Class({Extends:RPCCall,listService:function(a,b){var c=this.getRequest("system.listService");sendRequest(c,a,b)}}),Global=new Class({Extends:RPCCall,getCurrentTime:function(a,b){var c=this.getRequest("global.getCurrentTime");sendRequest(c,a,b)},setCurrentTime:function(a,b,c,d){a=this.getRequest("global.setCurrentTime",JSON.encode({time:a,tolerance:b}));sendRequest(a,
c,d)}}),ConfigManager=new Class({Extends:RPCCall,getConfig:function(a,b,c){c==void 0&&(c=!0);var d;if($type(a)=="array"){d=this.getRequest("configManager.getConfig",'{"name":"'+a[0]+'"}');for(var e=1;e<a.length;e++)d+=", "+this.getRequest("configManager.getConfig",'{"name":"'+a[e]+'"}');this.doMutiCall(d,b,c)}else d=this.getRequest("configManager.getConfig",'{"name":"'+a+'"}'),sendRequest(d,b,c)},setConfig:function(a,b,c,d){d==void 0&&(d=!0);var e;if($type(a)=="array"){e=this.getRequest("configManager.setConfig",
'{"name":"'+a[0]+'","table":'+JSON.encode(b[0])+',"options":""}');for(var f=1;f<a.length;f++)e+=", "+this.getRequest("configManager.setConfig",'{"name":"'+a[f]+'","table":'+JSON.encode(b[f])+',"options":""}');this.doMutiCall(e,c,d)}else e=this.getRequest("configManager.setConfig",'{"name":"'+a+'","table":'+JSON.encode(b)+',"options":""}'),sendRequest(e,c,d)},getDefault:function(a,b,c){c==void 0&&(c=!0);var d;if($type(a)=="array"){d=this.getRequest("configManager.getDefault",'{"name":"'+a[0]+'"}');
for(var e=1;e<a.length;e++)d+=", "+this.getRequest("configManager.getDefault",'{"name":"'+a[e]+'"}');this.doMutiCall(d,b,c)}else d=this.getRequest("configManager.getDefault",'{"name":"'+a+'"}'),sendRequest(d,b,c)},restore:function(a,b,c){a=$type(a)=="array"?this.getRequest("configManager.restore",'{"names":'+JSON.encode(a)+"}"):this.getRequest("configManager.restore",'{"names":["'+a+'"]}');sendRequest(a,b,c)},restoreExcept:function(a,b,c){a=$type(a)=="array"?this.getRequest("configManager.restoreExcept",
'{"names":'+JSON.encode(a)+"}"):this.getRequest("configManager.restoreExcept",'{"names":["'+a+'"]}');sendRequest(a,b,c)},restoreTemporaryConfig:function(a,b,c){c==void 0&&(c=!0);var d;if($type(a)=="array"){d=this.getRequest("configManager.restoreTemporaryConfig",'{"name":"'+a[0]+'"}');for(var e=1;e<a.length;e++)d+=", "+this.getRequest("configManager.restoreTemporaryConfig",'{"name":"'+a[e]+'"}');this.doMutiCall(d,b,c)}else d=this.getRequest("configManager.restoreTemporaryConfig",'{"name":"'+a+'"}'),
sendRequest(d,b,c)},setTemporaryConfig:function(a,b,c,d){d==void 0&&(d=!0);var e;if($type(a)=="array"){e=this.getRequest("configManager.setTemporaryConfig",'{"name":"'+a[0]+'","table":'+JSON.encode(b[0])+',"options":""}');for(var f=1;f<a.length;f++)e+=", "+this.getRequest("configManager.setTemporaryConfig",'{"name":"'+a[f]+'","table":'+JSON.encode(b[f])+',"options":""}');this.doMutiCall(e,c,d)}else e=this.getRequest("configManager.setTemporaryConfig",'{"name":"'+a+'","table":'+JSON.encode(b)+',"options":""}'),
sendRequest(e,c,d)}}),LogService=new Class({Extends:RPCCall,getSummary:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "log.getSummary","session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},getLogToken:function(a){var b,a=this.getRequest("log.startFind",'{"condition":'+a+"}");sendRequest(a,function(a){b=JSON.decode(a).result?JSON.decode(a).params.token:-1},!1);return b},doFind:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("log.doFind",'{"token":'+a+',"count":'+
b+"}");sendRequest(a,c,d)},stopFind:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("log.stopFind",'{"token":'+a+"}");sendRequest(a,b,c)},clear:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "log.clear","session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)}}),EventManager=new Class({Extends:RPCCall,attachEvent:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("eventManager.attach",'{"codes":'+JSON.encode(a)+"}");sendRequest(a,b,c)},detachEvent:function(a,b,c,d){d==
void 0&&(d=!0);a=this.getRequest("eventManager.detach",'{"SID":'+a+',"codes":'+JSON.encode(b)+"}");sendRequest(a,c,d)},getEventData:function(a,b,c,d,e){e==void 0&&(e=!0);a=this.getRequest("eventManager.getEventData",'{"code":"'+a+'","index":'+b+',"name":"'+c+'"}');sendRequest(a,d,e)},getCaps:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("eventManager.getCaps",'""');sendRequest(c,a,b)}}),UserManager=new Class({Extends:RPCCall,getAuthorityList:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("userManager.getAuthorityList",
'""');sendRequest(c,a,b)},addGroup:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("userManager.addGroup",'{"group":'+JSON.encode(a)+"}");sendRequest(a,b,c)},deleteGroup:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("userManager.deleteGroup",'{"name":"'+a+'"}');sendRequest(a,b,c)},modifyGroup:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("userManager.modifyGroup",'{"name":"'+a+'","group":'+JSON.encode(b)+"}");sendRequest(a,c,d)},getGroupInfo:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("userManager.getGroupInfo",
'{"name":"'+a+'"}');sendRequest(a,b,c)},getGroupInfoAll:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("userManager.getGroupInfoAll",'""');sendRequest(c,a,b)},addUser:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("userManager.addUser",'{"user":'+JSON.encode(a)+"}");sendRequest(a,b,c)},deleteUser:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("userManager.deleteUser",'{"name":"'+a+'"}');sendRequest(a,b,c)},modifyUser:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("userManager.modifyUser",
'{"name":"'+a+'","user":'+JSON.encode(b)+"}");sendRequest(a,c,d)},modifyPassword:function(a,b,c,d,e){e==void 0&&(e=!0);a=this.getRequest("userManager.modifyPassword",'{"name":"'+a+'", "pwd":"'+b+'", "pwdOld":"'+c+'"}');sendRequest(a,d,e)},getUserInfo:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("userManager.getUserInfo",'{"name":"'+a+'"}');sendRequest(a,b,c)},getUserInfoAll:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("userManager.getUserInfoAll",'""');sendRequest(c,a,b)},setDefault:function(a,
b){b==void 0&&(b=!0);var c;c=this.getRequest("userManager.getDefault",'""');sendRequest(c,a,b)},saveFile:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("userManager.saveFile",'""');sendRequest(c,a,b)},getActiveUserInfoAll:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("userManager.getActiveUserInfoAll",'""');sendRequest(c,a,b)}}),AudioRecordManager=new Class({Extends:RPCCall,startChannel:function(a,b,c,d,e){e==void 0&&(e=!0);b='{"method" : "audioRecordManager.startChannel","params":{"channel" : '+
b+', "stream" : "'+c+'" , "path" : "'+d+'" }, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,e)},stopChannel:function(a,b,c,d,e){e==void 0&&(e=!0);b='{"method" : "audioRecordManager.stopChannel","params":{"channel" : '+b+', "stream" : "'+c+'" , "path" : "'+d+'" }, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,e)},getStateAll:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "audioRecordManager.getStateAll","params":null, "session":'+rpcCore.sessionID+
',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)}}),Speak=new Class({Extends:RPCCall,startPlay:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "speak.startPlay","params":{"channel" : '+b+', "path" : "'+c+'" }, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)}}),MagicBox=new Class({Extends:RPCCall,getProductDef:function(a,b,c){c==void 0&&(c=!0);var d;if($type(a)=="array"){d=this.getRequest("magicBox.getProductDefinition",'{"name":"'+a[0]+'"}');for(var e=1;e<a.length;e++)d+=
", "+this.getRequest("magicBox.getProductDefinition",'{"name":"'+a[e]+'"}');return this.doMutiCall(d,b,c)}else return d=this.getRequest("magicBox.getProductDefinition",'{"name":"'+a+'"}'),sendRequest(d,b,c)},getSerialNo:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("magicBox.getSerialNo",'""');sendRequest(c,a,b)},getDeviceType:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("magicBox.getDeviceType",'""');sendRequest(c,a,b)},getSubModules:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("magicBox.getSubModules",
'""');sendRequest(c,a,b)},getDeviceClass:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("magicBox.getDeviceClass",'""');sendRequest(c,a,b)},getSystemInfo:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("magicBox.getSystemInfo",'""');sendRequest(c,a,b)},reboot:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("magicBox.reboot",'""');sendRequest(c,a,b)},getProcessInfo:function(a,b){var c=this.getRequest("magicBox.getProcessInfo");return sendRequest(c,a,b)},getSystemInfoNew:function(a,
b){var c=this.getRequest("magicBox.getSystemInfoNew");sendRequest(c,a,b)}}),Upgrader=new Class({Extends:RPCCall,prepare:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("upgrader.prepare",'""');sendRequest(c,a,b)},appendData:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("upgrader.appendData",'{"length":'+a+"}")+b;sendRequest(a,c,d)},getStatus:function(a,b,c){c==void 0&&(c=!0);var d;d=this.getRequest("upgrader.getState",'""');sendRequest(d,a,c,"/RPC2",b)},cancel:function(a,b){b==void 0&&
(b=!0);var c;c=this.getRequest("upgrader.cancel",'""');sendRequest(c,a,b)},execute:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("upgrader.execute",'""');sendRequest(c,a,b)}}),VideoInput=new Class({Extends:RPCCall,ptz:function(a,b,c,d,e){a=this.getRequest("devVideoInput.ptz",JSON.encode({pan:a,tilte:b,zoom:c}));sendRequest(a,d,e)},getVideoInStatus:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "devVideoInput.getVideoInStatus","params":{"channel" : '+b+'},"session":'+rpcCore.sessionID+
',"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},getCaps:function(a,b,c){b=this.getRequest("devVideoInput.getCaps",'{"channel":'+b+"}");sendRequest(b,a,c)},getCapsEx:function(a,b,c,d){b=this.getRequest("devVideoInput.getCapsEx",'{"channel":'+b+',"Name": "'+c+'"}');sendRequest(b,a,d)},getObjectID:function(a,b,c){b=this.getRequest("devVideoInput.factory.instance",'{"channel":'+b+"}");sendRequest(b,a,c)},adjustFocus:function(a,b,c,d,e){b=this.getRequest("devVideoInput.adjustFocus",'{"channel": '+b+',"focus": '+
c+', "zoom": '+d+"}");sendRequest(b,a,e)},autoFocus:function(a,b,c){b=this.getRequest("devVideoInput.autoFocus",'{"channel": '+b+"}");sendRequest(b,a,c)},getFocusStatus:function(a,b,c){b=this.getRequest("devVideoInput.getFocusStatus",'{"channel": '+b+"}");sendRequest(b,a,c)},adjustFocusContinuously:function(a,b,c,d,e){b=this.getRequest("devVideoInput.adjustFocusContinuously",'{"channel": '+b+',"focus": '+c+', "zoom": '+d+"}");sendRequest(b,a,e)},getFishEyeWinInfo:function(a,b,c,d){a=this.getRequest("devVideoInput.getFishEyeWinInfo",
'{"channel": '+a+',"winIdSet": ['+b+"]}");sendRequest(a,c,d)},setFishEyeEPtz:function(a,b,c,d,e,f,g,h,i){a=this.getRequest("devVideoInput.setFishEyeEPtz",'{"channel": '+a+',"winID": '+b+',"cmd": "'+c+'","arg1": '+d+',"arg2": '+e+',"arg3": '+f+',"arg4": '+g+"}");sendRequest(a,h,i)},setTempVideoInOptions:function(a,b,c,d){a=this.getRequest("devVideoInput.setTempVideoInOptions",'{"options": '+JSON.encode(b)+"}",a);sendRequest(a,c,d)},instance:function(a,b,c){a=this.getRequest("devVideoInput.factory.instance",
'{"channel": '+a+"}");sendRequest(a,b,c)},focusRegion:function(a,b,c,d,e){e==void 0&&(e=!0);b='{"method" : "devVideoInput.focusRegion", "session" : '+rpcCore.sessionID+', "params" : {"mode": "'+b+'", "rect" : ['+c+'],"channel":'+d+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,e)},stopAutoFocus:function(a,b,c){b=this.getRequest("devVideoInput.stopAutoFocus",'{"channel": '+b+"}");sendRequest(b,a,c)}}),DevVideoOut=new Class({Extends:RPCCall,instance:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devVideoOutput.factory.instance",
'{"channel":'+a+"}");sendRequest(a,b,c)},enumModes:function(a,b,c){c==void 0&&(c=!0);b=this.getRequest("devVideoOutput.enumModes",'{"channel":'+b+"}");sendRequest(b,a,c)},getCollect:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devVideoOutput.factory.getCollect",'{"channel":'+(a||0)+"}");return sendRequest(a,b,c)}}),DevVideoDetect=new Class({Extends:RPCCall,instance:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devVideoDetect.factory.instance",'{"channel":'+a+"}");sendRequest(a,b,c)},
destroy:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("devVideoDetect.destroy",'""',a);sendRequest(c,function(){},b)},attachMotionData:function(a,b,c){c==void 0&&(c=!0);b=this.getRequest("devVideoDetect.attachMotionData",'{"proc":'+b+"}");sendRequest(b,a,c)},detachMotionData:function(a,b,c){c==void 0&&(c=!0);b=this.getRequest("devVideoDetect.detachMotionData",'{"proc":'+b+"}");sendRequest(b,a,c)},getCaps:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devVideoDetect.getCaps",'""',a);
sendRequest(a,b,c)}}),DevVideoEnc=new Class({Extends:RPCCall,instance:function(a,b,c,d){d==void 0&&(d=!0);a='{"method" : "devVideoEncode.factory.instance","params" : {"channel" : '+a+', "group":0, "stream":"'+b+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,c,d)},getCaps:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devVideoEncode.getCaps",'""',a);sendRequest(a,b,c)}}),EncodeManager=new Class({Extends:RPCCall,getConfigCaps:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("encode.getConfigCaps",
'{"config":'+JSON.encode(a)+"}");sendRequest(a,b,c)},updateOverlayPicture:function(a,b,c){json_string=this.getRequest("encode.updateOverlayPicture",JSON.encode({Pictures:[{Name:a}]}));sendRequest(json_string,b,c)}}),AudioInput=new Class({Extends:RPCCall,getCollect:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("devAudioInput.factory.getCollect",'""');return sendRequest(c,a,b)},getSourceList:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devAudioInput.getCaps",'{"channel":'+a+"}");sendRequest(a,
b,c)},getCaps:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devAudioInput.getCaps",'{"channel":'+a+"}");sendRequest(a,b,c)}}),PtzCtrl=new Class({Extends:RPCCall,pztPostResult:function(a){JSON.decode(a).result||alert(tl("Set PTZ first!"))},sendPtzRequest:function(a,b,c,d,e){b=b=="LeftUp"||b=="RightUp"||b=="LeftDown"||b=="RightDown"?'"code" : "'+b+'","arg1" : '+c+',"arg2" : '+c+',"arg3" : 0':'"code" : "'+b+'","arg1" : '+c+',"arg2" : '+d+',"arg3" : 0';a=a?'{"method" : "ptz.start", "session" : '+
rpcCore.sessionID+',"params" : {"channel" : '+e+", "+b+'}, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +"}":'{"method" : "ptz.stop", "session" : '+rpcCore.sessionID+',"params" : {"channel" : '+e+", "+b+'}, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +"}";sendRequest(a,this.pztPostResult,!0)},sendPtzRequestEx:function(a,b,c,d,e,f,g){b='"code" : "'+b+'","arg1" : '+c+',"arg2" : '+d+',"arg3" : '+e;a=a?'{"method" : "ptz.start", "session" : '+rpcCore.sessionID+',"params" : {"channel" : '+f+", "+b+'}, "seq":'+
getSeq()+', "id" : '+ID_REQUEST++ +"}":'{"method" : "ptz.stop", "session" : '+rpcCore.sessionID+',"params" : {"channel" : '+f+", "+b+'}, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +"}";g==void 0&&(g=!0);sendRequest(a,this.pztPostResult,g)},start:function(a,b,c,d,e,f,g){g==void 0&&(g=0);f==void 0&&(f=!0);ptzJson='{"method" : "ptz.start", "session" : '+rpcCore.sessionID+',"params" : {'+('"channel":'+g+',"code" : "'+a+'","arg1" : '+b+',"arg2" : '+c+',"arg3" : '+d)+'}, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +
"}";sendRequest(ptzJson,e,f)},stop:function(a,b,c,d,e,f,g){g==void 0&&(g=0);f==void 0&&(f=!0);ptzJson='{"method" : "ptz.stop", "session" : '+rpcCore.sessionID+',"params" : {'+('"channel":'+g+',"code" : "'+a+'","arg1" : '+b+',"arg2" : '+c+',"arg3" : '+d)+'}, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +"}";sendRequest(ptzJson,e,f)},getProtocolList:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("ptz.getProtocolList",'""');sendRequest(c,a,b)},getCurrentProtocolCaps:function(a,b,c){b==void 0&&
(b=0);c==void 0&&(c=!0);b=this.getRequest("ptz.getCurrentProtocolCaps",'{"channel" : '+b+"}");return sendRequest(b,a,c)},instance:function(a,b,c){b==void 0&&(b=!0);c==void 0&&(c=0);c=this.getRequest("ptz.factory.instance",'{"channel" : '+c+"}");sendRequest(c,a,b)},getStatus:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.getStatus", "session" : '+rpcCore.sessionID+',"params" : null,"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},setPreset:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.setPreset", "session" : '+
rpcCore.sessionID+',"params" : {"index" : '+b+', "name" : "'+c+'"},"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},getPresets:function(a,b){b==void 0&&(b=!0);var c;c='{ "method" : "ptz.getPresets", "session" : '+rpcCore.sessionID+',"params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},gotoPreset:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.gotoPreset", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+', "speed" : '+c+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},
removePreset:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.removePreset", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},setTour:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.setTour", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+', "name" : "'+c+'"},"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},getTours:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.getTours", "session" : '+rpcCore.sessionID+
',"params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},removeTour:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.removeTour", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},addTourPoint:function(a,b,c,d,e,f,g){g==void 0&&(g=!0);b='{"method" : "ptz.addTourPoint", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+", "+('"point" : '+c+', "presetIndex" : '+d+',"duration" : '+e+',"speed" : '+f+"")+'}, "id" : '+
ID_REQUEST++ +"}";sendRequest(b,a,g)},removeTourPoint:function(a,b,c,d,e){e==void 0&&(e=!0);b='{"method" : "ptz.removeTourPoint", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+", "+('"point" : '+c+', "presetIndex" : '+d+" ")+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,e)},getTourPoints:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.getTourPoints", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},startTour:function(a,
b,c){c==void 0&&(c=!0);b='{"method" : "ptz.startTour", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},autoTour:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.autoTour", "session" : '+rpcCore.sessionID+',"params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},stopTour:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.stopTour", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";
sendRequest(b,a,c)},startPatternRecord:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.startPatternRecord", "session" : '+rpcCore.sessionID+',"params" : {"index" : '+b+', "name" : "'+c+'"},"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},stopPatternRecord:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.stopPatternRecord", "session" : '+rpcCore.sessionID+', "params" : {"index" : '+b+'},"id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},getPatterns:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.getPatterns", "session" : '+
rpcCore.sessionID+', "params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},removePattern:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.getPatterns", "session" : '+rpcCore.sessionID+', "params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},startPatternReplay:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.startPatternReplay", "session" : '+rpcCore.sessionID+', "params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},stopPatternReplay:function(a,
b,c){c==void 0&&(c=!0);b='{"method" : "ptz.stopPatternReplay", "session" : '+rpcCore.sessionID+', "params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},setScanLimit:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.setScanLimit", "session" : '+rpcCore.sessionID+', "params" : {"index" : '+b+', "limitMode" : "'+c+'"}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},startScan:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.startScan", "session" : '+rpcCore.sessionID+
', "params" : {"index" : '+b+', "speed" : '+c+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},stopScan:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.stopScan", "session" : '+rpcCore.sessionID+', "params" : {"index" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},restartPtz:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.restartPtz", "session" : '+rpcCore.sessionID+', "params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},restartCamera:function(a,b){b==void 0&&
(b=!0);var c;c='{ "method" : "ptz.restartCamera", "session" : '+rpcCore.sessionID+', "params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},reset:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.reset", "session" : '+rpcCore.sessionID+', "params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},moveRelatively:function(a,b,c,d){d==void 0&&(d=!0);b='{ "method" : "ptz.moveRelatively", "session" : '+rpcCore.sessionID+', "params" : {"position" : '+b+', "speed" : '+c+'}, "id" : '+
ID_REQUEST++ +"}";sendRequest(b,a,d)},moveDirectly:function(a,b,c,d){d==void 0&&(d=!0);b=c==void 0?'{"method" : "ptz.moveDirectly", "session" : '+rpcCore.sessionID+', "params" : {"screen" : ['+b+']}, "id" : '+ID_REQUEST++ +"}":'{"method" : "ptz.moveDirectly", "session" : '+rpcCore.sessionID+', "params" : {"screen" : ['+b+'], "speed" : ['+c+']}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},moveContinuouslyDirectly:function(a,b,c,d,e,f){f==void 0&&(f=!0);b='{"method" : "ptz.continueMoveDirectly", "session" : '+
rpcCore.sessionID+', "params" : {"screenDetail": {"index":'+b+', "timeInterval":'+c+', "isLastScreen":'+d+'}, "screen" : ['+e+']}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,f)},moveContinuously:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.moveContinuously", "session" : '+rpcCore.sessionID+', "params" : {"speed" : ['+b+'], "timeout" : '+c+'}, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},stopMove:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.stopMove", "session" : '+
rpcCore.sessionID+', "params" : null, "seq":'+getSeq()+', "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},markLimit:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.markLimit", "session" : '+rpcCore.sessionID+', "params" : {"type" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},gotoLimit:function(a,b,c){c==void 0&&(c=!0);b='{"method" : "ptz.gotoLimit", "session" : '+rpcCore.sessionID+', "params" : {"type" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},enableLimit:function(a,
b,c){c==void 0&&(c=!0);b='{ "method" : "ptz.enableLimit", "session" : '+rpcCore.sessionID+', "params" : {"enable" : '+b+'}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)},setRegionFocus:function(a,b,c,d){d==void 0&&(d=!0);b='{"method" : "ptz.focusRegion", "session" : '+rpcCore.sessionID+', "params" : {"mode": "'+b+'", "rect" : ['+c+']}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,d)},directionCalibration:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "ptz.directionCalibration", "session" : '+
rpcCore.sessionID+', "params" : null, "id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},setDirection:function(a,b,c){c==void 0&&(c=!0);b==void 0&&(b="North");b='{"method" : "ptz.setDirection", "session" : '+rpcCore.sessionID+', "params" : {"direction" : "'+b+'"}, "id" : '+ID_REQUEST++ +"}";sendRequest(b,a,c)}}),IDevIntelliTracker=new Class({Extends:RPCCall,markSceneMaxZoom:function(a,b,c){c==void 0&&(c=!0);a='{"method" : "devIntelliTracker.markSceneMaxZoom","params":{"scene":'+a+'},"session":'+rpcCore.sessionID+
',"id" : '+ID_REQUEST++ +"}";sendRequest(a,b,c)},markScene:function(a,b,c){c==void 0&&(c=!0);a='{"method" : "devIntelliTracker.markScene","params":{"scene":'+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,b,c)},gotoScene:function(a,b,c){c==void 0&&(c=!0);a='{"method" : "devIntelliTracker.gotoScene","params":{"scene":'+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,b,c)},markSceneLimit:function(a,b,c,d){d==void 0&&(d=!0);a='{"method" : "devIntelliTracker.markSceneLimit","params":{"scene":'+
a+', "type" : "'+b+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,c,d)},gotoSceneLimit:function(a,b,c,d){d==void 0&&(d=!0);a='{"method" : "devIntelliTracker.gotoSceneLimit","params":{"scene":'+a+', "type" : "'+b+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,c,d)},start:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "devIntelliTracker.start","params":null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},
stop:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "devIntelliTracker.stop","params":null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},trackObject:function(a,b,c,d){d==void 0&&(d=!0);a='{"method" : "devIntelliTracker.trackObject","params":{"object":{"ObjectID":'+a+', "BoundingBox" : ['+b+']}},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,c,d)}}),VideoAnalyseDevice=new Class({Extends:RPCCall,getVideoAnalyseCap:function(a,b,c){c==void 0&&
(c=!0);b='{"method" : "devVideoAnalyse.getCaps","params":{"channel" : '+b+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";return sendRequest(b,a,c)}}),Split=new Class({Extends:RPCCall,instance:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("split.factory.instance",'{"channel":'+a+"}");sendRequest(a,b,c)},getCaps:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("split.getCaps",'""',a);sendRequest(a,b,c)},destroy:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("split.destroy",
'""',a);sendRequest(a,b,c)}}),CapsManager=new Class({Extends:RPCCall,instance:function(a,b){b===void 0&&(b=!0);var c;c='{"method" : "capsManager.factory.instance","params" : null, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},get:function(a,b,c,d){d===void 0&&(d=!0);var e;if($type(b)=="array"){e='{"method" : "capsManager.get","params" : {"channel": '+a+', "path": "'+b[0]+'"}, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";for(var f=1;f<b.length;f++)e+=
', {"method" : "capsManager.get","params" : {"channel": '+a+', "path": "'+b[f]+'"}, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";this.doMutiCall(e,c,d)}else e='{"method" : "capsManager.get","params" : {"channel": '+a+', "path": "'+b+'"}, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",sendRequest(e,c,d)},destroy:function(a,b){b===void 0&&(b=!0);var c;c='{"method" : "capsManager.destroy","params" :null, "session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,
a,b)}}),DevComm=new Class({Extends:RPCCall,getCollect:function(a,b){b==void 0&&(b=!0);var c;c=this.getRequest("devComm.factory.getCollect",'""');sendRequest(c,a,b)}}),Alarm=new Class({Extends:RPCCall,getInState:function(a,b){b===void 0&&(b=!0);var c;c=this.getRequest("alarm.getInState",'""');sendRequest(c,a,b)},getOutState:function(a,b){b===void 0&&(b=!0);var c;c=this.getRequest("alarm.getOutState",'""');sendRequest(c,a,b)},getInSlots:function(a,b){b===void 0&&(b=!0);var c;c=this.getRequest("alarm.getInSlots",
'""');sendRequest(c,a,b)},getOutSlots:function(a,b){b===void 0&&(b=!0);var c;c=this.getRequest("alarm.getOutSlots",'""');sendRequest(c,a,b)},addressbinding:function(a,b,c,d){d===void 0&&(d=!0);a=this.getRequest("alarm.addressbinding",'{"WirelessDevice":{"DeviceType":'+a+',"Index":'+b+"}}");sendRequest(a,c,d)},setArmMode:function(a,b,c,d){d===void 0&&(d=!0);a=this.getRequest("alarm.setArmMode",'{"Arm":{"Delay":'+a+',"Status":'+b+"}}");sendRequest(a,c,d)},getArmMode:function(a,b){b===void 0&&(b=!0);
var c;c=this.getRequest("alarm.getArmMode",'""');sendRequest(c,a,b)}}),StorageDev=new Class({Extends:RPCCall,getDeviceNames:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "storage.getDeviceNames","params":null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},getGroupNames:function(a,b){b==void 0&&(b=!0);var c;c='{"method" : "storage.getGroupNames","params":null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},getDevPnt:function(a){var b,
a='{"method" : "storage.getDevice","params":{"name":"'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,function(a){b=JSON.decode(a).result},!1);return b},getDirectory:function(a){var b,a='{"method" : "storage.getDirectory","params":{"path":"'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,function(a){b=JSON.decode(a).result},!1);return b},getiSCSITargets:function(a,b,c,d,e,f){f==void 0&&(f=!0);a='{"method" : "storage.getiSCSITargets","params":{"Address":"'+
a+'","Port":'+b+',"UserName":"'+c+'","Password":"'+d+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,e,f)},isGroupFull:function(a,b,c){c==void 0&&(c=!0);a='{"method" : "storage.isGroupFull","params":{"group":"'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,b,c)},getCurrentDirectory:function(a,b,c){c==void 0&&(c=!0);a='{"method" : "storage.getCurrentDirectory","params" : {"group" : "'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +
"}";sendRequest(a,b,c)},testNAS:function(a,b,c){a=this.getRequest("storage.testNAS",'{"NAS":'+JSON.encode(a)+"}");sendRequest(a,b,c)},getDeviceAllInfo:function(a,b){var c='{"method" : "storage.getDeviceAllInfo","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},getDeviceInfo:function(a,b,c){c==void 0&&(c=!0);a='{"method" : "devStorage.getDeviceInfo","params" : {"pointer" : '+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,b,
c)},getDeviceInfoEx:function(a,b,c){c==void 0&&(c=!0);a='{"object":'+a+',"method" : "devStorage.getDeviceInfo","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,b,c)},releaseDevice:function(a){json_string='{"method" : "devStorage.releaseDevice","params":{"pointer":'+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(json_string,function(){},!1)},deletePartition:function(a,b,c,d){d==void 0&&(d=!0);a='{"object":'+a+',"method" : "devStorage.deletePartition","params" : {"part" : "'+
b+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,c,d)},destroy:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("devStorage.destroy",'""',a);sendRequest(a,b,c)},releaseDirectory:function(a){json_string='{"method" : "workDirectory.releaseDirectory","params":{"pointer":'+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(json_string,function(){},!1)},getCapacity:function(a){var b=[],c='{"method" : "workDirectory.getFreeSpace","params" : {"pointer" :'+
a+'},"session":'+rpcCore.sessionID+',"id" :'+ID_REQUEST++ +"}",a='{"method" : "workDirectory.getTotalSpace","params" : {"pointer" :'+a+'},"session":'+rpcCore.sessionID+',"id" :'+ID_REQUEST++ +"}";sendRequest(a,function(a){b[0]=JSON.decode(a).result?JSON.decode(a).params.totalSpace:0},!1);sendRequest(c,function(a){b[1]=JSON.decode(a).result?JSON.decode(a).params.freeSpace:0},!1);return b},startRecord:function(){var a='{"method" : "recordManager.start","params" : null,"session":'+rpcCore.sessionID+
',"id" : '+ID_REQUEST++ +"}",b='{"method" : "snapManager.start","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",c=function(){};sendRequest(a,c,!1);sendRequest(b,c,!1)},stopRecord:function(){var a='{"method" : "recordManager.stop","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",b='{"method" : "snapManager.stop","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",c=function(){};sendRequest(a,c,!1);sendRequest(b,c,!1)},formatPatition:function(a,
b){this.stopRecord();var c='{"method" : "devStorage.formatPatition","params" : {"pointer" : '+a+',"part" : '+b+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",d;sendRequest(c,function(a){d=JSON.decode(a).result},!1);this.startRecord();return d},formatPatitionEx:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("devStorage.formatPatition",'{"part" : "'+b+'", "fs" : "FAT32"}',a);sendRequest(a,c,d)},eject:function(a){var a='{"method" : "devStorage.eject","params" : {"pointer" : '+a+
'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",b;sendRequest(a,function(a){b=JSON.decode(a).result},!1);return b},setType:function(a,b){var c='{"method" : "workDirectory.setType","params":{"pointer":'+a+',"type":"'+b+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",d;sendRequest(c,function(a){d=JSON.decode(a).result},!1);return d},getType:function(a){var a='{"method" : "workDirectory.getType","params":{"pointer" :'+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +
"}",b;sendRequest(a,function(a){b=JSON.decode(a).result},!1);return b},isError:function(a){var a='{"method" : "workDirectory.isError","params" : {"pointer" :'+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}",b=!1;sendRequest(a,function(a){b=JSON.decode(a).result},!1);return b}}),ChannelNumInfo=new Class({Extends:RPCCall,getChannelNO:function(){var a=0,b=this.getRequest("devVideoInput.getChannels");sendRequest(b,function(b){a=JSON.decode(b).result-0},!1);return a},getAlarmIN:function(){var a=
0,b=this.getRequest("alarm.getInSlots");sendRequest(b,function(b){a=JSON.decode(b).params.inputs-0},!1);return a},getAlarmOUT:function(){var a=0,b=this.getRequest("alarm.getOutSlots");sendRequest(b,function(b){a=JSON.decode(b).params.outputs-0},!1);return a}}),NetApp=new Class({Extends:RPCCall,getNetInterfaces:function(a,b,c){b==void 0&&(b=!0);c=c==void 0?this.getRequest("netApp.getNetInterfaces",'""'):this.getRequest("netApp.getNetInterfaces",'""',c);return sendRequest(c,a,b)},instance:function(a,
b){var c=this.getRequest("netApp.factory.instance");sendRequest(c,a,b)},destroy:function(a,b,c){c=this.getRequest("netApp.destroy",null,c);sendRequest(c,a,b)},scanWLanDevices:function(a,b,c){a=this.getRequest("netApp.scanWLanDevices",'{"Name":"'+a+'"}',c);return sendRequest(a,b,c)},getDialInfo:function(a,b,c,d){a=this.getRequest("netApp.getDialInfo",'{"Name":"'+a+'"}',d);sendRequest(a,b,c)},getDialInfoAdd:function(a,b,c){c=this.getRequest("netApp.getDialInfo",'{"Name":"3G"}',c);sendRequest(c,a,b)},
getMobileRSSI:function(a,b,c){c=this.getRequest("netApp.getMobileRSSI",null,c);sendRequest(c,a,b)},getMobileRSSIAdd:function(a,b,c){c=this.getRequest("netApp.getMobileRSSI",'{"Name":"3G"}',c);sendRequest(c,a,b)},sendTestMail:function(a,b,c){c=this.getRequest("netApp.sendTestMail",'""',c);sendRequest(c,a,b)},getSipRegisterStatus:function(a,b){var c=this.getRequest("netApp.getSipRegisterStatus",'""');sendRequest(c,a,b)},getPingStatus:function(a,b,c){json_string='{"method" : "netApp.getPingStatus","params":{"Address":"'+
a+'"},"session":'+parent.rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(json_string,b,c)},getUPnPStatus:function(a,b,c){c=this.getRequest("netApp.getUPnPStatus",'""',c);sendRequest(c,a,b)},refreshUpnpRouter:function(a,b,c){c=this.getRequest("netApp.refreshUpnpRouter",'""',c);sendRequest(c,a,b)},getConnectWlanStatus:function(a,b,c){c=this.getRequest("netApp.getNetInterfaces",'""',c);sendRequest(c,a,b)},scanWLanIsExist:function(a,b,c,d){a=this.getRequest("netApp.scanWLanDevices",'{"Name":"'+
a+'","SSID":"'+b+'"}',d);return sendRequest(a,c,d)},connectByWps:function(a,b,c,d,e,f,g){a=this.getRequest("netApp.connectByWps",JSON.encode({info:{ApPin:a,SSID:b,WLanPin:d,Type:c}}),g);sendRequest(a,e,f)},getRemoteDeviceStatus:function(a,b,c){b==void 0&&(b=!0);c=c==void 0?this.getRequest("netApp.getRemoteDeviceStatus",'""'):this.getRequest("netApp.getRemoteDeviceStatus",'""',c);sendRequest(c,a,b)},getSipRegisterStatus:function(a,b){var c=this.getRequest("netApp.getSipRegisterStatus",'""');sendRequest(c,
a,b)}}),DDNSClient=new Class({Extends:RPCCall,testHostName:function(a,b,c,d,e,f,g,h){a=this.getRequest("ddnsClient.testHostName",JSON.encode({Protocol:a,Address:b,Port:c,HostName:d,UserName:e,Password:f}));sendRequest(a,g,h)},getStatus:function(a,b,c){b==void 0&&(b=!0);c=c==void 0?this.getRequest("ddnsClient.getStatus",'""'):this.getRequest("ddnsClient.getStatus",'""',c);sendRequest(c,a,b)}}),Timeout_Times=5,KeepAlive=new Class({Extends:RPCCall,start:function(a,b){var c=this.getRequest("global.keepAlive",
'{"timeout": '+a+"}");(new Request({url:"/RPC2",async:!0,headers:{"X-Request":"JSON"},onSuccess:function(a){JSON.decode(a).result?Timeout_Times=5:(--Timeout_Times,Timeout_Times<=0?(alert(tl("The connection is Overtime.")),top.location="/"):b&&b())},onFailure:function(){--Timeout_Times;Timeout_Times<=0?(alert(tl("The connection is Overtime.")),top.location="/"):b&&b()}})).send(c)}}),BaceBoard=new Class({Extends:RPCCall,getCaps:function(a,b){var c=this.getRequest("faceBoard.getCaps");return sendRequest(c,
a,b)}}),IntervideoManager=new Class({Extends:RPCCall,instance:function(a,b){var c='{"method" : "IntervideoManager.factory.instance","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},getVersion:function(a,b,c,d){a=this.getRequest("IntervideoManager.getVersion",JSON.encode({Name:a}),d);sendRequest(a,b,c)}});function getConfigCaps(a,b){var c=(new RPCCall).getRequest("encode.getConfigCaps",'{"config" : '+a+"}");return sendRequest(c,b)}
function getTable(a){return JSON.decode(a).params.table}function getJsonReq(a){return'{"method":"configManager.getConfig","params":{"name":"'+a+'"},"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}"}function getPostJson(a,b){return'{"method":"configManager.setConfig","params":{"name":"'+a+'","table":'+JSON.encode(b)+',"options":""},"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}"}
function getJsonDef(a){return'{"method":"configManager.getDefault","params":{"name":"'+a+'"},"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}"}function getJsonPrd(a){return'{"method" : "magicBox.getProductDefinition","params" : {"name" : "'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}function getJsonPtz(){return'{"method":"ptz.getProtocolList","params":null,"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}"}
function getDevName(){return'{"method" : "devStorage.getAllNames","params" : null,"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}function getDevInfo(a){return'{"method" : "devStorage.getDeviceInfo","params" : {"pointer" : '+a+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}function doFormat(a,b){return'{"method" : "devStorage.formatPatition","params" : {"pointer" : '+a+',"part" : '+b+'},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}
function getAllPath(a){return'{"method" : "workDirectory.getAllPaths","params" : {"position" : "'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}function getGPath(a){return'{"method" : "storage.getGroupPaths","params":{"group":"'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}function getEMask(a){return'{"method" : "eventManager.getEventMask","params" : {"code" : "'+a+'"},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}"}
function getRecordPaths(a,b){var c=(new RPCCall).getRequest("workDirectory.getAllPaths",'{ "position" : "'+a+'"}');sendRequest(c,b)}function getFileSign(a,b,c,d,e,f){a=(new RPCCall).getRequest("mediaFileFind.findFile",'{ "condition" : '+('{ "Channel" :'+a+', "StartTime" : "'+b+' 00:00:00", "EndTime" : "'+b+' 23:59:59", "Dirs" : '+c+', "Types" : '+d+', "Events" : '+e+"}")+"}");sendRequest(a,f)}
function findFile(a,b,c){a!=-1&&(a=(new RPCCall).getRequest("mediaFileFind.findNextFiles",'{ "this" : "'+a+'", "count" :'+b+"}"),sendRequest(a,c))}function closeFindFile(a,b){var c=(new RPCCall).getRequest("mediaFileFind.close",'{ "this" : "'+a+'"}');sendRequest(c,b)}
var Nat=new Class({Extends:RPCCall,instance:function(a,b){var c=this.getRequest("Nat.factory.instance");sendRequest(c,a,b)},destroy:function(a,b,c){c=this.getRequest("Nat.destroy",null,c);sendRequest(c,a,b)},getTurnStatus:function(a,b){var c='{"method" : "Nat.getTurnStatus","params":{"channel" : 0},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(c,a,b)},createP2PChannel:function(a,b,c,d){a='{"method" : "Nat.createP2PChannel","params":{"channel" : 0,"Info":{ "MapIP":"'+a+'" , "MapPort" : '+
b+'}},"session":'+rpcCore.sessionID+',"id" : '+ID_REQUEST++ +"}";sendRequest(a,c,d)}}),VideoStatServer=new Class({Extends:RPCCall,instance:function(a,b,c){c==void 0&&(c=!0);a=this.getRequest("videoStatServer.factory.instance",'{"channel":'+a+"}");sendRequest(a,b,c)},destroy:function(a,b){a==void 0&&(a=!0);var c;c=b==void 0?this.getRequest("videoStatServer.destroy",'""'):this.getRequest("videoStatServer.destroy",'""',b);sendRequest(c,function(){},a)},clearSectionStat:function(a,b,c){c==void 0&&(c=
!0);b=this.getRequest("videoStatServer.clearSectionStat",'{"channel":'+b+"}");sendRequest(b,a,c)},startFind:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("videoStatServer.startFind",'{"channel":'+c+',"condition":'+a+"}");sendRequest(a,b,d)},doFind:function(a,b,c,d,e,f){f==void 0&&(f=!0);a=this.getRequest("videoStatServer.doFind",'{"channel":'+e+',"token":'+a+',"beginNumber":'+b+',"count":'+c+"}");sendRequest(a,d,f)},stopFind:function(a,b,c,d){d==void 0&&(d=!0);a=this.getRequest("videoStatServer.stopFind",
'{"channel":'+c+',"token":'+a+"}");sendRequest(a,b,d)}});
