(function(){(function(){var c=Page.abnormalConfig={Tab:[],init:function(){c.Tab.sdcard.init();c.Tab.netAbort.init();c.Tab.unauthAccess.init();c.translate();c.bind();c.render()},translate:function(){$("abnormal_sdcard").set("text",tl("w_sdCardError"));$("abnormal_netAbort").set("text",tl("w_networkError"));$("abnormal_unauthAccess").set("text",tl("w_unauthAccess"));$("abnormal_help").set("title",tl("w_help"))},render:function(){hasSDCard?$("abnormal_sdcard").style.display="":($("abnormal_netAbort").addClass("ui-tab-current"),
$("abnormal_sdcard").style.display="none");ALARM_OUT_NUMBER<1&&$$(".abnormal_showAlarmOut").setStyle("display","none");hasSDCard||$$(".abnormal_showRecode").setStyle("display","none");bool_4g||bool_get4GNet?$$(".abnormal_showMMS").setStyle("display",""):bool_get3GNet&&bool_3g?$$(".abnormal_showMMS").setStyle("display",""):$$(".abnormal_showMMS").setStyle("display","none");$$(".abnormal_tab_title.ui-tab-current").fireEvent("click")},bind:function(){$$(".abnormal_tab_title").addEvent("click",c._onTabTitleClick);
$("abnormal_help").addEvent("click",function(){openHelp("abnormalConfig.htm")})},_onTabTitleClick:function(){var b=this.getProperty("data-for");c.Tab[b].render();$$(".abnormal_tab_title").removeClass("ui-tab-current");$$(".abnormal_tab_con").setStyle("display","none");this.addClass("ui-tab-current");$("abnormal_tab_"+b).setStyle("display","block")},_showAlarmOut:function(b,a){var d="";if(ALARM_OUT_NUMBER>1){for(var e=0;e<ALARM_OUT_NUMBER;e++)d+='<a href="javascript:;" class="ui-channel-item abnormal_alarmOut"  id="abnormal_alarmOut_'+
a+"_"+e+'">'+(e+1)+"</a>";$("abnormal_alarmOutAdd"+a).innerHTML=d;$$(".ui-channel a[id^=abnormal_alarmOut_"+a+"]").addEvent("click",function(){var d=this.id.split("_");c._renderAlarmOut(d[3],d[2])});for(var d=b.AlarmOutChannels.length,e=b.AlarmOutChannels,g=0;g<d;g++)$("abnormal_alarmOut_"+a+"_"+e[g]).addClass("ui-channel-item-current")}},_renderAlarmOut:function(b,a){$("abnormal_alarmOut_"+a+"_"+b).toggleClass("ui-channel-item-current")},_saveChannels:function(b,a){var d=b.EventHandler;if(ALARM_OUT_NUMBER>
1){for(var e=0,c=[],f=0;f<ALARM_OUT_NUMBER;f++)$("abnormal_alarmOut_"+a+"_"+f).hasClass("ui-channel-item-current")&&(c[e]=f,e+=1);d.AlarmOutChannels=c}else d.AlarmOutChannels=[0];d.RecordChannels=[0];d.SnapshotChannels=[0];d.ExAlarmOutChannels=[0]}}})();(function(){var c="NotExist",b={},a=Page.abnormalConfig.Tab.sdcard={init:function(){a.configManager=new ConfigManager;a.translate();a.bind()},translate:function(){a._renderErrorType();$("SD_error_type_label").set("text",tl("w_Event Type"));$("SD_enable_label").set("text",
tl("w_StartUp"));$("SD_alarmout_enable_label").set("text",tl("w_Alarm Out"));$("SD_outdelay_label").set("text",tl("AlarmOutLatch"));$("SD_mail_enable_label").set("text",tl("w_Send E-Mail"));$("SD_outdelay_sec_label").set("text",tl("w_Second"));$("SD_lowerlimit_label").set("text",tl("w_Floor level of SD card's area"));$("SD_MMS_enable_label").set("text",tl("w_noteLink"));$("SDcard_default").set("text",tl("w_DefaultConfig"));$("SDcard_refresh").set("text",tl("w_Refresh"));$("SDcard_confirm").set("text",
tl("w_Confirm"))},bind:function(){$("SDcard_confirm").addEvent("click",a._onConfirmClick);$("SDcard_refresh").addEvent("click",a._onRefreshClick);$("SDcard_default").addEvent("click",a._onDefaultClick);attachLimit("SD_outdelay",10,300);attachLimit("SD_lowerlimit",0,99);$("SD_error_type").addEvent("change",function(){a._savaSDData();c=this.value;a._renderElements()})},render:function(){a.configManager.getConfig(["StorageNotExist","StorageLowSpace","StorageFailure"],function(d,b){a._getSDData(b);a._renderElements()})},
_renderErrorType:function(){var d=$("SD_error_type");d.empty();d.options.add(new Option(tl("w_No SD Card"),"NotExist"));d.options.add(new Option(tl("w_SD Card Error"),"Failure"));d.options.add(new Option(tl("w_Fall short of SD card's area"),"LowSpace"));d.value=c},_getSDData:function(d){b.NotExist=d.params[0].params.table;b.LowSpace=d.params[1].params.table;b.Failure=d.params[2].params.table},_savaSDData:function(){var d=b[c],a=d.EventHandler;d.Enable=$("SD_enable").checked;if(c==="LowSpace")d.LowerLimit=
+$("SD_lowerlimit").value;a.AlarmOutEnable=$("SD_alarmout_enable").checked;a.AlarmOutLatch=$("SD_outdelay").value-0;a.MailEnable=$("SD_mail_enable").checked;a.MMSEnable=$("SD_MMS_enable").checked;Page.abnormalConfig._saveChannels(d,0)},_renderElements:function(){var d=b[c],a=d.EventHandler;Page.abnormalConfig._showAlarmOut(a,0);$("SD_MMS_enable").checked=a.MMSEnable;$("SD_enable").checked=d.Enable;$("SD_alarmout_enable").checked=a.AlarmOutEnable;$("SD_outdelay").value=a.AlarmOutLatch;$("SD_mail_enable").checked=
a.MailEnable;c==="LowSpace"?($("SD_lowerlimit_wrap").setStyle("display","block"),$("SD_lowerlimit").value=d.LowerLimit):$("SD_lowerlimit_wrap").setStyle("display","none")},_onConfirmClick:function(){a._savaSDData();a.configManager.setConfig(["StorageNotExist","StorageLowSpace","StorageFailure"],[b.NotExist,b.LowSpace,b.Failure],function(a){checkPostResult(a)?remarkDisplay("SDcard_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("SDcard_remark",tl("Saving failure"),3E3,1)})},_onRefreshClick:function(){a.configManager.getConfig(["StorageNotExist",
"StorageLowSpace","StorageFailure"],function(d,b){checkPostResult(d)?(a._getSDData(b),a._renderElements(),remarkDisplay("SDcard_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("SDcard_remark",tl("Operateingfailure"),3E3,1)})},_onDefaultClick:function(){a.configManager.getDefault(["StorageNotExist","StorageLowSpace","StorageFailure"],function(d,b){checkPostResult(d)?(a._getSDData(b),a._renderElements(),remarkDisplay("SDcard_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("SDcard_remark",
tl("Operateingfailure"),3E3,1)})}}})();(function(){var c={},b="NetAbort",a=Page.abnormalConfig.Tab.netAbort={init:function(){a.configManager=new ConfigManager;a.translate();a.bind()},translate:function(){a._renderErrorType();$("netError_type_label").set("text",tl("w_Event Type"));$("netError_enable_label").set("text",tl("w_StartUp"));$("netError_record_enable_label").set("text",tl("w_Record"));$("netError_record_delay_label").set("text",tl("RecordLatch"));$("netError_alarmout_enable_label").set("text",
tl("w_Alarm Out"));$("netError_outdelay_label").set("text",tl("AlarmOutLatch"));$("netError_record_delay_sec_label").set("text",tl("w_Second"));$("netError_outdelay_sec_label").set("text",tl("w_Second"));$("netError_MMS_enable_label").set("text",tl("w_noteLink"));$("netError_default").set("text",tl("w_DefaultConfig"));$("netError_refresh").set("text",tl("w_Refresh"));$("netError_confirm").set("text",tl("w_Confirm"))},bind:function(){$("netError_confirm").addEvent("click",a._onConfirmClick);$("netError_refresh").addEvent("click",
a._onRefreshClick);$("netError_default").addEvent("click",a._onDefaultClick);attachLimit("netError_outdelay",10,300);attachLimit("netError_record_delay",10,300);$("netError_type").addEvent("change",function(){a._savaNetData();b=this.value;a._renderElements()})},render:function(){a.configManager.getConfig(["NetAbort","IPConflict"],function(d,b){a._getNetData(b);a._renderElements()})},_renderErrorType:function(){var a=$("netError_type");a.empty();a.options.add(new Option(tl("w_Network Disconnect"),
"NetAbort"));a.options.add(new Option(tl("w_IP Conflict"),"IPConflict"));a.value=b},_getNetData:function(a){c.NetAbort=a.params[0].params.table;c.IPConflict=a.params[1].params.table},_savaNetData:function(){var a=c[b],e=a.EventHandler;e.MMSEnable=$("netError_MMS_enable").checked;a.Enable=$("netError_enable").checked;e.AlarmOutEnable=$("netError_alarmout_enable").checked;e.RecordEnable=$("netError_record_enable").checked;e.RecordLatch=$("netError_record_delay").value-0;e.AlarmOutLatch=$("netError_outdelay").value-
0;Page.abnormalConfig._saveChannels(a,1)},_renderElements:function(){var a=c[b],e=a.EventHandler;Page.abnormalConfig._showAlarmOut(e,1);$("netError_MMS_enable").checked=e.MMSEnable;$("netError_enable").checked=a.Enable;$("netError_alarmout_enable").checked=e.AlarmOutEnable;$("netError_record_enable").checked=e.RecordEnable;$("netError_record_delay").value=e.RecordLatch;$("netError_outdelay").value=e.AlarmOutLatch},_onConfirmClick:function(){a._savaNetData();a.configManager.setConfig(["NetAbort","IPConflict"],
[c.NetAbort,c.IPConflict],function(a){checkPostResult(a)?remarkDisplay("netError_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("netError_remark",tl("Saving failure"),3E3,1)})},_onRefreshClick:function(){a.configManager.getConfig(["NetAbort","IPConflict"],function(b,c){checkPostResult(b)?(a._getNetData(c),a._renderElements(),remarkDisplay("netError_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("netError_remark",tl("Operateingfailure"),3E3,1)})},_onDefaultClick:function(){a.configManager.getDefault(["NetAbort",
"IPConflict"],function(b,c){checkPostResult(b)?(a._getNetData(c),a._renderElements(),remarkDisplay("netError_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("netError_remark",tl("Operateingfailure"),3E3,1)})}}})();(function(){var c=Page.abnormalConfig.Tab.unauthAccess={init:function(){c.configManager=new ConfigManager;c.translate();c.bind()},translate:function(){$("unauthAccess_enable_label").set("text",tl("w_StartUp"));$("unauthAccess_error_enable_label").set("text",tl("w_allowErrorTimeForLogin"));
$("unauthAccess_times").set("text",tl("w_times"));$("unauthAccess_alarmout_label").set("text",tl("w_Alarm Out"));$("unauthAccess_delay_label").set("text",tl("AlarmDelay"));$("unauthAccess_email_enable_label").set("text",tl("w_Send E-Mail"));$$(".unauthAccess_second").set("text",tl("w_Second"));$("unauthAccess_default").set("text",tl("w_DefaultConfig"));$("unauthAccess_refresh").set("text",tl("w_Refresh"));$("unauthAccess_confirm").set("text",tl("w_Confirm"))},bind:function(){$("unauthAccess_confirm").addEvent("click",
c._onConfirmClick);$("unauthAccess_refresh").addEvent("click",c._onRefreshClick);$("unauthAccess_default").addEvent("click",c._onDefaultClick);attachLimit("unauthAccess_delay",10,300);attachLimit("unauthAccess_error_input",3,10)},render:function(){c.configManager.getConfig(["General","LoginFailureAlarm"],function(b){c._getNoAccessData(b);c._renderElements(jsonGenral,jsonLogFailAlam)},!1)},_getNoAccessData:function(b){b=JSON.decode(b).params;jsonGenral=b[0].params.table;jsonLogFailAlam=b[1].params.table},
_renderElements:function(){var b=jsonLogFailAlam.EventHandler;Page.abnormalConfig._showAlarmOut(b,2);$("unauthAccess_enable").checked=jsonLogFailAlam.Enable;$("unauthAccess_error_input").value=jsonGenral.LockLoginTimes;$("unauthAccess_alarmout").checked=b.AlarmOutEnable;$("unauthAccess_delay").value=b.AlarmOutLatch;$("unauthAccess_email_enable").checked=b.MailEnable},_onConfirmClick:function(){var b=jsonLogFailAlam.EventHandler;jsonLogFailAlam.Enable=$("unauthAccess_enable").checked;jsonGenral.LockLoginTimes=
$("unauthAccess_error_input").value-0;b.AlarmOutEnable=$("unauthAccess_alarmout").checked;b.AlarmOutLatch=$("unauthAccess_delay").value-0;b.MailEnable=$("unauthAccess_email_enable").checked;Page.abnormalConfig._saveChannels(jsonLogFailAlam,2);c.configManager.setConfig(["General","LoginFailureAlarm"],[jsonGenral,jsonLogFailAlam],function(a){checkPostResult(a)?remarkDisplay("unauthAccess-remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("unauthAccess-remark",tl("Saving failure"),3E3,1)})},
_onRefreshClick:function(){c.configManager.getConfig(["General","LoginFailureAlarm"],function(b){checkPostResult(b)?(c._getNoAccessData(b),c._renderElements(jsonGenral,jsonLogFailAlam),remarkDisplay("unauthAccess-remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("unauthAccess-remark",tl("Operateingfailure"),3E3,1)},!1)},_onDefaultClick:function(){c.configManager.getDefault(["General","LoginFailureAlarm"],function(b){checkPostResult(b)?(c._getNoAccessData(b),c._renderElements(jsonGenral,jsonLogFailAlam),
remarkDisplay("unauthAccess-remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("unauthAccess-remark",tl("Operateingfailure"),3E3,1)},!1)}}})()})();
