var alarmEvent=[["VideoLoss"],["VideoMotion"],["StorageLowSpace"],["StorageFailure"],["VideoBlind"],["AlarmLocal"],["LoginFailure"],["AudioAnomaly","AudioMutation"],["CrossLineDetection","CrossRegionDetection","LeftDetection","VideoAbnormalDetection","TakenAwayDetection","FaceDetection","RioterDetection","MoveDetection","WanderDetection","CrossFenceDetection","ParkingDetection","NumberStat"]],sidNo=[];
function setAlarmConfig(a){var b=new ConfigManager;jsonAlarmConfig.AlarmEvent=[];$$('#alarmTypelist input[id ^= "alarmType_"]').each(function(a){a.checked&&(a=a.id.substring(10),jsonAlarmConfig.AlarmEvent.push(a))});jsonAlarmConfig.AlarmTip=$("workType_3").checked;jsonAlarmConfig.AlarmSound.Enable=$("c_sound").checked;if(a)jsonAlarmConfig.AlarmSound.Path=a;else if($("i_chosepth").value=="")jsonAlarmConfig.AlarmSound.Path="";b.setConfig("AlarmConfig",jsonAlarmConfig,function(){})}
function chkAlarmType(a){$("alarmType_"+a).checked?attAlarmEvent(a):DetAlarmEvent(a);setAlarmConfig()}
function chkAlarmSound(){if($("c_sound").checked)$("i_chosepth").disabled=!1,$("b_almpth").disabled=!1,$("b_almpth").removeClass("ui-button-disabled");else{$("i_chosepth").disabled=!0;$("b_almpth").disabled=!0;$("b_almpth").addClass("ui-button-disabled");$("i_chosepth").value="";var a='{"method":"getvideopath","params":{"videopath":"'+("c://notexistfile"+$time()+".mp3")+'"},"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}";sendRequest(a,$empty)}}
function attAlarmEvent(a){(new EventManager).attachEvent(alarmEvent[a],function(b){sidNo[a]=JSON.decode(b).params.SID},!1)}function DetAlarmEvent(a){(new EventManager).detachEvent(sidNo[a],alarmEvent[a],chkDownAlarmEvent,!1)}function chkDownAlarmEvent(){}
function getPath(){var a="";if($("c_sound").checked&&$("ocx")){a=Browser.ie?"*.mp3;*.wav;*.mav;*.avi;*.wma;*.wmv":Browser.Platform.mac?"*.mp3;*.wav;":"*.wav";try{$("ocx").SetFilter("Music Files ("+a+")|"+a+"|All Files|*.*||"),$("ocx").ShowOpen()}catch(b){}}}
function getMusicPath(a,b){var c=b.replace(/\\/g,"/");$("i_chosepth").value=c;jsonReq='{"method":"getvideopath","params":{"videopath":"'+c+'"},"session":'+rpcCore.sessionID+',"id":'+ID_REQUEST++ +"}";sendRequest(jsonReq,$empty);setAlarmConfig(c)}function playAlarmSound(a){if(a&&(clearTimeout(playAlarmSound.timer),playAlarmSound.timer=null,$("ocx")))$("ocx").OpenAudioFile(a),playAlarmSound.timer=setTimeout(function(){$("ocx").OpenAudioFile("NULL")},7E3)}
var AlarmCGI=new Class({initialize:function(a){this.timer=null;this.iframe=a},open:function(){this.iframe.src="/cgi-bin/eventManager.cgi?action=notifyEventStream&sessionId="+rpcCore.sessionID;this.keepalive()},close:function(){this.iframe.src="";$clear(this.timer)},keepalive:function(){$clear(this.timer);this.timer=this._loseConnection.delay(6E4,this)},_loseConnection:function(){$("alarm_frame").src!==""&&(this.close(),this.open())}}),alarmCGI=new AlarmCGI($("alarm_frame"));
function alarmCGIKeepAlive(){alarmCGI.keepalive()};
