(function(){var a,c,b=Page.autoMaintainConfig={init:function(){b.configManager=new ConfigManager;b.translate();b.render();b.bind()},translate:function(){$("autoMaintain_autoMaintainTitle").set("text",tl("AutoMaintain"));$("autoMaintain_autoRebootLabel").set("text",tl("w_Auto Reboot"));$("autoMaintain_autoFileHoldLabel").set("text",tl("w_Auto Delete File"));$("autoMaintain_customized").set("text",tl("w_Customize"));$("autoMaintain_autoFileHoldDaysSpan").set("text",tl("w_Days ago"));$("autoMaintain_refresh").set("text",
tl("w_Refresh"));$("autoMaintain_save").set("text",tl("w_Confirm"));$("autoMaintain_everyday").set("text",tl("w_everyday"));$("autoMaintain_Sunday").set("text",tl("w_Sunday"));$("autoMaintain_Monday").set("text",tl("w_Monday"));$("autoMaintain_Tuesday").set("text",tl("w_Tuesday"));$("autoMaintain_Wednesday").set("text",tl("w_Wednesday"));$("autoMaintain_Thursday").set("text",tl("w_Thursday"));$("autoMaintain_Friday").set("text",tl("w_Friday"));$("autoMaintain_Saturday").set("text",tl("w_Saturday"));
$("autoMaintain_RpcReboot").set("text",tl("w_Reboot"));$("autoMaintain_rebootRPC").set("text",tl("w_rebootconfirm"));$("autoMaintain_rebootConfirm").set("text",tl("w_Confirm"));$("autoMaintain_rebootCancel").set("text",tl("Cancel"));$("autoMaintain_help").set("title",tl("w_help"))},render:function(){if(!checkAuthority("ShutDown"))$("autoMaintain_RpcReboot").style.display="none";b.configManager.getConfig(["AutoMaintain","StorageGlobal"],function(d){d=JSON.decode(d).params;a=d[0].params.table;c=d[1].params.table;
b._renderElements()},!1);b._rebootDialogClose()},bind:function(){$("autoMaintain_help").addEvent("click",b._openHelp);$("autoMaintain_autoRebootEnable").addEvent("click",function(){$("autoMaintain_autoRebootEnable").checked?($$("#autoMaintain_daysSelect","#autoMaintain_autoRebootHour","#autoMaintain_autoRebootTime","#autoMaintain_autoRebootMinute").setStyle("display",""),a.AutoRebootDay==7?$("autoMaintain_daysSelect").selectedIndex=0:$("autoMaintain_daysSelect").selectedIndex=a.AutoRebootDay+1):$$("#autoMaintain_daysSelect",
"#autoMaintain_autoRebootHour","#autoMaintain_autoRebootTime","#autoMaintain_autoRebootMinute").setStyle("display","none")});$("autoMaintain_autoFileHoldEnable").addEvent("click",function(){if($("autoMaintain_autoFileHoldEnable").checked){if($$("#autoMaintain_customizedSelect","#autoMaintain_autoFileHoldDays","#autoMaintain_autoFileHoldDaysSpan").setStyle("display",""),$("autoMaintain_autoFileHoldDays").value=="")$("autoMaintain_autoFileHoldDays").value=1}else $$("#autoMaintain_customizedSelect",
"#autoMaintain_autoFileHoldDays","#autoMaintain_autoFileHoldDaysSpan").setStyle("display","none")});$("autoMaintain_RpcReboot").addEvent("click",function(){isNeedReboot('{"result":true,"params":{"options":["NeedReboot"]}}',"w_rebootconfirm",!0,!0)});$("autoMaintain_refresh").addEvent("click",b._onRefreshClick);$("autoMaintain_save").addEvent("click",b._onSaveClick);attachLimit("autoMaintain_autoFileHoldDays",1,31);b._attachLimitTime(["autoMaintain_autoRebootHour","autoMaintain_autoRebootMinute"])},
_openHelp:function(){openHelp("autoMaintainConfig.htm")},_rebootDialogClose:function(){Site.currentPage.is.autoMaintainConfig?setTimeout(b._rebootDialogClose,100):spe_rebootDialog&&spe_rebootDialog.close()},_renderElements:function(){a.AutoRebootEnable==!1?($("autoMaintain_autoRebootEnable").checked=!1,$$("#autoMaintain_daysSelect","#autoMaintain_autoRebootHour","#autoMaintain_autoRebootTime","#autoMaintain_autoRebootMinute").setStyle("display","none")):($("autoMaintain_autoRebootEnable").checked=
!0,$$("#autoMaintain_daysSelect","#autoMaintain_autoRebootHour","#autoMaintain_autoRebootTime","#autoMaintain_autoRebootMinute").setStyle("display",""),a.AutoRebootDay==7?$("autoMaintain_daysSelect").selectedIndex=0:$("autoMaintain_daysSelect").selectedIndex=a.AutoRebootDay+1);$("autoMaintain_autoRebootHour").value=a.AutoRebootHour<10?"0"+a.AutoRebootHour:a.AutoRebootHour;$("autoMaintain_autoRebootMinute").value=a.AutoRebootMinute<10?"0"+a.AutoRebootMinute:a.AutoRebootMinute;c.FileHoldTime==0?($("autoMaintain_autoFileHoldEnable").checked=
!1,$$("#autoMaintain_customizedSelect","#autoMaintain_autoFileHoldDays","#autoMaintain_autoFileHoldDaysSpan").setStyle("display","none")):($("autoMaintain_autoFileHoldEnable").checked=!0,$("autoMaintain_customizedSelect").selectedIndex=0,$$("#autoMaintain_customizedSelect","#autoMaintain_autoFileHoldDays","#autoMaintain_autoFileHoldDaysSpan").setStyle("display",""),$("autoMaintain_autoFileHoldDays").value=c.FileHoldTime)},_onRefreshClick:function(){b.configManager.getConfig(["AutoMaintain","StorageGlobal"],
function(d){var e=JSON.decode(d).params;a=e[0].params.table;c=e[1].params.table;JSON.decode(d).result?(b._renderElements(),remarkDisplay("autoMaintain_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("autoMaintain_remark",tl("Operateingfailure"),3E3,1)},!1)},_onSaveClick:function(){b._saveElements();b.configManager.setConfig(["AutoMaintain","StorageGlobal"],[a,c],function(a){checkPostResult(a)?remarkDisplay("autoMaintain_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("autoMaintain_remark",
tl("Saving failure"),3E3,1)})},_saveElements:function(){$("autoMaintain_autoRebootEnable").checked==!1?a.AutoRebootEnable=!1:(a.AutoRebootEnable=!0,a.AutoRebootDay=$("autoMaintain_daysSelect").selectedIndex==0?7:$("autoMaintain_daysSelect").selectedIndex-1);a.AutoRebootHour=$("autoMaintain_autoRebootHour").value-0;a.AutoRebootMinute=$("autoMaintain_autoRebootMinute").value-0;c.FileHoldTime=$("autoMaintain_autoFileHoldEnable").checked==!1?0:$("autoMaintain_autoFileHoldDays").value-0},_attachLimitTime:function(a){var b=
[],b=[$(a[0]),$(a[1])],a=function(a,d,c){b[a]&&b[a].addEvents({keyup:function(c){c=c.keyCode;limitEx(this,d);c==110||c==190||c==39?a<1&&b[a+1].select():c!=9&&(c==37?a==1&&b[a-1].select():this.value.length>=2&&a<1&&b[a+1].select())},blur:function(){limit(this,d);limitMin(this,c);if(this.value==""||this.value==0)this.value="00";else if(+this.value<10)this.value="0"+this.value},focus:function(){this.select()}})};a(0,23,0);a(1,59,0)}}})();
