(function(){var c=[["VideoColor","VideoWaterMark","VideoWidget","ChannelTitle","VideoEncodeROI","VideoInPreviewOptions","VideoInWhiteBalance","VideoInExposure","VideoInDenoise","VideoInDayNight","VideoInFocus","VideoInZoom","VideoInSharpness","VideoInColor","VideoInRotate","VideoInMode","VideoInDefog","FishEye","VideoWidgetNumberStat","ThermographyOptions"],["NetAbort","PPPoE","DDNS","AlarmServer","NTP","Email","WLan","Wireless","SIP","UPnP","Mobile","SNMP","Bonjour","ARP&Ping","Qos","VideoAnalyseRule",
"VideoAnalyseGlobal","VideoAnalyseModule","VideoOut"],["MotionDetect","BlindDetect","UnFocusDetect","AudioDetect","LossDetect","Alarm","NetAlarm","ExAlarm","AlarmOut","ExAlarmOut","ExRemoteCtrl","IPConflict","NetAbort","StorageNotExist","StorageFailure","StorageLowSpace","FlashLight","LoginFailureAlarm"],["Record","Snap","RecordMode","SnapMode","RecordStoragePoint","NAS","MediaGlobal","Holiday"],["StorageGlobal","StorageGroup","Comm","Ptz","PtzPreset","PtzTour","AutoMaintain","ATM","ATMSniffer","Locales",
"Lighting"],["IntelliTrackScene","VideoAnalyseCalibrate","TrafficGlobal","TrafficSnapMosaic","OSD","TrafficSnapshot","SceneSnapShotWithRule","WideViewControl"],["VideoInOptions","Encode"]],b=Page.backupConfig={init:function(){b.configManager=new ConfigManager;b.translate();b.render();b.bind()},translate:function(){$("backup_configImportOut").set("text",tl("w_Collocate I/O"));$("backup_backupPath").set("text",tl("w_BACKUP Path"));$("backup_configImport").set("text",tl("w_Import Config"));$("backup_configExport").set("text",
tl("w_Export Config"));$("backup_help").set("title",tl("w_help"))},render:function(){$("backup_configImport").set("data","defalut");$("backup_configExport").set("data","defalut");b.configManager.getConfig("VideoInOptions",function(a){JSON.decode(a).result&&(a=JSON.decode(a),c[6]=a.params.table[0].Rotate90!=0?["VideoInOptions","Encode"]:["Encode","VideoInOptions"])},!1)},bind:function(){$("backup_configImport").addEvent("click",b._importConfig);$("backup_configExport").addEvent("click",b._exportConfig);
$("backup_help").addEvent("click",b._openHelp)},_openHelp:function(){openHelp("backupConfig.htm")},_importConfig:function(){$("ocx")&&($("backup_configImport").set("data","current"),$("backup_configExport").set("data","defalut"),$("ocx").SetFilter("Config Files (*.backup)|*.backup||"),$("ocx").ShowOpen())},_setImportConfig:function(a){for(var g=0,f=[],d=c.length,e=0;e<c.length-1;e++)f.combine(c[e]);var j=f.length,h=j;remarkDisplay("backup_remark",tl("w_waiting"),0,2);try{$("backup_path").setProperty("text",
a);var k="";$("ocx")&&(k=$("ocx").ReadFile(a));for(var i=JSON.decode(k),a=0;a<c[d-1].length;a++)b.configManager.setConfig(c[d-1][a],i[c[d-1][a]],function(){},!1);for(e=0;e<j;e++)i[f[e]]?b.configManager.setConfig(f[e],i[f[e]],function(a){g++;g==h&&(JSON.decode(a).result?remarkDisplay("backup_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("backup_remark",tl("Saving failure"),3E3,1))}):h--;h==0&&remarkDisplay("backup_remark",tl("No items which can be imported."),3E3,2)}catch(l){remarkDisplay("backup_remark",
tl("Bad FileFormat!"),3E3,2)}},_exportConfig:function(){$("ocx")&&($("backup_configExport").set("data","current"),$("backup_configImport").set("data","defalut"),$("ocx").SetFilename("DeviceConfig.backup"),$("ocx").SetFilter("Config Files (*.backup)|*.backup||"),$("ocx").ShowSave())},_setExportConfig:function(a,g){try{for(var f=[],d=0;d<c.length;d++)f.combine(c[d]);/[\\\/\:\*\?\"\<\>\|]/g.test(a)?alert(tl("File Name Invalid!")):($("backup_path").setProperty("text",g),remarkDisplay("backup_remark",
tl("w_waiting"),0,2),b.configManager.getConfig(f,function(a){for(var a=JSON.decode(a).params,b="{",e="",c=f.length,d=0;d<c;d++)a[d].result&&(e=JSON.encode(a[d].params.table))&&(b+='"'+f[d]+'":'+e+",");a=b.slice(0,b.length-1);a+="}\000";$("ocx")&&($("ocx").WriteFile(g,a,"w+")===-1?remarkDisplay("backup_remark",tl("w_No Write Right"),3E3,1):remarkDisplay("backup_remark",tl("Operateingsuccess"),3E3,0))}))}catch(e){remarkDisplay("backup_remark",tl("Operateingfailure"),3E3,1)}},_setConfigPath:function(a,
c){$("backup_configImport").getProperty("data")=="current"?(b._setImportConfig(c),$("backup_configImport").set("data","default")):(b._setExportConfig(a,c),$("backup_configExport").set("data","default"))}}})();
