(function(){var b="",g="",f,e=1,h=!1,c=Page.broadcastConfig={init:function(){c._showExtraStream();c.configManager=new ConfigManager;c.translate();c.render();c.bind()},translate:function(){$("broadcast").set("text",tl("w_Multicast"));$("broadcast_help").set("title",tl("w_help"));$("broadcast_main_stream_lable").set("text",tl("w_MainStream"));$("broadcast_main_stream_enable_lable").set("text",tl("Enable"));$("broadcast_main_port_label").set("text",tl("w_Port"));$("broadcast_main_mcast_addr_lable").set("text",
tl("w_Multicast Address"));$("broadcast_extra_stream_lable").set("text",tl("w_SecondStream"));$("broadcast_extra_stream_enable_lable").set("text",tl("Enable"));$("broadcast_extra_port_label").set("text",tl("w_Port"));$("broadcast_extra_mcast_addr_lable").set("text",tl("w_Multicast Address"));$("broadcast_default").set("text",tl("w_DefaultConfig"));$("broadcast_refresh").set("text",tl("w_Refresh"));$("broadcast_confirm").set("text",tl("w_Confirm"))},render:function(){c.configManager.getConfig(["Multicast",
"DVRIP"],function(a){b=JSON.decode(a).params[0].params.table;g=$unlink(b);e=1;c._renderElements(b,e);f=JSON.decode(a).params[1].params.table});ExtraStreamNum<1?$("broadcast_extra_stream").style.display="none":$("broadcast_extra_stream").style.display=""},bind:function(){$("broadcast_default").addEvent("click",c._onDefaultClick);$("broadcast_refresh").addEvent("click",c._onRefreshClick);$("broadcast_confirm").addEvent("click",c._onConfirmClick);$("broadcast_help").addEvent("click",function(){openHelp("broadcastConfig.htm")});
attachIpInput("broadcast_main_mcast_addr");attachLimit("broadcast_main_mcast_addr0",224,239);attachLimit("broadcast_main_port",1025,65529);attachIpInput("broadcast_extra_mcast_addr");attachLimit("broadcast_extra_mcast_addr0",224,239);attachLimit("broadcast_extra_port",1025,65529);$("broadcast_main_mcast_addr0").addEvents({keyup:function(a){a=a.code;a==110||a==190||a==39?$("broadcast_main_mcast_addr1").select():a!=9&&(a==37?$("broadcast_main_mcast_addr3").select():this.value.length>=3&&$("broadcast_main_mcast_addr1").select())}});
$("broadcast_extra_mcast_addr0").addEvents({keyup:function(a){a=a.code;a==110||a==190||a==39?$("broadcast_extra_mcast_addr1").select():a!=9&&(a==37?$("broadcast_extra_mcast_addr3").select():this.value.length>=3&&$("broadcast_extra_mcast_addr1").select())}});$("broadcast_extraStreams").addEvent("change",c._onChangeextraStreams)},_showExtraStream:function(){$("broadcast_extraStreams").empty();if(ExtraStreamNum<2)$("broadcast_extraStreams").style.display="none";else{$("broadcast_extraStreams").style.display=
"";for(var a=0;a<ExtraStreamNum;a++)$("broadcast_extraStreams").options.add(new Option(tl("w_SecondStream"+(a+1)),a))}},_onChangeextraStreams:function(){c._saveTempJson();e=$("broadcast_extraStreams").selectedIndex+1;c._renderExtraElements(b,e)},_saveTempJson:function(){var a=[0,1,2,3].map(function(a){return $("broadcast_extra_mcast_addr"+a).value}).join("."),d=$("broadcast_extra_port").value-0;b.RTP[e].MulticastAddr=a;b.RTP[e].Port=d;b.RTP[e].Enable=$("broadcast_extra_stream_enable").checked},_renderElements:function(a,
b){$("broadcast_main_port").value=a.RTP[0].Port;$("broadcast_main_stream_enable").checked=a.RTP[0].Enable;a.RTP[0].MulticastAddr.split(".").each(function(a,b){$("broadcast_main_mcast_addr"+b).value=a});c._renderExtraElements(a,b)},_renderExtraElements:function(a,b){if(ExtraStreamNum>1)$("broadcast_extraStreams").selectedIndex=b-1;$("broadcast_extra_port").value=a.RTP[b].Port;$("broadcast_extra_stream_enable").checked=a.RTP[b].Enable;a.RTP[b].MulticastAddr.split(".").each(function(a,b){$("broadcast_extra_mcast_addr"+
b).value=a})},_onDefaultClick:function(){c.configManager.getDefault("Multicast",function(a){JSON.decode(a).result?(b=getTable(a),c._renderElements(b,e),remarkDisplay("broadcast_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("broadcast_remark",tl("Defaultfailure"),3E3,1)},!1)},_onRefreshClick:function(){c.configManager.getConfig("Multicast",function(a){JSON.decode(a).result?(b=getTable(a),c._renderElements(b,e),remarkDisplay("broadcast_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("broadcast_remark",
tl("Operateingfailure"),3E3,1)},!1)},_onConfirmClick:function(){var a=[0,1,2,3].map(function(a){return $("broadcast_main_mcast_addr"+a).value}).join("."),d=$("broadcast_main_port").value-0;b.RTP[0].MulticastAddr=a;f.MCASTAddress=a;b.RTP[0].Port=d;f.MCASTPort=d;b.RTP[0].Enable=$("broadcast_main_stream_enable").checked;c._saveTempJson();c._checkConfig()&&c.configManager.setConfig(["Multicast","DVRIP"],[b,f],c._bindConfirmCallback)},_checkConfig:function(){h=!1;if(b.RTP[0].Port==f.TCPPort||b.RTP[0].Port==
f.UDPPort)return remarkDisplay("broadcast_remark",tl("w_Main port in use Saving failure"),3E3,1),!1;if(b.RTP[e].Port==f.TCPPort||b.RTP[e].Port==f.UDPPort)return remarkDisplay("broadcast_remark",tl("w_Extra port in use Saving failure"),3E3,1),!1;var a=b.RTP.length;if(!chkPort(b.RTP[0].Port))return remarkDisplay("broadcast_remark",tl("w_Main port in use Saving failure"),3E3,1),!1;for(var d=1;d<a;d++)if(!chkPort(b.RTP[d].Port))return remarkDisplay("broadcast_remark",tl("w_Extra port in use Saving failure"),
3E3,1),!1;for(d=0;d<a;d++)if(g.RTP[d].MulticastAddr!=b.RTP[d].MulticastAddr||g.RTP[d].Port!=b.RTP[d].Port)h=!0;for(d=0;d<a;d++)for(var c=d;c<a;c++)if(d!=c&&b.RTP[d].Enable&&b.RTP[c].Enable&&b.RTP[d].MulticastAddr==b.RTP[c].MulticastAddr&&b.RTP[d].Port==b.RTP[c].Port)return remarkDisplay("broadcast_remark",tl("w_Multicast port conflict"),3E3,1),!1;return!0},_bindConfirmCallback:function(a){JSON.decode(a).result?(remarkDisplay("broadcast_remark",tl("Succeed in saving configure"),3E3,0),h&&setTimeout(function(){doLogout(!0);
window.removeEvents("unload").removeEvents("beforeunload");window.location=window.location},3E3)):remarkDisplay("broadcast_remark",tl("Saving failure"),3E3,1)}}})();
