(function(){var c=Page.connetConfig={Tab:[],init:function(){c.Tab.connect.init();c.Tab.onvif.init();c.translate();c.bind();c.render()},translate:function(){$("connect_help").set("title",tl("w_help"))},render:function(){$("ONVIF").setStyle("display",bool_GB28181?"none":"block");$$(".connect_tab_title.ui-tab-current").fireEvent("click")},bind:function(){$$(".connect_tab_title").addEvent("click",c._onTabTitleClick);$("connect_help").addEvent("click",function(){openHelp("connetConfig.htm")})},_onTabTitleClick:function(){var f=
this.getProperty("data-for");$$(".connect_tab_title").removeClass("ui-tab-current");$$(".connect_tab_con").setStyle("display","none");this.addClass("ui-tab-current");$("connect_tab_"+f).setStyle("display","block");c.Tab[f].render()}}})();
(function(){var c,f,h,g,e,d=Page.connetConfig.Tab.connect={init:function(){d.configManager=new ConfigManager;d.translate();d.bind()},translate:function(){$("connect").set("text",tl("w_Connect Settings"));$("connect_help").set("title",tl("w_help"));$("connect_max_connections_label").set("text",tl("w_Max Connect"));$("connect_tcp_port_label").set("text",tl("w_TCP Port"));$("connect_udp_port_label").set("text",tl("w_UDP Port"));$("connect_http_port_label").set("text",tl("w_HTTP Port"));$("connect_https_enable_label").set("text",
tl("w_HTTPs On"));$("connect_https_port_label").set("text",tl("w_HTTPs Port"));$("connect_rtsp_port_label").set("text",tl("w_RTSP Port"));$("connect_default").set("text",tl("w_DefaultConfig"));$("connect_refresh").set("text",tl("w_Refresh"));$("connect_confirm").set("text",tl("w_Confirm"))},render:function(){d.configManager.getConfig(["DVRIP","Web","RTSP","Https","Multicast"],function(a){d._getData(a);d._renderElements(c,f,h,g,e)});if(window.location.protocol.toLowerCase()=="https:")$("connect_https_enable").disabled=
"disabled"},bind:function(){$("connect_default").addEvent("click",d._onDefaultClick);$("connect_refresh").addEvent("click",d._onRefreshClick);$("connect_confirm").addEvent("click",d._onConfirmClick);$("connect_help").addEvent("click",function(){openHelp("connetConfig.htm")});attachLimit("connect_max_connections",1,20);$("connect_max_connections").addEvent("keyup",function(){this.value-=0});attachPortLimit("connect_tcp_port","connect_remark",37777,65534,1025);attachPortLimit("connect_udp_port","connect_remark",
37778,65534,1025);attachPortLimit("connect_http_port","connect_remark",80,65534);attachPortLimit("connect_https_port","connect_remark",443,65534);attachPortLimit("connect_rtsp_port","connect_remark",554,65534)},_getData:function(a){a=JSON.decode(a).params;c=a[0].params.table;f=a[1].params.table;h=a[2].params.table;g=a[3].params.table;e=a[4].params.table},_renderElements:function(a,b,d,c){$("connect_max_connections").value=a.MaxConnections;$("connect_tcp_port").value=a.TCPPort;$("connect_udp_port").value=
a.UDPPort;$("connect_http_port").value=b.Port;$("connect_rtsp_port").value=d.Port;$("connect_https_port").value=c.Port;$("connect_https_enable").checked=c.Enable},_onDefaultClick:function(){d.configManager.getDefault(["DVRIP","Web","RTSP","Https"],function(a){var b,c,e;checkPostResult(a)?(b=JSON.decode(a).params,a=b[0].params.table,c=b[1].params.table,e=b[2].params.table,b=b[3].params.table,d._renderElements(a,c,e,b),remarkDisplay("connect_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("connect_remark",
tl("Defaultfailure"),3E3,1)})},_onRefreshClick:function(){d.configManager.getConfig(["DVRIP","Web","RTSP","Https","Multicast"],function(a){checkPostResult(a)?(d._getData(a),d._renderElements(c,f,h,g),remarkDisplay("connect_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("connect_remark",tl("Operateingfailure"),3E3,1)})},_onConfirmClick:function(){var a=[],b=$("connect_tcp_port").value-0,i=$("connect_udp_port").value-0,j=$("connect_http_port").value-0,k=$("connect_rtsp_port").value-0,l=$("connect_https_port").value-
0,m=c.MCASTPort;b==e.RTP[0].Port||i==e.RTP[0].Port||b==e.RTP[1].Port||i==e.RTP[1].Port?remarkDisplay("connect_remark",tl("Tip.Port in use Saving failure"),3E3,1):(a.include(b).include(i).include(j).include(k).include(l).include(m),a.length!==6?remarkDisplay("connect_remark",tl("w_sameport"),3E3,1):chkPort(b,37777)&&chkPort(i,37778)&&chkPort(j,80)&&chkPort(k,554)&&i!=b-1&&j!=b-1&&k!=b-1?(c.MaxConnections=$("connect_max_connections").value-0,g.Enable=$("connect_https_enable").checked,c.TCPPort=b,c.UDPPort=
i,f.Port=j,g.Port=l,h.Port=k,d.configManager.setConfig(["DVRIP","Web","RTSP","Https"],[c,f,h,g],function(a){checkPostResult(a)?(remarkDisplay("connect_remark",tl("Succeed in saving configure"),3E3,0),isNeedReboot(a,"The configration take effect! The device is restarting now,please reconnect later...",!1,!1)):remarkDisplay("connect_remark",tl("Port in use Saving failure"),3E3,1)})):remarkDisplay("connect_remark",tl("Port in use Saving failure"),3E3,1))}}})();
(function(){function c(a){$("onvif_login_check_on").checked=a.OnvifLoginCheck;$("onvif_login_check_off").checked=!a.OnvifLoginCheck}function f(){e.OnvifLoginCheck=$("onvif_login_check_on").checked;d.configManager.setConfig("UserGlobal",e,function(a,b){b.result?remarkDisplay("onvif_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("onvif_remark",tl("Saving failure"),3E3,1)})}function h(){d.configManager.getConfig("UserGlobal",function(a,b){b.result?(c(b.params.table||{}),remarkDisplay("onvif_remark",
tl("Operateingsuccess"),3E3,0)):remarkDisplay("onvif_remark",tl("Operateingfailure"),3E3,1)})}function g(){d.configManager.getDefault("UserGlobal",function(a,b){b.result?(c(b.params.table||{}),remarkDisplay("onvif_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("onvif_remark",tl("Defaultfailure"),3E3,1)})}var e={},d=Page.connetConfig.Tab.onvif={init:function(){d.configManager=new ConfigManager;d.translate();d.bind()},translate:function(){$("onvif_login_check_label").set("text",tl("w_LoginCheck"));
$("onvif_login_check_on_label").set("text",tl("C_On"));$("onvif_login_check_off_label").set("text",tl("C_Off"));$("onvif_version_label").set("text",tl("w_Edition Info"));$("onvif_confirm").set("text",tl("w_Confirm"));$("onvif_refresh").set("text",tl("w_Refresh"));$("onvif_default").set("text",tl("w_DefaultConfig"))},bind:function(){$("onvif_confirm").addEvent("click",f);$("onvif_refresh").addEvent("click",h);$("onvif_default").addEvent("click",g)},render:function(){d.configManager.getConfig("UserGlobal",
function(a,b){b.result&&(e=b.params.table||{},c(e))})}}})();
