(function(){var d,e=0,j="",i=60,g,a=Page.DDNSConfig={init:function(){a.configManager=new ConfigManager;a.ddnsClient=new DDNSClient;a.dialog=new Dialog("ddns_connectDDNS",function(){},"","",tl("w_connectDDNS"));a.dialog.setPosition(300,200);a.translate();a.render();a.bind();a._render=a.render},translate:function(){$("ddns_title").set("text",tl("w_DDNS Settings"));$("ddns_help").set("title",tl("w_help"));$("ddns_protocol_label").set("text",tl("w_Server Type"));$("ddns_address_label").set("text",tl("w_Server Address"));
$("ddns_port_label").set("text",tl("w_Server Port"));$("ddns_mode_label").set("text",tl("w_Mode"));$("ddns_mode_auto_label").set("text",tl("w_Auto"));$("ddns_mode_manual_label").set("text",tl("w_Manual"));$("ddns_hostname_label").set("text",tl("w_DomainName"));$("ddns_username_label").set("text",tl("w_Username"));$("ddns_password_label").set("text",tl("w_password"));$("ddns_keepalive_label").set("text",tl("w_KeepAlive"));$("ddns_keepalive_unit").set("text",tl("w_Minute"));$("ddns_username_tip").set("text",
tl("w_UsernameTip"));$("ddns_default").set("text",tl("w_DefaultConfig"));$("ddns_refresh").set("text",tl("w_Refresh"));$("ddns_confirm").set("text",tl("w_Confirm"));$("ddns_test").set("text",tl("w_test"));$("ddns_macAddress_label").set("text",tl("w_Mac Address"));$("ddns_internetStatus_label").set("text",tl("w_linkState"));$("ddns_title1").set("text",tl("w_Notes:"));$("ddns_title2").set("text",tl("w_1.To add the domain name"));$("ddns_title3").set("text",tl("w_- Check Enable"));$("ddns_title4").set("text",
tl("w_- Input the domain name and press Save button"));$("ddns_title5").set("text",tl("w_2.To remove the domain name"));$("ddns_title6").set("text",tl("w_- Uncheck Enable and press Save button"));$("ddns_title7").set("text",tl("w_3.Domain name field accepts only alpha unmeric characters(a-z\u30010-9)are valid"));$("ddns_title8").set("text",tl("w_4.Use"));$("ddns_title10").set("text",tl("w_URL to access your IP Camera"));$("ddns_connectDDNSTitle").set("text",tl("w_DDNSconnectting"))},render:function(){a.configManager.getConfig("DDNS",
function(b){d=getTable(b);a._setProtocolOptions();a._renderElements()})},_render:null,bind:function(){$("ddns_enable").addEvent("click",a._onEnableClick);$("ddns_protocol").addEvent("change",a._onProtocolChange);$("ddns_mode_auto").addEvent("click",a._onModeAutoClick);$("ddns_mode_manual").addEvent("click",a._onModeManualClick);$("ddns_test").addEvent("click",a._onTestClick);$("ddns_default").addEvent("click",a._onDefaultClick);$("ddns_refresh").addEvent("click",a._onRefreshClick);$("ddns_confirm").addEvent("click",
a._onConfirmClick);$("ddns_hostname").addEvent("keyup",a._onHostnameKeyup);$("ddns_password").addEvents({keyup:function(){promptImportLimt("ddns_password","ddns_password_tip","w_noInputMarks",3)},blur:function(){promptImportLimt("ddns_password","ddns_password_tip","w_noInputMarks",3)}});$("ddns_username").addEvents({keyup:function(){promptImportLimt("ddns_username","ddns_username_tipred","w_noInputMarks",3)},blur:function(){promptImportLimt("ddns_username","ddns_username_tipred","w_noInputMarks",
3)}});$("ddns_address").addEvents({keyup:function(){promptImportLimt("ddns_address","ddns_address_tip","w_wrongServerName",1)},blur:function(){promptImportLimt("ddns_address","ddns_address_tip","w_wrongServerName",1)}});attachLimit("ddns_keepalive",1,500);attachLimit("ddns_port",1,65535);$("ddns_help").addEvent("click",function(){openHelp("DDNSConfig.htm")})},_hostnamePasteDeal:function(){},_setProtocolOptions:function(){var a=$("ddns_protocol");a.empty();for(var h=!1,c=0;c<d.length;c++){if(d[c].Protocol==
"Private Old DDNS")currenVendor=="Dahua"&&Site.currentLanguage=="SimpChinese"&&a.options.add(new Option("Private DDNS",d[c].Protocol));else{a.options.add(new Option(d[c].Protocol,d[c].Protocol));if(d[c].Protocol=="CP Plus DDNS"&&!h)e=a.selectedIndex=c;if((d[c].Protocol=="Private DDNS"||d[c].Protocol=="QUICK DDNS")&&currenVendor=="Dahua"){if(!h)e=a.selectedIndex=c;a.options[c].text="Dahua DDNS"}if(d[c].Name)a.options[c].text=d[c].Name}!h&&d[c].Enable&&(h=!0,e=c)}},_renderElements:function(){var b=
d[e],h=$("ddns_username");$("ddns_username_tip");var c=$("ddns_address"),k=$("ddns_port"),f=$("ddns_hostname"),l=$("ddns_keepalive"),m=$("ddns_password"),n=$("ddns_protocol"),o=$("ddns_enable");$("page_DDNSConfig").removeClass("private_ddns").addClass("ddns");$("ddns_protocol").value=="CP Plus DDNS"&&($("ddns_hostname").removeEvents("keyup"),$("ddns_hostname").addEvent("keyup",a._showPostBtn));$$("#ddns_test,#ddns_test_image,#ddns_hostname_postfix,#ddns_mode_wrap,#ddns_macAddress_wrap,#ddns_internetStatus_wrap,#ddns_cpPlusNotes_wrap,#ddns_username_tip").setStyle("display",
"none");$$("#ddns_serviceIp_wrap,#ddns_username_wrap,#ddns_password_wrap,#ddns_keepalive_wrap").setStyle("display","");$("ddns_test_tip").set("text","");$("ddns_test_tipred").set("text","");$("ddns_username_tipred").set("text","");$("ddns_password_tip").set("text","");$("ddns_address_tip").set("text","");a._hostnameAvailable(!0);c.disabled=!1;f.disabled=!1;o.checked=b.Enable?!0:!1;n.selectedIndex=e;c.value=b.Address;k.value=b.Port;f.value=b.HostName;h.value=b.UserName;m.value=b.Password;l.value=b.KeepAlive;
f.maxLength=64;b.Protocol==="Private DDNS"||b.Protocol==="QUICK DDNS"?(h=b.Address.indexOf("w"),h+=3,g=b.Address.contains(".")?b.Address.slice(h):"",$("ddns_hostname_postfix").style.display="",$("ddns_hostname_postfix").set("text",g),$("ddns_mode_wrap").style.display="",$("ddns_username_tip").style.display="",$("ddns_password_wrap").style.display="none",$("ddns_keepalive_wrap").style.display="none",$("page_DDNSConfig").addClass("private_ddns").removeClass("ddns"),f.maxLength=60,$("ddns_address").disabled=
!0,b.DefaultHostName&&b.DefaultHostName.Enable?($("ddns_mode_auto").checked=!0,f.value=b.DefaultHostName.HostName.replace(g,""),f.disabled=!0):($("ddns_mode_manual").checked=!0,$("ddns_test").style.display="",f.disabled=!1,f.value=b.HostName.replace(g,""))):$("ddns_address").disabled=!0;if(b.Protocol=="CP Plus DDNS")$("ddns_cpPlusNotes_wrap").style.display="",$("ddns_enable").checked?$("ddns_hostname").disabled=!1:$("ddns_hostname").disabled=!0,$("ddns_hostname").disabled=$("ddns_enable").checked?
!1:!0,$$("#ddns_serviceIp_wrap,#ddns_username_wrap,#ddns_password_wrap,#ddns_keepalive_wrap,#ddns_macAddress").setStyle("display","none"),$$("#ddns_macAddress_wrap,#ddns_internetStatus_wrap,#ddns_hostname_postfix,#ddns_macAddressSpan").setStyle("display",""),$("ddns_hostname").value=b.HostName.replace(/(.cpplusddns.com)+/,""),$("ddns_title9").innerHTML="http://"+$("ddns_hostname").value+".cpplusddns.com",$("ddns_hostname_postfix").set("text",".cpplusddns.com"),j==""&&a.configManager.getConfig("Network",
function(a){a=getTable(a);j=a[a.DefaultInterface].PhysicalAddress},!1),$("ddns_macAddressSpan").set("text",j),i=60,a._getConnectState("one");b.Protocol=="Private Old DDNS"?($("ddns_address").disabled=!1,$("ddns_port_wrap").style.display=""):$("ddns_port_wrap").style.display="none"},_onProtocolChange:function(){a._hostnamePasteDeal();a._saveData();a._checkHostnameInput()?(e=this.selectedIndex,a._renderElements()):this.selectedIndex=e},_checkHostnameInput:function(){return d[e].Protocol.test("CP Plus DDNS")&&
$("ddns_hostname").value.length<3?(remarkDisplay("ddns_remark",tl("w_Operation failed:The hostname of CP Plus DDNS cannot be less than three alphas"),3E3,1),!1):!0},_onModeAutoClick:function(){$("ddns_hostname").disabled=!0;$$("#ddns_test,#ddns_tesst_img").setStyle("display","none");$("ddns_test_tip").set("text","");$("ddns_confirm").removeEvents("click");$("ddns_confirm").removeClass("ui-button-disabled");$("ddns_confirm").addEvent("click",a._onConfirmClick);if(d[e].DefaultHostName)$("ddns_hostname").value=
d[e].DefaultHostName.HostName.replace(g,"")},_onModeManualClick:function(){$("ddns_test").style.display="";$("ddns_test_image").setStyle("display","none");$("ddns_hostname").disabled=!1;$("ddns_hostname").value=d[e].HostName.replace(g,"")},_onTestClick:function(){var b=$("ddns_protocol").value,h=$("ddns_address").value,c=$("ddns_port").value-0,k=$("ddns_hostname").value+g,f=$("ddns_username").value,i=$("ddns_password").value;$("ddns_test_tip").set("text",tl("testing..."));$("ddns_test_tip").className=
"ui-tip-red";$("ddns_test_image").style.display="";a._testAvailable(!1);a.render=$empty;a.ddnsClient.testHostName(b,h,c,k,f,i,function(b){a.render=a._render;var b=JSON.decode(b),c="";$("ddns_test_image").style.display="none";if(b.result)$("ddns_test_tip").set("text",tl("Succeed!")),$("ddns_test_tip").className="ui-tip-green",a._hostnameAvailable(!0),a._testAvailable(!0);else{if(b.params&&b.params.Detail)c=b.params.Detail;$("ddns_test_tip").className="ui-tip-red";a._hostnameAvailable(!0);a._testAvailable(!0);
$("ddns_hostname").value=d[e].HostName.replace(g,"");switch(c){case "badauth\r\n":case "badsys\r\n":case "badagent\r\n":case "notfqdn\r\n":$("ddns_test_tip").set("text",tl("Fail!"));break;case "nohost\r\n":$("ddns_test_tip").set("text",tl("Domain Exist!"));break;case "!yours\r\n":$("ddns_test_tip").set("text",tl("Domain Used!"));break;case "!active\r\n":case "abuse\r\n":case "dnserr\r\n":case "911\r\n":$("ddns_test_tip").set("text",tl("Server Fail!"));break;default:$("ddns_test_tip").set("text",tl("Fail!"))}}setTimeout(function(){$("ddns_test_tip").set("text",
"")},3E3)})},_onDefaultClick:function(){a.configManager.getDefault("DDNS",function(b){JSON.decode(b).result?($("ddns_confirm").removeEvents("click"),$("ddns_confirm").removeClass("ui-button-disabled"),$("ddns_confirm").addEvent("click",a._onConfirmClick),d=getTable(b),e=0,a._setProtocolOptions(),a._renderElements(),remarkDisplay("ddns_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("ddns_remark",tl("Defaultfailure"),3E3,1)})},_onRefreshClick:function(){a.configManager.getConfig("DDNS",function(b){JSON.decode(b).result?
($("ddns_confirm").removeEvents("click"),$("ddns_confirm").removeClass("ui-button-disabled"),$("ddns_confirm").addEvent("click",a._onConfirmClick),d=getTable(b),a._setProtocolOptions(),a._renderElements(),remarkDisplay("ddns_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("ddns_remark",tl("Operateingfailure"),3E3,1)})},_onConfirmClick:function(){var b=!0;a._hostnamePasteDeal();if(checkedImportLimt("ddns_hostname",1))if(checkedImportLimt("ddns_username",3))if(checkedImportLimt("ddns_password",
3)){a._saveData();if($("ddns_protocol").value=="CP Plus DDNS"){if(!/^[a-zA-Z0-9-_.]+$/.test(d[e].HostName.replace(".cpplusddns.com",""))){remarkDisplay("ddns_remark",tl("w_wrongDomainName"),3E3,1);return}$("ddns_confirm").removeEvents("click");$("ddns_confirm").addClass("ui-button-disabled");$("ddns_refresh").removeEvents("click");$("ddns_refresh").addClass("ui-button-disabled");$("ddns_default").removeEvents("click");$("ddns_default").addClass("ui-button-disabled")}d.each(function(a){if((a.Protocol===
"Private DDNS"||a.Protocol==="QUICK DDNS")&&!expressionCheck(7,a.UserName)&&a.UserName!=="")a.Protocol==="Private DDNS"?remarkDisplay("ddns_remark",tl("w_emailLimite"),3E3,1):remarkDisplay("ddns_remark",tl("w_quickemailLimite"),3E3,1),b=!1;a.Protocol=="Private Old DDNS"&&!expressionCheck(1,a.Address)&&(remarkDisplay("ddns_remark",tl("w_wrongServerName"),3E3,1),b=!1)});b&&a.configManager.setConfig("DDNS",d,a._postresult)}else remarkDisplay("ddns_remark",tl("w_noInputMarks"),3E3,1);else remarkDisplay("ddns_remark",
tl("w_noInputMarks"),3E3,1);else remarkDisplay("ddns_remark",tl("w_wrongDomainName2"),3E3,1)},_postresult:function(b){JSON.decode(b).result?(remarkDisplay("ddns_remark",tl("Succeed in saving configure"),3E3,0),$("ddns_protocol").value=="CP Plus DDNS"&&(a.dialog.show(),$("ddns_connectDDNSTitle").set("text",tl("w_DDNSconnectting")),i=60,setTimeout(a._getConnectState,6E3))):($("ddns_protocol").value=="CP Plus DDNS"&&($("ddns_confirm").removeEvents("click"),$("ddns_confirm").removeClass("ui-button-disabled"),
$("ddns_refresh").removeEvents("click"),$("ddns_refresh").removeClass("ui-button-disabled"),$("ddns_default").removeEvents("click"),$("ddns_default").removeClass("ui-button-disabled"),$("ddns_confirm").addEvent("click",a._onConfirmClick),$("ddns_refresh").addEvent("click",a._onRefreshClick),$("ddns_default").addEvent("click",a._onDefaultClick)),remarkDisplay("ddns_remark",tl("Saving failure"),3E3,1))},_onHostnameKeyup:function(){promptImportLimt(this.id,"ddns_test_tipred","w_wrongDomainName2",1);
if($("ddns_protocol").value==="Private DDNS"||$("ddns_protocol").value==="QUICK DDNS")$("ddns_mode_manual").checked&&($("ddns_hostname").value!==d[e].HostName.replace(g,"")?a._hostnameAvailable(!1):a._hostnameAvailable(!0))},_hostnameAvailable:function(b){$("ddns_confirm").disabled=!b;$("ddns_mode_auto").disabled=!b;$("ddns_mode_manual").disabled=!b;$("ddns_protocol").disabled=!b;b?($("ddns_confirm").addEvent("click",a._onConfirmClick),$("ddns_confirm").removeClass("ui-button-disabled")):($("ddns_confirm").removeEvents("click"),
$("ddns_confirm").addClass("ui-button-disabled"))},_testAvailable:function(b){$("ddns_protocol").disabled=!b;$("ddns_mode_auto").disabled=!b;$("ddns_mode_manual").disabled=!b;$("ddns_hostname").disabled=!b;$("ddns_username").disabled=!b;$("ddns_enable").disabled=!b;b?($("ddns_confirm").addEvent("click",a._onConfirmClick),$("ddns_confirm").removeClass("ui-button-disabled"),$("ddns_refresh").addEvent("click",a._onRefreshClick),$("ddns_refresh").removeClass("ui-button-disabled"),$("ddns_default").addEvent("click",
a._onDefaultClick),$("ddns_default").removeClass("ui-button-disabled"),$("ddns_test").addEvent("click",a._onTestClick),$("ddns_test").removeClass("ui-button-disabled")):($("ddns_confirm").removeEvents("click"),$("ddns_confirm").addClass("ui-button-disabled"),$("ddns_refresh").removeEvents("click"),$("ddns_refresh").addClass("ui-button-disabled"),$("ddns_default").removeEvents("click"),$("ddns_default").addClass("ui-button-disabled"),$("ddns_test").removeEvents("click"),$("ddns_test").addClass("ui-button-disabled"))},
_saveData:function(){var a=d[e];a.Enable=!!$("ddns_enable").checked;if(a.Protocol==="Private DDNS"||a.Protocol==="QUICK DDNS")if($("ddns_mode_manual").checked){if(a.HostName=$("ddns_hostname").value+g,a.DefaultHostName)a.DefaultHostName.Enable=!1}else{if(a.DefaultHostName)a.DefaultHostName.Enable=!0}else a.HostName=$("ddns_hostname").value;a.Address=$("ddns_address").value;a.Port=$("ddns_port").value-0;a.UserName=$("ddns_username").value;a.Password=$("ddns_password").value;a.KeepAlive=$("ddns_keepalive").value-
0},_getConnectState:function(b){i--;var d="",c="",g="";new DDNSClient;a.ddnsClient.getStatus(function(f){switch(JSON.decode(f).params.status[e].Status){case 0:d="Disconnected";i>0&&b==void 0&&setTimeout(a._getConnectState,1E3);break;case 1:d="m_connected";switch(JSON.decode(f).params.status[e].Value){case 908:c="w_cpDDNS908";break;case 909:c="w_cpDDNS909";break;case 910:c="w_cpDDNS910";break;case 801:c="w_cpDDNS801";break;case 702:c="w_cpDDNS702";break;default:c=""}$("ddns_connectDDNSTitle").set("text",
tl("m_connected")+": "+tl(c));setTimeout(a._closeDialog,5E3);$("ddns_confirm").removeEvents("click");$("ddns_confirm").removeClass("ui-button-disabled");$("ddns_refresh").removeEvents("click");$("ddns_refresh").removeClass("ui-button-disabled");$("ddns_default").removeEvents("click");$("ddns_default").removeClass("ui-button-disabled");$("ddns_confirm").addEvent("click",a._onConfirmClick);$("ddns_refresh").addEvent("click",a._onRefreshClick);$("ddns_default").addEvent("click",a._onDefaultClick);g=
JSON.decode(f).params.status[e].ConIp;break;case 2:JSON.decode(f).params.status[e].Value==601?(c="w_cpDDNS601",$("ddns_connectDDNSTitle").set("text",tl("Disconnected")+": "+tl(c)),setTimeout(a._closeDialog,5E3)):a.dialog&&a.dialog.close(),d="Disconnected",$("ddns_confirm").removeEvents("click"),$("ddns_confirm").removeClass("ui-button-disabled"),$("ddns_refresh").removeEvents("click"),$("ddns_refresh").removeClass("ui-button-disabled"),$("ddns_default").removeEvents("click"),$("ddns_default").removeClass("ui-button-disabled"),
$("ddns_confirm").addEvent("click",a._onConfirmClick),$("ddns_refresh").addEvent("click",a._onRefreshClick),$("ddns_default").addEvent("click",a._onDefaultClick)}switch(JSON.decode(f).params.status[e].Value){case 0:c="w_cpDDNS0";break;case 901:c="w_cpDDNS901";break;case 902:c="w_cpDDNS902";break;case 903:c="w_cpDDNS903";break;case 904:c="w_cpDDNS904";break;case 905:c="w_cpDDNS905";break;case 906:c="w_cpDDNS906";break;case 911:c="w_cpDDNS911";break;case 907:c="w_cpDDNS907";break;case 912:c="w_cpDDNS912";
break;default:$("ddns_enable").checked||(c="w_Note:The CP PLUS DDNS function has not been enabled")}$("ddns_noteStatus").className="ui-text";$("ddns_noteStatus").set("text","");if(i==0)$("ddns_internetStatus").set("text",tl("Disconnected")),$("ddns_noteStatus").set("text",tl("w_cpDDNS0")),$("ddns_noteStatus").className="ui-tip-red",$("ddns_confirm").removeEvents("click"),$("ddns_confirm").removeClass("ui-button-disabled"),$("ddns_refresh").removeEvents("click"),$("ddns_refresh").removeClass("ui-button-disabled"),
$("ddns_default").removeEvents("click"),$("ddns_default").removeClass("ui-button-disabled"),$("ddns_confirm").addEvent("click",a._onConfirmClick),$("ddns_refresh").addEvent("click",a._onRefreshClick),$("ddns_default").addEvent("click",a._onDefaultClick),a.dialog.close();else{if(JSON.decode(f).params.status[e].Status==1)$("ddns_noteStatus").set("text",g);else if(JSON.decode(f).params.status[e].Status==2)$("ddns_noteStatus").set("text",tl(c)),$("ddns_noteStatus").className="ui-tip-red";else if(JSON.decode(f).params.status[e].Status==
0&&b!=void 0)$("ddns_noteStatus").set("text",tl(c)),$("ddns_noteStatus").className="ui-tip-red";$("ddns_internetStatus").set("text",tl(d))}},!1)},_closeDialog:function(){a.dialog.close()},_onEnableClick:function(){if($("ddns_protocol").value=="CP Plus DDNS")$("ddns_hostname").disabled=$("ddns_enable").checked?!1:!0},_showPostBtn:function(){$("ddns_title9").innerHTML="http://"+$("ddns_hostname").value+".cpplusddns.com";$("ddns_hostname").value==""||$("ddns_hostname").value.length==0?($("ddns_test_tip").set("text",
tl("w_wrongHostName")),$("ddns_confirm").addClass("ui-button-disabled"),$("ddns_confirm").removeEvents("click")):($("ddns_test_tip").set("text",""),$("ddns_confirm").removeEvents("click"),$("ddns_confirm").removeClass("ui-button-disabled"),$("ddns_confirm").addEvent("click",a._onConfirmClick))}}})();
