(function(){var a,e,b=Page.emailConfig={init:function(){b.configManager=new ConfigManager;b.netApp=new NetApp;b.translate();b.render();b.bind()},translate:function(){$("smtp_set").set("text",tl("w_Mail Settings"));$("smtp_help").set("title",tl("w_help"));$("smtp_server_address_label").set("text",tl("w_SMTP Server"));$("smtp_server_port_label").set("text",tl("w_Port"));$("smtp_anonymous_label").set("text",tl("w_Anonymity"));$("smtp_username_label").set("text",tl("w_Username"));$("smtp_password_label").set("text",
tl("w_password"));$("smtp_send_address_label").set("text",tl("w_SendAddress"));$("smtp_title_label").set("text",tl("w_Theme"));$("smtp_attachment_enable_label").set("text",tl("w_Bear Mail"));$("smtp_auth_label").set("text",tl("w_SSL Encrypt"));$("smtp_auth_none").set("text",tl("None"));$("smtp_receivers_label").set("text",tl("w_Mailreceiver"));$("smtp_send_interval_label").set("text",tl("w_Send Interval"));$("smtp_send_interval_unit").set("text",tl("w_Second"));$("smtp_health_report_enable_label").set("text",
tl("w_Send Healthy Mail"));$("smtp_health_report_interval_label").set("text",tl("w_sendhealthinterval"));$("smtp_health_report_interval_unit").set("text",tl("w_Second"));$("smtp_test").set("text",tl("w_Test Email"));$("smtp_default").set("text",tl("w_DefaultConfig"));$("smtp_refresh").set("text",tl("w_Refresh"));$("smtp_confirm").set("text",tl("w_Confirm"))},render:function(){b._getData();b._renderElements()},bind:function(){$("smtp_health_report_enable").addEvent("click",b._onHealthReportClick);
$("smtp_receiver").addEvent("keyup",b._onReceiverKeyup);$("smtp_receiver").addEvent("focus",function(){var a=b._onReceiverKeyup.bind(this);this.timer=setInterval(a,100)});$("smtp_receiver").addEvent("blur",function(){b._onReceiverKeyup.call(this);clearInterval(this.timer);this.timer=null});$("smtp_receiver_add").addEvent("click",b._onReceiverAddClick);$("smtp_receiver_del").addEvent("click",b._onReceiverDelClick);$("smtp_test").addEvent("click",b._onTestClick);$("smtp_confirm").addEvent("click",b._onConfirmClick);
$("smtp_refresh").addEvent("click",b._onRefreshClick);$("smtp_default").addEvent("click",b._onDefaultClick);$("smtp_server_address").addEvent("keyup",function(){promptImportLimt("smtp_server_address","smtp_server_address_tip","w_wrongServerName",1)});$("smtp_username").addEvent("keyup",function(){promptImportLimt("smtp_username","smtp_username_tipred","w_noInputMarks",3);StringUtil.byteLength(this.value,"aaa")>32?$("smtp_username_tip").setProperty("text",tl("w_usernameTooLong")):$("smtp_username_tip").setProperty("text",
"")});$("smtp_username").addEvent("blur",function(){promptImportLimt("smtp_username","smtp_username_tipred","w_noInputMarks",3);StringUtil.byteLength(this.value,"aaa")>32?$("smtp_username_tip").setProperty("text",tl("w_usernameTooLong")):$("smtp_username_tip").setProperty("text","")});$("smtp_password").addEvent("keyup",function(){promptImportLimt("smtp_password","smtp_password_tip","w_noInputMarks",3)});$("smtp_title").addEvent("keyup",function(){promptImportLimt("smtp_title","smtp_title_tip","w_noInputMarks",
3)});$("smtp_title").addEvent("blur",b._onEmailTitleBlur);attachLimit("smtp_send_interval",0,3600);attachLimit("smtp_health_report_interval",1,3600);attachLimit("smtp_server_port",1,65535);$("smtp_server_port").addEvent("keyup",function(){this.value-=0});$("smtp_help").addEvent("click",function(){openHelp("emailConfig.htm")});$("smtp_send_address").addEvent("focus",function(){$("smtp_send_address_tip").innerHTML=""})},_onEmailTitleBlur:function(){for(var a=$("smtp_title").value,b,d=0;d<a.length;d++)if(b=
a.slice(0,d),b.replace(/[^\x00-\xff]/g,"xxx").length>120){$("smtp_title").value=$("smtp_title").value.slice(0,d-1);break}},_getData:function(f,c){var d="Operateing",f=f||!1,c=c||"getConfig";c==="getDefault"&&(d="Default");b.configManager[c]("Email",function(b){JSON.decode(b).result?f&&remarkDisplay("smtp_remark",tl(d+"success"),3E3,0):remarkDisplay("smtp_remark",tl(d+"failure"),3E3,1);a=getTable(b)},!1)},_renderElements:function(){$("smtp_server_address_tip").setProperty("text","");$("smtp_username_tip").setProperty("text",
"");$("smtp_password_tip").setProperty("text","");$("smtp_title_tip").setProperty("text","");$("smtp_username_tipred").setProperty("text","");$("smtp_server_address").value=a.Address;$("smtp_server_port").value=a.Port;$("smtp_anonymous").checked=a.Anonymous;$("smtp_username").value=a.UserName;$("smtp_password").value=a.Password;$("smtp_send_address").value=a.SendAddress;$("smtp_receiver").value="";$("smtp_receiver_add").setProperty("disabled",!0).addClass("ui-set-control-icon-disabled");$("smtp_title").value=
a.Title;$("smtp_attachment_enable").checked=a.AttachEnable;a.SslEnable?$("smtp_auth").value="SSL":a.TlsEnable?$("smtp_auth").value="TLS":$("smtp_auth").value="None";$("smtp_send_address_tip").innerHTML="";b._showReceiverList();$("smtp_send_interval").value=a.SendInterv;$("smtp_health_report_enable").checked=a.HealthReport.Enable;$("smtp_health_report_interval").value=a.HealthReport.Interval;b._onHealthReportClick()},_showReceiverList:function(){var b="",c=a.Receivers.filter(function(a){return a!=
""});a.Receivers=c;e=-1;$("smtp_receiver_del").disabled=!0;$("smtp_receiver_del").addClass("ui-set-control-icon-disabled");c.each(function(a,c){b+='<a id="smtp_receiver_address_'+c+'" class="ui-receiver-address">'+a+"&nbsp</a>"});$("smtp_receiver_list").innerHTML=b;$$(".ui-receiver-address").addEvent("click",function(){$$(".ui-receiver-address").each(function(a){a.removeClass("ui-receiver-address-current")});e=this.id.replace(/[^\d]/g,"");this.addClass("ui-receiver-address-current");$("smtp_receiver_del").disabled=
!1;$("smtp_receiver_del").removeClass("ui-set-control-icon-disabled")})},_onAnonymousClick:function(){$("smtp_anonymous").checked?($("smtp_username").value="anonymity",$("smtp_password").value="none",$("smtp_send_address").value="none",$("smtp_username").disabled=!0,$("smtp_password").disabled=!0,$("smtp_send_address").disabled=!0):($("smtp_username").disabled=!1,$("smtp_password").disabled=!1,$("smtp_send_address").disabled=!1)},_onHealthReportClick:function(){$("smtp_health_report_interval").disabled=
$("smtp_health_report_enable").checked?!1:!0},_onReceiverKeyup:function(){this.value.length?$("smtp_receiver_add").setProperty("disabled",!1).removeClass("ui-set-control-icon-disabled"):$("smtp_receiver_add").setProperty("disabled",!0).addClass("ui-set-control-icon-disabled")},_onReceiverAddClick:function(){checkedImportLimt("smtp_receiver",7)?a.Receivers.length==3?remarkDisplay("smtp_remark",tl("w_emailrevnum"),3E3,1):a.Receivers.contains($("smtp_receiver").value)?remarkDisplay("smtp_remark",tl("w_sameEmail"),
3E3,1):(a.Receivers.include($("smtp_receiver").value),$("smtp_receiver").value="",this.disabled=!0,this.addClass("ui-set-control-icon-disabled"),b._showReceiverList()):remarkDisplay("smtp_remark",tl("w_emailreverror"),3E3,1)},_onReceiverDelClick:function(){e<0||e>=a.Receivers.length||(a.Receivers.splice(e,1),b._showReceiverList())},_onTestClick:function(){b.netApp.sendTestMail(function(a){JSON.decode(a).result?remarkDisplay("smtp_remark",tl("w_emailtestsuccess"),3E3,0):remarkDisplay("smtp_remark",
tl("w_emailtestfail"),3E3,1)},!1)},_onConfirmClick:function(){if(b._checkFormat())if($("smtp_send_address").value=="")$("smtp_send_address_tip").innerHTML=tl("w_Need");else if(StringUtil.byteLength($("smtp_username").value,"aaa")>32)$("smtp_username_tip").setProperty("text",tl("w_usernameTooLong")),remarkDisplay("smtp_remark",tl("w_usernameTooLong"),3E3,1);else{$("smtp_username_tip").setProperty("text","");b._onEmailTitleBlur();a.Address=$("smtp_server_address").value;a.Port=$("smtp_server_port").value-
0;a.Anonymous=$("smtp_anonymous").checked;a.UserName=$("smtp_username").value;a.Password=$("smtp_password").value;a.SendAddress=$("smtp_send_address").value;a.Title=$("smtp_title").value;a.AttachEnable=$("smtp_attachment_enable").checked;switch($("smtp_auth").value){case "SSL":a.SslEnable=!0;a.TlsEnable=!1;break;case "TLS":a.SslEnable=!1;a.TlsEnable=!0;break;default:a.SslEnable=!1,a.TlsEnable=!1}a.SendInterv=$("smtp_send_interval").value-0;a.HealthReport.Enable=$("smtp_health_report_enable").checked;
a.HealthReport.Interval=$("smtp_health_report_interval").value-0;b.configManager.setConfig("Email",a,function(a){JSON.decode(a).result?remarkDisplay("smtp_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("smtp_remark",tl("Saving failure"),3E3,1)},!1)}},_onRefreshClick:function(){b._getData(!0);b._renderElements()},_onDefaultClick:function(){b._getData(!0,"getDefault");b._renderElements()},_checkFormat:function(){return!checkedImportLimt("smtp_server_address",1)?(remarkDisplay("smtp_remark",
tl("w_wrongServerName"),3E3,1),!1):!checkedImportLimt("smtp_username",3)?(remarkDisplay("smtp_remark",tl("w_noInputMarks"),3E3,1),!1):!checkedImportLimt("smtp_password",3)?(remarkDisplay("smtp_remark",tl("w_noInputMarks"),3E3,1),!1):$("smtp_send_address").value!=""&&$("smtp_send_address").value!="none"&&!checkedImportLimt("smtp_send_address",7)?(remarkDisplay("smtp_remark",tl("w_emailsendererror"),3E3,1),!1):!checkedImportLimt("smtp_title",3)?(remarkDisplay("smtp_remark",tl("w_wrongEmailTitle"),3E3,
1),!1):!0}}})();
