(function(){(function(){var h=Page.networkConfig={Tab:[],init:function(){h.Tab.tcpip.init();isEnable("is_show_T2UServer")&&(h.Tab.T2UServer.init(),$("tcpip_T2UServer").setStyle("display","block"));h.translate();h.bind();h.render()},translate:function(){},render:function(){$$("#page_networkConfig .ui-tab-current").fireEvent("click")},_onTabTitleClick:function(){var e=this.getProperty("data-for");$$("#page_networkConfig .tcpip_tab_title").removeClass("ui-tab-current");$$("#page_networkConfig .ui-container").setStyle("display",
"none");this.addClass("ui-tab-current");h.Tab[e].render();$("tcpip_tab_"+e).setStyle("display","block")},bind:function(){$("tcpip_help").addEvent("click",function(){openHelp("networkConfig.htm")});$$("#page_networkConfig .tcpip_tab_title").addEvent("click",h._onTabTitleClick)}}})();(function(){function h(a,f,b){var j=$(a),c;c=a=="tcpip_v4_address_0"?$("tcpip_v4_address_1"):a=="tcpip_v4_gateway_0"?$("tcpip_v4_gateway_1"):a=="tcpip_v4_preferred_dns_0"?$("tcpip_v4_preferred_dns_1"):$("tcpip_v4_alternate_dns_1");
var d=this.value;j.removeEvents("keyup");j.removeEvents("blur");j.addEvents({keyup:function(a){a=a.code;if(a==110||a==190||a==39){if(this.value.length==1&&(a==110||a==190))this.value=d;c.select()}else a!=9&&a!=37&&this.value.length>=3&&c.select()},blur:function(){if(this.value-0==127)remarkDisplay("tcpip_remark",tl("w_ipv4_127"),3E3,2),this.value=1;(this.value-0==0||this.value-0>223)&&remarkDisplay("tcpip_remark",tl("w_ipv4_range"),3E3,2);limit(this,b);limitMin(this,f)},focus:function(){d=this.value;
this.select()}})}function e(a,f,b){var a=$(a),c=a.getPrevious("input");a.removeEvents("keyup");a.removeEvents("blur");var d=this.value;a.addEvents({keyup:function(a){a=a.code;if(a==110||a==190||a==39)if(this.value.length==1&&(a==110||a==190))this.value=d;this.value-0>254&&remarkDisplay("tcpip_remark",tl("w_ipv4_range_last"),3E3,2);limitEx(this,b);a==37&&c.select()},blur:function(){if(this.value-0==0)remarkDisplay("tcpip_remark",tl("w_ipv4_range_last"),3E3,2),this.value=1;limit(this,b);limitMin(this,
f)},focus:function(){d=this.value;this.select()}})}var g={},c={},d={},k={},l=[],i={},m={},o,n=!0,b=Page.networkConfig.Tab.tcpip={init:function(){b.configManager=new ConfigManager;b.netApp=new NetApp;b.translate();b.bind();b.render()},translate:function(){$("tcpip").set("text",tl("w_TCP/IP Settings"));$("tcpip_help").set("title",tl("w_help"));$("tcpip_hostname_label").set("text",tl("w_HostName"));$("tcpip_network_card_label").set("text",tl("w_Ethernet Card"));$("tcpip_network_card_set_as_default").set("text",
tl("w_Set DefaultCard"));$("tcpip_mac_address_label").set("text",tl("w_Mac Address"));$("tcpip_version_label").set("text",tl("w_IP Version"));$("tcpip_v4_mode_label").set("text",tl("w_Mode"));$("tcpip_v4_mode_static_label").set("text",tl("w_Static"));$("tcpip_v4_address_label").set("text",tl("w_IP Address"));$("tcpip_v4_subnet_mask_label").set("text",tl("w_Subnet Mask"));$("tcpip_v4_gateway_label").set("text",tl("w_Default Gateway"));$("tcpip_v4_preferred_dns_label").set("text",tl("w_First DNS Server"));
$("tcpip_v4_alternate_dns_label").set("text",tl("w_Second DNS Server"));$("tcpip_v6_mode_label").set("text",tl("w_Mode"));$("tcpip_v6_mode_static_label").set("text",tl("w_Static"));$("tcpip_v6_link_address_label").set("text",tl("w_Link Address"));$("tcpip_v6_address_label").set("text",tl("w_IP Address"));$("tcpip_v6_gateway_label").set("text",tl("w_Default Gateway"));$("tcpip_v6_preferred_dns_label").set("text",tl("w_First DNS Server"));$("tcpip_v6_alternate_dns_label").set("text",tl("w_Second DNS Server"));
$("tcpip_arp_enable_label").set("text",tl("w_Open ARP/Ping"));$("tcpip_default").set("text",tl("w_DefaultConfig"));$("tcpip_refresh").set("text",tl("w_Refresh"));$("tcpip_confirm").set("text",tl("w_Confirm"))},render:function(){b._getNetInterfaces()&&b._getConfigs()?(b._setNetworkCardOptions(),b._renderElements(c,d,k)):remarkDisplay("tcpip_remark",tl("Operateingfailure"),3E3,1)},bind:function(){$("tcpip_network_card").addEvent("change",b._onNetworkCardChange);$("tcpip_version").addEvent("change",
b._onVersionChange);$("tcpip_v4_mode_static").addEvent("click",b._onV4ModeStaticClick);$("tcpip_v4_mode_dhcp").addEvent("click",b._onV4ModeDhcpClick);$("tcpip_v6_mode_static").addEvent("click",b._onV6ModeStaticClick);$("tcpip_v6_mode_dhcp").addEvent("click",b._onV6ModeDhcpClick);$("tcpip_refresh").addEvent("click",b._onRefreshClick);$("tcpip_confirm").addEvent("click",b._onConfirmClick);["address","subnet_mask","gateway","preferred_dns","alternate_dns"].each(function(a){attachIpInput("tcpip_v4_"+
a+"_")});h("tcpip_v4_address_0",1,223);h("tcpip_v4_gateway_0",1,223);e("tcpip_v4_address_3",1,254);e("tcpip_v4_gateway_3",1,254);attachLimit("tcpip_v6_address_prefix",0,128);h("tcpip_v4_preferred_dns_0",1,223);e("tcpip_v4_preferred_dns_3",1,254);h("tcpip_v4_alternate_dns_0",1,223);e("tcpip_v4_alternate_dns_3",1,254);$("tcpip_hostname").addEvent("keyup",function(){promptImportLimt("tcpip_hostname","tcpip_hostname_tip","w_BadstringServerName",0)});$("tcpip_hostname").addEvent("blur",function(){promptImportLimt("tcpip_hostname",
"tcpip_hostname_tip","w_BadstringServerName",0)})},_getNetInterfaces:function(){var a;b.netApp.getNetInterfaces(function(f,b){(a=b.result)&&(l=b.params.netInterface.filter(function(a){return a.Name!=="3G"}))},!1);return a},_getConfigs:function(){var a;b.configManager.getConfig(["PPPoE","Network","IPv6","ARP&Ping"],function(f,b){if(a=b.result)g=b.params[0].result&&b.params[0].params.table,c=b.params[1].params.table,d=b.params[2].params.table,k=b.params[3].params.table,i=$unlink(c),m=$unlink(d)},!1);
return a},_setNetworkCardOptions:function(){$("tcpip_network_card").empty();$("tcpip_network_card_set_as_default").style.display=l.length===1?"none":"block";l.each(function(a){var b=a.Name==="eth0"?tl("w_Lineate"):tl("w_Wireless");b+=a.Name===c.DefaultInterface?"("+tl("DEFAULT")+")":"";$("tcpip_network_card").options.add(new Option(b,a.Name))})},_renderElements:function(a,f,c,j){$("tcpip_hostname_tip").setProperty("text","");o=j=j||a.DefaultInterface;$("tcpip_network_card").value=j;g&&g.Enable?($$("#tcpip_tab_tcpip input").setProperty("disabled",
!0),$("tcpip_hostname").setProperty("disabled",!1),$("tcpip_arp_enable").setProperty("disabled",!1),$("tcpip_default").removeEvents("click").addClass("ui-button-disabled"),$("tcpip_network_card_set_as_default").removeEvents("click").addClass("ui-button-disabled")):($$("#tcpip_tab_tcpip input").setProperty("disabled",!1),(6).times(function(a){$("tcpip_mac_address_"+a).setProperty("disabled",!0)}),$("tcpip_default").removeEvents("click").removeClass("ui-button-disabled").addEvent("click",b._onDefaultClick),
$("tcpip_network_card_set_as_default").removeEvents("click").removeClass("ui-button-disabled").addEvent("click",b._onNetworkCardSetAsDefaultClick));b._renderCommonElements(a,c,j);b._renderIPv4Elements(a,j);b._renderIPv6Elements(f,j);$("tcpip_version").value=/:/.test(location.hostname)?"IPv6":"IPv4";$("tcpip_version").fireEvent("change")},_renderCommonElements:function(a,b,c){$("tcpip_hostname").value=a.Hostname;a[c].PhysicalAddress.split(":").each(function(a,b){$("tcpip_mac_address_"+b).value=a});
$("tcpip_arp_enable").checked=b.SettingIP},_renderIPv4Elements:function(a,b){a[b].DhcpEnable?$("tcpip_v4_mode_dhcp").setProperty("checked",!0).fireEvent("click"):$("tcpip_v4_mode_static").setProperty("checked",!0).fireEvent("click");a[b].IPAddress.split(".").each(function(a,b){$("tcpip_v4_address_"+b).value=a});a[b].SubnetMask.split(".").each(function(a,b){$("tcpip_v4_subnet_mask_"+b).value=a});a[b].DefaultGateway.split(".").each(function(a,b){$("tcpip_v4_gateway_"+b).value=a});a[b].DnsServers[0].split(".").each(function(a,
b){$("tcpip_v4_preferred_dns_"+b).value=a});a[b].DnsServers[1].split(".").each(function(a,b){$("tcpip_v4_alternate_dns_"+b).value=a})},_renderIPv6Elements:function(a,b){$("tcpip_v6_link_address").set("text",a[b].LinkLocalAddress);$("tcpip_v6_address").value=a[b].IPAddress;$("tcpip_v6_address_prefix").value=a[b].Prefix;$("tcpip_v6_gateway").value=a[b].DefaultGateway;$("tcpip_v6_preferred_dns").value=a[b].DnsServers[0];$("tcpip_v6_alternate_dns").value=a[b].DnsServers[1];a[b].DhcpEnable?$("tcpip_v6_mode_dhcp").checked=
!0:$("tcpip_v6_mode_static").checked=!0},_onNetworkCardChange:function(){b._temporaryStorageConfigs(o);b._renderElements(c,d,k,this.value)},_onVersionChange:function(){this.value==="IPv4"?($("tcpip_v4_wrap").style.display="",$("tcpip_v6_wrap").style.display="none",$("tcpip_v4_mode_wrap").style.display="",$("tcpip_v6_mode_wrap").style.display="none"):($("tcpip_v6_mode_dhcp").checked?$$("#tcpip_v6_address, #tcpip_v6_address_prefix, #tcpip_v6_gateway").setProperty("disabled",!0):!g&&!g.Enable&&$$("#tcpip_v6_address, #tcpip_v6_address_prefix, #tcpip_v6_gateway").setProperty("disabled",
!1),$("tcpip_v4_wrap").style.display="none",$("tcpip_v6_wrap").style.display="",$("tcpip_v4_mode_wrap").style.display="none",$("tcpip_v6_mode_wrap").style.display="")},_onV4ModeStaticClick:function(){!g&&!g.Enable&&$$("input[id^=tcpip_v4_address], input[id^=tcpip_v4_subnet_mask], input[id^=tcpip_v4_gateway]").setProperty("disabled",!1)},_onV4ModeDhcpClick:function(){!g&&!g.Enable&&$$("input[id^=tcpip_v4_address], input[id^=tcpip_v4_subnet_mask], input[id^=tcpip_v4_gateway]").setProperty("disabled",
!0)},_onV6ModeStaticClick:function(){$$("#tcpip_v6_address, #tcpip_v6_address_prefix, #tcpip_v6_gateway").setProperty("disabled",!1)},_onV6ModeDhcpClick:function(){$$("#tcpip_v6_address, #tcpip_v6_address_prefix, #tcpip_v6_gateway").setProperty("disabled",!0)},_onNetworkCardSetAsDefaultClick:function(){i.DefaultInterface=$("tcpip_network_card").value;b.configManager.setConfig("Network",i,function(a,f){f.result?(c.DefaultInterface=i.DefaultInterface,b._setNetworkCardOptions(),b._renderElements(c,d,
k,c.DefaultInterface),remarkDisplay("tcpip_remark",tl("Succeed in saving configure"),3E3,0),isNeedReboot(a,"The configration take effect! The device is restarting now,please reconnect later...",!1,!1)):remarkDisplay("tcpip_remark",tl("Saving failure"),3E3,1)},!1)},_onDefaultClick:function(){$("tcpip_hostname_tip").setProperty("text","");b.configManager.getDefault(["Network","IPv6","ARP&Ping"],function(a,f){f.result?(c=f.params[0].params.table,d=f.params[1].params.table,k=f.params[2].params.table,
b._renderElements(c,d,k),$("tcpip_network_card").value=c.DefaultInterface,remarkDisplay("tcpip_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("tcpip_remark",tl("Defaultfailure"),3E3,1)})},_onRefreshClick:function(){$("tcpip_hostname_tip").setProperty("text","");b.configManager.getConfig(["PPPoE","Network","IPv6","ARP&Ping"],function(a,f){f.result?(g=f.params[0].result&&f.params[0].params.table,c=f.params[1].params.table,d=f.params[2].params.table,k=f.params[3].params.table,i=$unlink(c),m=$unlink(d),
b._renderElements(c,d,k,$("tcpip_network_card").value),remarkDisplay("tcpip_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("tcpip_remark",tl("Operateingfailure"),3E3,1)})},_onConfirmClick:function(){b._temporaryStorageConfigs($("tcpip_network_card").value);b._checkConfigsAvailability()&&b._setConfigs()},_temporaryStorageConfigs:function(a){c.Hostname=$("tcpip_hostname").value;k.SettingIP=$("tcpip_arp_enable").checked;c[a].DhcpEnable=$("tcpip_v4_mode_dhcp").checked;c[a].IPAddress=b._getIPString("tcpip_v4_address_");
c[a].SubnetMask=b._getIPString("tcpip_v4_subnet_mask_");c[a].DefaultGateway=b._getIPString("tcpip_v4_gateway_");c[a].DnsServers[0]=b._getIPString("tcpip_v4_preferred_dns_");c[a].DnsServers[1]=b._getIPString("tcpip_v4_alternate_dns_");d[a].DhcpEnable=$("tcpip_v6_mode_dhcp").checked;d[a].IPAddress=$("tcpip_v6_address").value;d[a].Prefix=$("tcpip_v6_address_prefix").value-0;d[a].DefaultGateway=$("tcpip_v6_gateway").value;d[a].DnsServers[0]=$("tcpip_v6_preferred_dns").value;d[a].DnsServers[1]=$("tcpip_v6_alternate_dns").value},
_getIPString:function(a){return[0,1,2,3].map(function(b){return $(a+b).value}).join(".")},_setConfigs:function(){var a=0;b.configManager.setConfig(["IPv6","ARP&Ping","Network"],[d,k,c],function(f,e){$clear(a);e.result?(isDDNS()&&l.each(function(a){if(i[a.Name].IPAddress!==c[a.Name].IPAddress||i[a.Name].DhcpEnable!==c[a.Name].DhcpEnable||m[a.Name].IPAddress!==d[a.Name].IPAddress||m[a.Name].DhcpEnable!==d[a.Name].DhcpEnable)parent.location.href="http://"+getDDNSMessage().ddnshost}),remarkDisplay("tcpip_remark",
tl("Succeed in saving configure"),1E3,0),b._reload(),i=$unlink(c),m=$unlink(d)):remarkDisplay("tcpip_remark",tl("Saving failure"),3E3,1)});a=this._reload.delay(3E3)},_checkConfigsAvailability:function(){return!checkedImportLimt("tcpip_hostname",0)||$("tcpip_hostname").value.length==0?(remarkDisplay("tcpip_remark",tl("w_BadstringServerName"),3E3,1),!1):b._checkIPv4Availability()&&b._checkIPv6Availability()},_checkIPv4Availability:function(){var a=[],f=[],d=!0;n=!0;l.each(function(b){a.push($unlink(c[b.Name]));
f.push($unlink(c[b.Name]))});a.each(function(a){var c=b._getNetworkSegment(a.IPAddress,a.SubnetMask),a=b._getNetworkSegment(a.DefaultGateway,a.SubnetMask);c!==a&&(remarkDisplay("tcpip_remark",tl("w_Not in the same network segment!"),3E3,1),d=!1)});if(!d)return!1;a.each(function(b){a.filter(function(a){return a.IPAddress===b.IPAddress}).length>1&&(d=!1)});if(!d)return remarkDisplay("tcpip_remark",tl("w_IP cannot be the same!"),3E3,1),!1;f.each(function(a){b._compareSubnet(a.SubnetMask)||(remarkDisplay("tcpip_remark",
tl("w_subnetAddressesWrong"),3E3,1),d=!1)});return!d?!1:!0},_compareSubnet:function(a){a=a.split(".");[0,1,2,3].map(function(c){n=n&&b.validateMask(a[c]-0)});return n},_checkIPv6Availability:function(){var a=!0;if(d.eth0&&d.eth2&&d.eth0.IPAddress==d.eth2.IPAddress)remarkDisplay("tcpip_remark",tl("w_IP cannot be the same!"),3E3,1);else return l.each(function(b){b=d[b.Name];a=a&&checkIPv6(b.IPAddress)&&checkIPv6(b.DefaultGateway)&&checkIPv6(b.DnsServers[0])&&checkIPv6(b.DnsServers[1])}),a||remarkDisplay("tcpip_remark",
tl("w_Bad IPv6 format!"),5E3,2),a},_getNetworkSegment:function(a,b){a=a.split(".");b=b.split(".");return[0,1,2,3].map(function(c){return a[c]&b[c]}).join(".")},checkIputFomartIP:function(a){return(a+256).toString(2).substring(1)},validateMask:function(a,c,d,e){return-1!=(b.checkIputFomartIP(a)+b.checkIputFomartIP(c)+b.checkIputFomartIP(d)+b.checkIputFomartIP(e)).indexOf("01")?!1:!0},_reload:function(){var a;a=location.hostname.replace(/(^\[)|(\]$)/g,"");for(var b="",e=0,h=l.length;h>e;e++){var g=
l[e];if(i[g.Name].IPAddress===a&&i[g.Name].IPAddress!=c[g.Name].IPAddress){b=c[g.Name].IPAddress;break}if(v6ToCanonicalForm(m[g.Name].IPAddress)===v6ToCanonicalForm(a)&&v6ToCanonicalForm(m[g.Name].IPAddress)!==v6ToCanonicalForm(d[g.Name].IPAddress)){b="["+d[g.Name].IPAddress+"]";break}}if(!b)e=c.DefaultInterface,i[e].IPAddress!==c[e].IPAddress&&(b=checkIPv6(a)?"["+a+"]":a);if(a=b)doLogout=$empty,window.removeEvents("unload").removeEvents("beforeunload"),location.href=location.protocol+"//"+a+":"+
location.port}}})();(function(){var h=null,e=Page.networkConfig.Tab.T2UServer={init:function(){e.configManager=new ConfigManager;e.nat=new Nat;e.translate();e.bind();e.render();e.initQrcode()},translate:function(){$("tcpip_T2Udefault").set("text",tl("w_DefaultConfig"));$("tcpip_T2Urefresh").set("text",tl("w_Refresh"));$("tcpip_T2Uconfirm").set("text",tl("w_Confirm"));$("tcpip_T2UEnable_label").setProperty("text",tl("Enable"));$("tcpip_T2UUUID_label").setProperty("text",tl("Status"))},render:function(){e.configManager.getConfig(["T2UServer"],
function(g,c){if(result=c.result)h=c.params[0].params.table,e._renderElements()})},initQrcode:function(){(new MagicBox).getSerialNo(function(e,c){$("tcpip_qrcodeSN").innerHTML="";$("tcpip_SN").innerHTML="";if(c.result&&c.params){var d=c.params.sn;if(d)$("tcpip_SN").innerHTML=d,$("tcpip_qrcodeSN").innerHTML=create_qrcode(d,4,"M",6)}})},_renderElements:function(){$("tcpip_T2UEnable").checked=h.Enable;e.nat.getTurnStatus(function(e,c){c.result&&(c.params.Status.IsTurnChannel?$("tcpip_T2UUUID").setProperty("text",
tl("w_online")):$("tcpip_T2UUUID").setProperty("text",tl("w_not_online")))})},_saveTempConfig:function(){h.Enable=$("tcpip_T2UEnable").checked},_onRefreshClick:function(){e.configManager.getConfig(["T2UServer"],function(g,c){c.result?(h=c.params[0].params.table,e._renderElements(),remarkDisplay("tcpip_T2Uremark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("tcpip_T2Uremark",tl("Operateingfailure"),3E3,1)})},_onDefaultClick:function(){e.configManager.getDefault(["T2UServer"],function(g,c){c.result?
(h=c.params[0].params.table,e._renderElements(),remarkDisplay("tcpip_T2Uremark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("tcpip_T2Uremark",tl("Defaultfailure"),3E3,1)})},_onConfirmClick:function(){e._saveTempConfig();e.configManager.setConfig(["T2UServer"],[h],function(e,c){c.result?remarkDisplay("tcpip_T2Uremark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("tcpip_T2Uremark",tl("Saving failure"),3E3,1)})},bind:function(){$("tcpip_T2Urefresh").addEvent("click",e._onRefreshClick);$("tcpip_T2Uconfirm").addEvent("click",
e._onConfirmClick);$("tcpip_T2Udefault").addEvent("click",e._onDefaultClick)}}})()})();
