var Site={currentPage:{},languages:{},currentLanguage:"English",hostname:getHostName(),httpport:getHttpPort()},Video={displayMode:Cookie.read("DHVideoWHMode")||"Adaptive Window",resolution:{x:0,y:0},rate:1.3333},Page={},Cache={},DEBUG=!1,cifPFrameMin=7,cifPFrameMax=40,g_Focusing=!1,PlayBack=null,localPngHash=new Hash;getLocalPngHash();
var USE_PLUGINS=!0,PLUGINS_VERSION=Browser.Platform.win?localPngHash.win_plugins_version:localPngHash.mac_plugins_version,PLUGINS_CLASSID="ED1EDBF5-CCC7-4171-A559-6578BD6D"+PLUGINS_VERSION.replace(/\./g,""),PLUGINS_NAME="WebActiveX.Plugin."+PLUGINS_VERSION,hasPlugin=checkPlugins();function isDDNS(){var a=window.location.href.split("?"),b=null;a[1]&&a[1].trim()&&(a=a[1],a.test(/username/g)&&a.test(/ccid/g)&&a.test(/p2pport/g)&&(b=a.split("&")));return b}
function getDDNSMessage(){var a=isDDNS(),b={};a[1]=Base64.decode(a[1]);for(var c=0;c<a.length;c++){var d=a[c].split("=");b[d[0]]=d[1]}return b}function checkPlugins(){var a;if(Browser.ie){try{a=new ActiveXObject(PLUGINS_NAME),delete a}catch(b){return!1}return!0}else return navigator.plugins.refresh(!1),a=navigator.mimeTypes["application/media-plugin-version-"+PLUGINS_VERSION],!(!a||!a.enabledPlugin)}
function loadPlugin(a){var b=document.getElementById("video1"),c="",d="";if(isDDNS())for(var d=getDDNSMessage(),e=d.resourcepath.split("_"),d="http://"+d.ddnshost+"/web",f=0;f<e.length;f++)d+="/"+e[f];hasPlugin?(b.innerHTML=Browser.ie?'<object id="ocx" width="100%" height="100%" classid="CLSID:{classid}">                                <param name="lVideoWindNum" value="1">                                <param name="VideoWindBarColor" value="414141">                                <param name="VideoWindTextColor" value="9c9c9c">                            </object>'.substitute({classid:PLUGINS_CLASSID}):
'<embed id="ocx" width="100%" height="100%"                                type="application/media-plugin-version-{version}"                                VideoWindTextColor="9c9c9c"                                VideoWindBarColor="414141">                            </embed>'.substitute({version:PLUGINS_VERSION}),b.innerHTML+='<img id="playback_pic" src="/image/black.png" style="display:none;"/>',bindOcxEvents.delay(100,window,a)):(Browser.Platform.win?c=d+"/webplugin.exe":Browser.Platform.mac?
c=" http://amcrest.com/downloads/webplugin_242.pkg":Browser.Platform.linux&&(c=d+"/webplugin.tar.bz2"),b.innerHTML='<div class="download-plugin" id="download_plugin" style="margin-top: -16px">                                <a href="{link}" target="_download">                                <span class="download-plugin-icon"></span>                                <span>{content}</span></a>                            </div>'.substitute({link:c,content:tl("w_no_plugins")}))}
function bindOcxEvents(a){$("ocx")?!Browser.ie&&!$("ocx").AddEventListener?bindOcxEvents.delay(100,window,a):(a||($("ocx").AddEventListener("ReturnWindInfo",OcxEventsHandler.ReturnWindInfo),$("ocx").AddEventListener("StateChanged",OcxEventsHandler.StateChanged),$("ocx").AddEventListener("DeviceDisconnected",OcxEventsHandler.DeviceDisconnected),$("ocx").AddEventListener("KeepAliveFailed",OcxEventsHandler.KeepAliveFailed),$("ocx").AddEventListener("DeviceReconnected",OcxEventsHandler.DeviceReconnected),
$("ocx").AddEventListener("TalkState",OcxEventsHandler.TalkState),$("ocx").AddEventListener("RButtonDown",OcxEventsHandler.RButtonDown),$("ocx").AddEventListener("ResolutionChange",OcxEventsHandler.ResolutionChange),$("ocx").AddEventListener("PlaybackRecordfileFailed",OcxEventsHandler.PlaybackRecordfileFailed),$("ocx").AddEventListener("RecordDiskFull",OcxEventsHandler.RecordDiskFull),$("ocx").AddEventListener("ErrorCode",OcxEventsHandler.ErrorCode)),$("ocx").AddEventListener("FocusZoomStatus",OcxEventsHandler.FocusZoomStatus),
$("ocx").AddEventListener("RegionChanged",OcxEventsHandler.CustomBackLight),$("ocx").AddEventListener("OutPutFilterRect",OcxEventsHandler.OutPutFilterRect),$("ocx").AddEventListener("OutPutShapeRect",OcxEventsHandler.OutPutShapeRect),$("ocx").AddEventListener("OutPutModuleRect",OcxEventsHandler.OutPutModuleRect),$("ocx").AddEventListener("OutPutStringInfo",OcxEventsHandler.OutPutStringInfo),$("ocx").AddEventListener("FileDialogInfo",OcxEventsHandler.FileDialogInfo),$("ocx").AddEventListener("MousePtzEvent",
OcxEventsHandler.MousePtzEvent),$("ocx").AddEventListener("FisheyeParamsEx",OcxEventsHandler.FisheyeParamsEx),$("ocx").AddEventListener("LocalFocus",OcxEventsHandler.LocalFocus),$("ocx").AddEventListener("DownLoadError",OcxEventsHandler.DownLoadError),$("ocx").AddEventListener("FeInstallMode",OcxEventsHandler.FeInstallMode),$("ocx").AddEventListener("VideoAnalyzeConfig",OcxEventsHandler.VideoAnalyzeConfig)):bindOcxEvents.delay(500,window,a)}
var OcxEventsHandler={DeviceReconnected:function(a,b){(new RPCLogin).login(a,b,function(){alarmCGI.close();clearInterval(alarm_timer);alarm_timer=setInterval("showAlarmTips()",1E3);clearInterval(g_aliveInterval);alive(300);g_aliveInterval=setInterval("alive(300)",6E4);(Site.currentPage.isPreview||Site.currentPage.isPTZ)&&$("b_Stream1").hasClass("ui-button-current")&&$$("#video_ivs_wrap .ui-video-wrap-item")[0].hasClass("ui-video-wrap-current")&&$("ocx")&&$("ocx").SetIVSEnable(!0);if(Page.tauConfig){var a=
new ThermographyManager;a.instance(function(a){if(JSON.decode(a).result)Page.tauConfig.Tab.Conditions.objectId=JSON.decode(a).result},!0)}else Page.leptonConfig&&(a=new ThermographyManager,a.instance(function(a){if(JSON.decode(a).result)Page.leptonConfig.Tab.Conditions.objectId=JSON.decode(a).result},!0))})},KeepAliveFailed:function(a,b){b&&$("ocx")&&$("ocx").ConnectRealVideo(0,a);keepActiveInit()},OutPutFilterRect:function(a,b,c,d){Site.currentPage.is.intellentConfig&&Page.intellentConfig._setFilterValue(a,
b,c,d)},OutPutShapeRect:function(a){Site.currentPage.is.intellentConfig&&Page.intellentConfig.Tab.rule._OutPutShapeRect(a)},OutPutModuleRect:function(a){Site.currentPage.is.intellentConfig&&Page.intellentConfig.Tab.para._OutPutModuleRect(a)},RButtonDown:function(a){if(Site.currentPage.isPreview&&a===0){if($("b_Stream1").hasClass("ui-button-current")&&(IPCIntellentShow||isIntellent))$("video_IVS_con").setStyle("display",""),$$("#video_ivs_wrap .ui-video-wrap-item")[0].hasClass("ui-video-wrap-current")&&
$("ocx")&&$("ocx").SetIVSEnable(!0);$("b_range").removeClass("main-top-icon-big-current")}Site.currentPage.isPreview&&a&&(new VideoInput).setFishEyeEPtz(0,a,"Undo",0,0,0,0,function(b,c){c.result&&FishEye.setFisheyeParams(a)});Site.currentPage.isPlayBack&&$("playback_zoom").removeClass("main-top-icon-big-current");Site.currentPage.is.functioncfg&&Page.functioncfg._rightButtonDown()},DeviceDisconnected:function(){},ReturnWindInfo:function(a,b,c,d){gwid=a;gst_sel=c;gptz=d},StateChanged:function(a,b,
c){try{$("ocx")&&$("ocx").SubVideoWndCtrl(3,0),$("video1").fireEvent("StateChanged",[a,b,c]),c==gwid&&(gst_sel=b),a!=-1&&(b==0?(resetIconState(),Site.currentPage.isPlayBack&&PlayBack.FishEye.closeFishEye()):b==1?play_pre==1?($("b_Stream1").addClass("ui-button-current"),$("b_Stream2").removeClass("ui-button-current"),$("b_Stream3").removeClass("ui-button-current"),play_state=1):play_pre==2?($("b_Stream2").addClass("ui-button-current"),$("b_Stream1").removeClass("ui-button-current"),$("b_Stream3").removeClass("ui-button-current"),
play_state=2):play_pre==3&&($("b_Stream3").addClass("ui-button-current"),$("b_Stream2").removeClass("ui-button-current"),$("b_Stream1").removeClass("ui-button-current"),play_state=3):resetIconState())}catch(d){}},TalkState:function(a){a==1?$("b_talk").removeClass("main-top-icon-speak-connect"):$("b_talk").addClass("main-top-icon-speak-connect")},VideoMouseEvent:function(a,b,c,d,e,f){Site.currentPage.isPreview&&$("b_figure").hasClass("main-top-icon-figure-current")&&mouseCtrlPtzEvent(b,c,d,e,f)},CustomBackLight:function(a,
b,c,d,e){Site.currentPage.is.cameraConfig&&Page.cameraConfig.Tab.Conditions._postBacklineCfg(b,c,d,e,2);Site.currentPage.is.sdCameraConfig&&Page.sdCameraConfig.Tab.config._postBacklineCfg(b,c,d,e);Site.currentPage.is.videoDetectConfig&&Page.videoDetectConfig.Tab.motionDetect._postMotionWindow(a,b,c,d,e);Site.currentPage.is.encodeConfig&&$("video_OSD_tab").hasClass("ui-tab-current")&&Page.encodeConfig.Tab.OSD.postOSDWindow(a,b,c,d,e);Site.currentPage.is.encodeConfig&&$("video_Intel_tab").hasClass("ui-tab-current")&&
Page.encodeConfig.Tab.Inter._postInterWindow(a,b,c,d,e);Site.currentPage.is.functioncfg&&Page.functioncfg.postBacklineCfg(b,c,d,e,2);Site.currentPage.isPreview&&$("b_locate").hasClass("main-top-icon-locate-current")&&postIVSWindow(b,c,d,e);(Site.currentPage.isPreview||Site.currentPage.isPTZ)&&$("yt5").hasClass("ui-ptz-icon-center-current")&&moveDirectly(a,b,c,d,e);typeof changePtzBtn=="function"&&changePtzBtn();Site.currentPage.isPreview&&FishEye&&FishEye.onOcxPaintRect.apply(window,arguments);Site.currentPage.is.leptonConfig&&
$("lepton_camara_label").hasClass("ui-tab-current")&&Page.leptonConfig.Tab.Conditions.PostInterWindow(a,b,c,d,e);Site.currentPage.is.tauConfig&&$("tau_camara_label").hasClass("ui-tab-current")&&Page.tauConfig.Tab.Conditions.PostInterWindow(a,b,c,d,e)},ResolutionChange:function(a,b){Video.resolution.x=a;Video.resolution.y=b;Video.rate=a/b;resize()},PlaybackRecordfileFailed:function(){PlayBack&&PlayBack.RecordFileFailedHandler()},RecordDiskFull:function(){$("b_record").removeClass("video1").addClass("video");
alert(tl("appEventStorageLowSpace"))},ErrorCode:function(a,b){b==0&&alert(tl("w_No Write Right"));if(a==17&&b==1)alert(tl("w_ErrorAuthorizeRelogin")),location.href="/"},DownLoadError:function(){var a=$$("#showfilelist .playback-dates-icon-delect")[0]&&$$("#showfilelist .playback-dates-icon-delect")[0].id;a&&PlayBack.downHandler.click(a);alert(tl("w_noSupportMp4"))},FileDialogInfo:function(a,b,c){Site.currentPage.isAlarm&&getMusicPath(a,b,c);Site.currentPage.is.encodeConfig&&Page.encodeConfig.Tab.path.setFilePath(a,
b,c);Site.currentPage.is.backupConfig&&Page.backupConfig._setConfigPath(a,b,c);Site.currentPage.is.logManageConfig&&Page.logManageConfig.Tab.logmanage._getLogBackFile(a,b,c)},OutPutStringInfo:function(a,b){if(Site.currentPage.is.videoDetectConfig)try{Page.videoDetectConfig.Tab.motionDetect.OutPutStringInfo(a,b)}catch(c){}Site.currentPage.is.ipcFacedectetionConfig&&$("ipc_face_glogal_tab").hasClass("ui-tab-current")&&a=="OutPutGlobalInfo"&&Page.ipcFacedectetionConfig.Tab.glogal.OutPutGlobalRect(b);
Site.currentPage.is.ipcFacedectetionConfig&&a=="OutPutFilterRect"&&$("ipc_face_para_tab").hasClass("ui-tab-current")&&Page.ipcFacedectetionConfig.Tab.para.setFilterValue(b);Site.currentPage.is.ipcFacedectetionConfig&&a=="OutPutModuleRect"&&$("ipc_face_para_tab").hasClass("ui-tab-current")&&Page.ipcFacedectetionConfig.Tab.para.OutPutModuleRect(b);Site.currentPage.is.ipcIntellentConfig&&a=="OutPutModuleRect"&&$("ipcintellent_para_tab").hasClass("ui-tab-current")&&Page.ipcIntellentConfig.Tab.para.OutPutModuleRect(b);
Site.currentPage.is.ipcIntellentConfig&&a=="OutPutGlobalCalibrateInfo"&&Page.ipcIntellentConfig.Tab.global.OutPutGlobalCalibrateInfo(b);Site.currentPage.is.ipcIntellentConfig&&a=="OutPutCheckedInfo"&&Page.ipcIntellentConfig.Tab.global.OutPutCheckedInfo(b);Site.currentPage.is.ipcIntellentConfig&&a=="OutPutFilterRect"&&($("ipcintellent_rule_tab").hasClass("ui-tab-current")&&Page.ipcIntellentConfig.Tab.rule.setFilterValue(b),$("ipcintellent_para_tab").hasClass("ui-tab-current")&&Page.ipcIntellentConfig.Tab.para.setFilterValue(b));
Site.currentPage.is.ipcIntellentConfig&&a=="OutPutRuleRect"&&$("ipcintellent_rule_tab").hasClass("ui-tab-current")&&Page.ipcIntellentConfig.Tab.rule.OutPutMinDetectRect(b);Site.currentPage.is.ipcIntellentConfig&&a=="OutPutShapeRect"&&$("ipcintellent_rule_tab").hasClass("ui-tab-current")&&Page.ipcIntellentConfig.Tab.rule.OutPutShapeRect(b);Site.currentPage.is.ipcFacedectetionConfig&&a=="OutPutCheckedInfo"&&Page.ipcFacedectetionConfig.Tab.para.setFilterValue(b);Site.currentPage.is.intellentConfig&&
a=="OutPutModuleRect"&&$("ivs_para_tab").hasClass("ui-tab-current")&&Page.intellentConfig.Tab.para.OutPutModuleRect(b);Site.currentPage.is.intellentConfig&&a=="OutPutRuleRect"&&Page.intellentConfig.Tab.rule.minGatherRegion(b);Site.currentPage.is.intellentConfig&&$("ivs_rule_tab").hasClass("ui-tab-current")&&a=="OutPutGlobalInfo"&&Page.intellentConfig.Tab.rule._OutPutGlobalRect(b);Site.currentPage.is.intellentConfig&&a=="OutPutFilterRect"&&($("ivs_rule_tab").hasClass("ui-tab-current")&&Page.intellentConfig.Tab.rule.setFilterValue(b),
$("ivs_para_tab").hasClass("ui-tab-current")&&Page.intellentConfig.Tab.para.setFilterValue(b));Site.currentPage.is.intellentConfig&&a=="OutPutGlobalLaneInfo"&&$("ivs_lane_tab").hasClass("ui-tab-current")&&Page.intellentConfig.Tab.lane.setFilterValue(b);Site.currentPage.is.intellentConfig&&a=="OutPutShapeRect"&&$("ivs_rule_tab").hasClass("ui-tab-current")&&Page.intellentConfig.Tab.rule.OutPutShapeRect(b);Site.currentPage.is.ipcIntellentNewConfig&&a=="OutPutShapeRect"&&Page.ipcIntellentNewConfig.Tab["public"].OutPutShapeRect(b);
Site.currentPage.is.ipcIntellentNewConfig&&a=="OutPutObjectRect"&&Page.ipcIntellentNewConfig.Tab["public"].setFilterValue(b);Site.currentPage.is.ipcIntellentNewConfig&&a=="OutPutGlobalCalibrateInfo"&&Page.ipcIntellentNewConfig.Tab.Global.OutPutGlobalCalibrateInfo(b);Site.currentPage.is.ipcIntellentNewConfig&&a=="OutPutCheckedInfo"&&Page.ipcIntellentNewConfig.Tab.Global.OutPutCheckedInfo(b);Site.currentPage.is.ipcIntellentNewConfig&&a=="OutPutRuleRect"&&Page.ipcIntellentNewConfig.Tab["public"].OutPutRuleRect(b);
Site.currentPage.is.intellentConfig&&a=="OutPutDFilter"&&Page.intellentConfig.Tab.scene.cameraMark.ocxInfo(b);Site.currentPage.isPreview&&a=="OutPutRuleRect"&&ManualEv.ocxBackStatusFlag(b);Site.currentPage.is.ipcIntellentCarConfig&&a=="OutPutShapeRect"&&Page.ipcIntellentCarConfig.Tab["public"].OutPutShapeRect(b);Site.currentPage.is.ipcIntellentCarConfig&&a=="OutPutObjectRect"&&Page.ipcIntellentCarConfig.Tab["public"].setFilterValue(b);Site.currentPage.is.ipcIntellTrafficConfig&&a=="OutPutRuleRect"&&
Page.ipcIntellTrafficConfig.Tab.scene._getDetectAreaInfo(b);Site.currentPage.is.ipcIntellTrafficConfig&&a=="DetectLine"&&Page.ipcIntellTrafficConfig.Tab.scene._getDetectLineInfo(b);Site.currentPage.is.ipcIntellTrafficConfig&&a=="OutPutFilterRect"&&Page.ipcIntellTrafficConfig.Tab.scene._getPlateFilterInfo(b);Site.currentPage.is.ipcFaceNewConfig&&a=="OutPutModuleRect"&&Page.ipcFaceNewConfig.OutPutModuleRect(b);Site.currentPage.is.ipcFaceNewConfig&&a=="OutPutObjectRect"&&Page.ipcFaceNewConfig.setFilterValue(b);
Site.currentPage.is.flowrateConfig&&a=="OutPutShapeRect"&&Page.flowrateConfig.Tab.setFlowrate.OutPutShapeRect(b);Site.currentPage.is.ipcIntellTrafficConfig&&a=="OutPutGlobalLaneInfo"&&Page.ipcIntellTrafficConfig.Tab.scene._getLanelineInfo(b)},VideoAnalyzeConfig:function(a){config=JSON.decode(a);if(Site.currentPage.is.encodeConfig&&$("video_OSD_tab").hasClass("ui-tab-current")&&$("osd_nav_privateMask").hasClass("osd-nav-item-current"))(a=config.EventParam.ShapeState)&&a==3&&Page.encodeConfig.Tab.OSD.PrivacyMask._ocxEventDone(config.EventParam.ShapeID)},
MousePtzEvent:function(a,b,c,d,e,f,g){if($("b_figure").hasClass("main-top-icon-figure-current"))OcxEventsHandler.VideoMouseEvent(a,b,c,d,e,f,g);else if($("b_rocker").hasClass("main-top-icon-rocker-current"))switch(b){case 0:VisualRocker.set_point_start(c,d);break;case 1:VisualRocker.mouse_up();break;case 2:VisualRocker.mouse_move(c,d);break;case 3:e>0?cptzd(!0,"ZoomTele",2,0,!0):cptzd(!0,"ZoomWide",2,0,!0)}g_isHasfisheye&&Site.currentPage.isPreview&&FishEye&&FishEye.isFisheyeOpen&&FishEye.onOcxMouseWheelEvent.apply(window,
arguments)},FisheyeParamsEx:function(a,b,c,d,e,f){if(FishEye&&FishEye.onFisheyeParamsEx)FishEye.onFisheyeParamsEx(a,b,c,d,e,f)},LocalFocus:function(a,b,c,d,e){a=getScreenOrder(b,c,d,e);currenDeviceType.contains("SD")?(new PtzCtrl).setRegionFocus(function(){},"InROIRegion",a):autoFocusConfig.getReginFocus(a)},FocusZoomStatus:function(a,b,c){if(g_Focusing&&(c=="AutoFocus"||g_beginFocus))(g_clickType=="longClick"||g_isZoom)&&autoFocusConfig.setZoomFocus(b*g_ZoomMotorSteps,a*g_FocusMotorSteps),c=="Normal"?
(g_Focusing=!1,g_focusState="Normal",g_beginFocus=!1,autoFocusConfig.disabledButton(!1)):g_beginFocus=!0;else if(Page.cameraConfig&&Page.cameraConfig.Tab.autoFocus._Focusing&&(c=="AutoFocus"||Page.cameraConfig.Tab.autoFocus._beginFocus))(Page.cameraConfig.Tab.autoFocus._clickType=="longClick"||Page.cameraConfig.Tab.autoFocus._isZoom)&&Page.cameraConfig.Tab.autoFocus._setZoomFocus(b*g_ZoomMotorSteps,a*g_FocusMotorSteps),c=="Normal"?(Page.cameraConfig.Tab.autoFocus._Focusing=!1,Page.cameraConfig.Tab.autoFocus._focusState=
"Normal",Page.cameraConfig.Tab.autoFocus._beginFocus=!1,Page.cameraConfig.Tab.autoFocus._disabledButton(!1)):Page.cameraConfig.Tab.autoFocus._beginFocus=!0},FeInstallMode:function(a){Site.currentPage.isPlayBack&&(a>0?PlayBack.FishEye.playbackHasFe(a):PlayBack.FishEye.closeFishEye())}};
function getScreenOrder(a,b,c,d){var e=Array(4);if(Browser.Platform.win){if(a==c)return null;else a>c?(e[0]=c,e[2]=a):(e[0]=a,e[2]=c);if(b==d)return null;else b>d?(e[1]=d,e[3]=b):(e[1]=b,e[3]=d)}if(Browser.Platform.mac){if(a==c)return null;else a>c?(e[0]=c,e[2]=a):(e[0]=a,e[2]=c);if(b==d)return null;else b>d?(e[1]=b,e[3]=d):(e[1]=d,e[3]=b)}return e}
function getEachHtml(a,b,c){var d=$("cmaincont");if(DEBUG)Page={},Cache={},d.innerHTML="";Cache[a]?showPage(a,"render"):(Cache[a]=!0,loadHtmlFile(b,function(b){var f=!1,g=document.createElement("div");g.id="wrap_page_"+a;g.className="wrap_page_config";g.style.display="none";g.innerHTML=b;d.appendChild(g);var h=document.createElement("script");h.setAttribute("type","text/javascript");h.setAttribute("src",c+"?version=2.210");d.appendChild(h);h.onreadystatechange=function(){["loaded","complete"].contains(h.readyState)&&
!f&&(f=!0,showPage(a))};h.onload=function(){f||(f=!0,showPage(a))}},function(){alert(tl("Getting configs fail!"));Cache[a]=!1},"2.400"))}
function showPage(a,b){b=b||"init";if(b==="init"&&(Page&&Page[a]&&Page[a].translate&&Page[a].translate(),Page[a].Tab))for(var c in Page[a].Tab)Page[a].Tab[c].translate&&Page[a].Tab[c].translate();$$(".wrap_page_config").setStyle("display","none");$("wrap_page_"+a).setStyle("display","block");if(Page&&Page[a]&&Page[a][b])Page[a][b]();$$(".ui-tab li.ui-tab-help a").setProperty("text",tl("w_helpCenter"))}function getHtml(a){getEachHtml(a,"../html/"+a+".htm","../js/"+a+".js")}
function getPlatformHtml(a){getEachHtml(a,"../platformHtm/"+a+".htm","../platformHtm/"+a+".js")}function getPreLanguage(){(new Request.JSON({async:!1,url:"/web_caps/preLanguage?version=2.400",onSuccess:function(a){Site.currentLanguage=a.PreLanguage}})).get();return Site.currentLanguage}
function getlang(a,b){Site.currentLanguage=a||getPreLanguage();Site.languages[Site.currentLanguage]?b&&b():(new Request.JSON({url:"/custom_lang/"+Site.currentLanguage+".txt?version=2.400",aysnc:!1,onSuccess:function(a){Site.languages[Site.currentLanguage]=a;b&&b()},onFailure:function(){(new Request.JSON({url:"/default_lang/"+Site.currentLanguage+".txt?version=2.400",async:!1,onSuccess:function(a){Site.languages[Site.currentLanguage]=a;b&&b()},onFailure:function(){(new Request.JSON({url:"../debug/"+
Site.currentLanguage+".txt?version=2.400",async:!1,onSuccess:function(a){Site.languages[Site.currentLanguage]=a;b&&b()}})).get()}})).get()}})).get();Cookie.write("DHLangCookie30",Site.currentLanguage,{duration:30,path:"/"})}getlang(null,function(){document.title=tl("w_Login");retranslate()});
function retranslate(){try{window.inilanguage&&inilanguage();window.PlayBack&&PlayBack.translate();window.PageSet&&PageSet.translate();for(var a in Page){Page[a].translate&&Page[a].translate();for(var b in Page[a].Tab)Page[a].Tab[b].translate&&Page[a].Tab[b].translate()}if(Site.currentPage.isSetup)document.title=tl("w_Setup"),$$("#set a.set-item-current").each(function(a){a=a.getProperty("data-filename");Page&&Page[a]&&Page[a].render&&Page[a].render()});$$("#ytszSelect option").each(function(a){var b=
a.getProperty("data-trans");a.setProperty("text",tl(b))});$$("#download_plugin a").set("text",tl("w_no_plugins"));$$("#nav a.main-nav-item-current").fireEvent("click");retranslateAlarmInfo()}catch(c){}}function retranslateAlarmInfo(){$("alarm_frame").contentWindow.$$&&$("alarm_frame").contentWindow.$$(".alarm-type-content").each(function(a){a.set("text",tl(a.get("data-content")))})}function tl(a){var b=Site.languages[Site.currentLanguage];return b&&(b[a]||b[a+" "]||"").trim()||a}
function getLocalPngHash(){(new Request({url:"/Custom/local.png?version=2.400",async:!1,onSuccess:function(a){a.split("\n").filter(function(a){a.trim()!=""&&a.test("=","i")&&(a=a.split("="),localPngHash.include(a[0].trim(),a[1].trim()))})}})).get()}function isEnable(a){return(a=localPngHash.get(a)-0)?a:!1}
function getWebCapsConfig(){(new Request.JSON({async:!1,url:"/web_caps/webCapsConfig?version=2.400&"+Date.now(),onSuccess:function(a){jsonWebCaps=a},onFailure:function(){jsonWebCaps={Anonymous:!1,deviceType:"IPC",mode:"IPC",vendor:" "}},onException:function(){}})).get();return jsonWebCaps}function getHostName(){var a=location.hostname;return/:/.test(a)?/\[|\]/.test(a)?a:"["+a+"]":a}
function getHttpPort(){var a=+location.port,b=window.webCaps||{};if(location.protocol==="http:")return a||80;var c=(window.webCaps||{}).HttpPort,a=80;if(c&&c.InnerPort)a=c.InnerPort;if(c&&c.OuterPort){var a=c.OuterPort,d="",e="";if(b.eth0)d=b.eth0.IPAddress;if(b.eth2)e=b.eth2.IPAddress;if(location.hostname==d||location.hostname==e)a=c.InnerPort}return a}
var getConfigR=function(){var a=new Hash;return function(b,c){var d=a.get(b);d==null?(new ConfigManager).getConfig(b,function(d){JSON.decode(d).result?(d=JSON.decode(d).params.table,a.include(b,d),c(d)):c(!1)},!1):c(d);return d}}(),COLOR=["#00FF00","#FFFF00","#FF0000","#0080C0","#000000"];
function createDiv(a,b,c){var d=(a[1]+a[2]/60+a[3]/3600)*22+1,e=(a[4]+a[5]/60+a[6]/3600)*22+1;if(Browser.ie9||Browser.ie10){var f=document.createElement("div");f.setAttribute("id","tstt"+b+"_"+c);a=d+"px";b=b*30+c*10+1+"px";d=(e-d>0?(e-d).ceil():0)+"px";f.setAttribute("style","height:9px;zIndex:10;position:absolute;border:0px solid #fff;overflow:hidden;width:"+d+"; top:"+b+";left:"+a+";background:"+COLOR[c]+";")}else f=new Element("div",{id:"tstt"+b+"_"+c,styles:{"z-index":10,background:COLOR[c],
height:"9px",position:"absolute",border:"0px solid #fff",overflow:"hidden"}}),d=(a[1]+a[2]/60+a[3]/3600)*22+1,e=(a[4]+a[5]/60+a[6]/3600)*22+1,f.style.left=d+"px",f.style.top=b*30+c*10+1+"px",f.style.width=(e-d>0?(e-d).ceil():0)+"px";return f}function chk10(a){var b=a-0;return a-0<10?"0"+(b-0):b}function intLimit(a){if(/[^\d]/g.test($(a).value))$(a).value=$(a).value.replace(/[^\d]/g,"")-0}
function attachLimit(a,b,c){a=$(a);a.removeEvents("keyup");a.removeEvents("blur");a.removeEvents("beforepaste");a.addEvents({keyup:function(){limitEx(this,c)},blur:function(){limit(this,c);limitMin(this,b)},beforepaste:function(){clipboardData.setData("text",clipboardData.getData("text").replace(/[^\d]/g,""))}})}
function attachPortLimit(a,b,c,d,e){d||(d=65535);for(var f=[1900,3800,5E3,5050,9999,37776,39999,42323],g=37780;g<=37880;g++)f.include(g);c!=void 0&&f.erase(c);$(a).addEvents({keyup:function(){limitEx(this,d)},blur:function(){this.value=this.value.replace(/[^\d]/g,"")-0;if(this.value-0>d+1)this.value=c==void 0?1025:c;if(!isNaN(this.value)&&this.value!=""){var a=this.value-0;if(a!=c&&(a<=1024||f.contains(a))){if(e&&a<=1024)this.value=e;$(b)?remarkDisplay(b,tl("Port in use!"),3E3,2):alert(tl("Port in use!"))}else if($(b))$(b).style.display=
"none"}else $(b)?remarkDisplay(b,tl("Numbers only!"),3E3,1):alert(tl("Numbers only!"))}})}function chkPort(a,b){for(var c=[1900,3800,5E3,5050,9999,37776,37777,37778,39999,42323],d=37780;d<=37880;d++)c.include(d);b!=void 0&&c.erase(b);return a-0==b||a-0>1024&&!c.contains(a-0)?!0:!1}
function attachMACInput(a){var b=[],b=$type(a)!="array"?[$(a+"0"),$(a+"1"),$(a+"2"),$(a+"3"),$(a+"4"),$(a+"5")]:[$(a[0]),$(a[1]),$(a[2]),$(a[3]),$(a[4]),$(a[5])],a=function(a){b[a]&&(b[a].removeEvents("keyup"),b[a].removeEvents("blur"),b[a].removeEvents("focus"),b[a].addEvents({keyup:function(d){d=d.code;this.value=this.value.replace(/[^0-9a-fA-F]/g,"");d==39?a<5&&b[a+1].select():d!=9&&(d==37?a>0&&a<6&&b[a-1].select():(this.value.length>=2&&a<5&&b[a+1].select(),this.value.length>=2&&a==5&&b[0].select()))},
blur:function(){if(this.value=="")this.value=0},focus:function(){this.select()}}))};a(0,b[0]);a(1,b[1]);a(2,b[2]);a(3,b[3]);a(4,b[4]);a(5,b[5])}
function attachIpInput(a){var b=[],b=$type(a)!="array"?[$(a+"0"),$(a+"1"),$(a+"2"),$(a+"3")]:[$(a[0]),$(a[1]),$(a[2]),$(a[3])],a=function(a,d){if(b[a]){var e=this.value;b[a].removeEvents("keyup");b[a].removeEvents("blur");b[a].removeEvents("focus");b[a].addEvents({keyup:function(f){f=f.code;if(f==110||f==190||f==39){if(this.value.length==1&&(f==110||f==190))this.value=e;a<3&&b[a+1].select()}else f!=9&&(f==37?a>0&&a<4&&b[a-1].select():(limitEx(this,d),this.value.length>=3&&a<3&&b[a+1].select(),this.value.length>=
3&&a==3&&b[0].select()))},blur:function(){limit(this,d);if(this.value=="")this.value=0;this.value-=0},focus:function(){e=this.value;this.select()}})}};a(0,255);a(1,255);a(2,255);a(3,255)}
function attachTimeEvent(a,b){b==void 0&&(b=!0);var c=[],c=$type(a)!="array"?[$(a+"0"),$(a+"1"),$(a+"2"),$(a+"3"),$(a+"4"),$(a+"5")]:[$(a[0]),$(a[1]),$(a[2]),$(a[3]),$(a[4]),$(a[5])],d=function(a,d){c[a]&&(c[a].removeEvents("keyup"),c[a].removeEvents("blur"),c[a].addEvents({keyup:function(b){if(/[^\d]/g.test(this.value))this.value=this.value.replace(/[^\d]/g,"");if(b.key=="right")a<5&&c[a+1].select();else if(b.code==37)a>0&&a<6&&c[a-1].select();else if(b.key!="tab"){if(this.value-0>d)this.value=d;
b=a>2?3:0;if(c[b].value=="24")c[b+1].value="00",c[b+2].value="00";this.value.length>=2&&a<5&&c[a+1].select()}},blur:function(){if(/[^\d]/g.test(this.value))this.value=this.value.replace(/[^\d]/g,"");if(this.value-0>d)this.value=d;this.value-0>=10?this.value-=0:this.value="0"+(this.value-0);var a=((c[0].value-0)*60+(c[1].value-0))*60+(c[2].value-0),e=((c[3].value-0)*60+(c[4].value-0))*60+(c[5].value-0);if(b&&a>e)c[3].value=c[0].value,c[4].value=c[1].value,c[5].value=c[2].value},focus:function(){this.select()}}))};
d(0,23);d(1,59);d(2,59);d(3,23);d(4,59);d(5,59)}function showPathOnly(a){a=$(a);a.style.imeMode="disabled";a.onpaste=function(){return!1};a.addEvent("keydown",function(a){a.code!=37&&a.code!=39&&a.preventDefault()})}
function getFrame(a,b){var c=a+"*"+b;return c=="704*576"||c=="704*480"?"D1":c=="352*576"||c=="352*480"?"HD1":c=="704*288"||c=="704*240"?"BCIF":c=="352*288"||c=="352*240"?"CIF":c=="176*144"||c=="176*120"?"QCIF":c=="640*480"?"VGA":c=="320*240"?"QVGA":c=="480*480"?"SVCD":c=="160*128"?"QQVGA":c=="800*592"?"SVGA":c=="1024*768"?"XVGA":c=="1280*800"?"WXGA":c=="1280*1024"?"SXGA":c=="1600*1024"?"WSXGA":c=="1600*1200"?"UXGA":c=="1920*1200"?"WUXGA":c=="240*192"?"ND1":c=="1280*720"?"720P":c=="1920*1080"?"1080P":
c=="1280*960"?"1.3M":c=="1872*1408"?"2.5M":c=="3744*1408"?"5M":c=="2560*1920"?"5_1M":c=="2048*1536"?"3M":c=="2560*1600"?"4M":c=="2048*2048"?"2048x2048":c=="2880*2160"?"2880x2160":c=="2880*2880"?"2880x2880":c=="3072*2048"?"3072x2048":c=="4096*2160"?"4096x2160":c=="3840*2160"?"3840x2160":c=="4000*3000"?"4000x3000":c=="3648*2736"?"3648x2736":a+"x"+b}
function getRorateFrame(a,b){var c=a+"*"+b;return c=="704*576"||c=="704*480"?"D1":c=="352*576"||c=="352*480"?"HD1":c=="704*288"||c=="704*240"?"BCIF":c=="352*288"||c=="352*240"?"CIF":c=="176*144"||c=="176*120"?"QCIF":c=="640*480"?"VGA":c=="320*240"?"QVGA":c=="480*480"?"SVCD":c=="160*128"?"QQVGA":c=="800*592"?"SVGA":c=="1024*768"?"XVGA":c=="1280*800"?"WXGA":c=="1280*1024"?"SXGA":c=="1600*1024"?"WSXGA":c=="1600*1200"?"UXGA":c=="1920*1200"?"WUXGA":c=="240*192"?"ND1":c=="1280*720"?"720P":c=="1920*1080"?
"1080P":c=="1280*960"?"1_3M":c=="1872*1408"?"2_5M":c=="3744*1408"?"5M":c=="2560*1920"?"5_1M":c=="2048*1536"?"3M":c=="2560*1600"?"4M":c=="2048*2048"?"2048x2048":c=="2880*2160"?"2880x2160":c=="2880*2880"?"2880x2880":c=="3072*2048"?"3072x2048":c=="4096*2160"?"4096x2160":c=="3840*2160"?"3840x2160":c=="4000*3000"?"4000x3000":a+"x"+b}
function getWidthH(a){var b=PAL_NTSC,c=["704*576","352*576","704*288","352*288","176*144","640*480","320*240","480*480","160*128","800*592","1024*768","1280*800","1280*1024","1600*1024","1600*1200","1920*1200","240*192","1280*720","1920*1080","1280*960","1872*1408","2560*1920","2048*1536","1216*1024","1408*1024","3296*2472","3744*1408","2560*1600","2048*2048","2880*2160","2880*2880","3072*2048","4096*2160","3840*2160","4000*3000","3648*2736"],d=["704*480","352*480","704*240","352*240","176*120","640*480",
"320*240","480*480","160*128","800*592","1024*768","1280*800","1280*1024","1600*1024","1600*1200","1920*1200","240*192","1280*720","1920*1080","1280*960","1872*1408","2560*1920","2048*1536","1216*1024","1408*1024","3296*2472","3744*1408","2560*1600","2048*2048","2880*2160","2880*2880","3072*2048","4096*2160","3840*2160","4000*3000","3648*2736"];a=="720P"&&(a="720");a=="1080P"&&(a="1080");a=="1_3M"&&(a="1.3M");a=="2_5M"&&(a="2.5M");var e=["D1","HD1","BCIF","CIF","QCIF","VGA","QVGA","SVCD","QQVGA",
"SVGA","XVGA","WXGA","SXGA","WSXGA","UXGA","WUXGA","ND1","720","1080","1.3M","2.5M","5_1M","3M","1_2M","1_5M","8M","5M","4M","2048x2048","2880x2160","2880x2880","3072x2048","4096x2160","3840x2160","4000x3000","3648x2736"].indexOf(a);return e<0?(a=a.split("x"),a[0]+"*"+a[1]):b=="PAL"?c[e]:d[e]}function checkPostResult(a){if(JSON.decode(a).result){a=JSON.decode(a).params;if($type(a)=="array")for(var b=0;b<a.length;b++)if(!a[b].result)return!1;return!0}else return!1}
function checkAll(a,b,c){for(var d=document.getElementById(a),c=document.getElementById(c).getElementsByTagName("input"),e=0,f=0,g=0;g<c.length;g++)if(c[g].type=="checkbox")d==b?c[g].checked=b.checked:c[g].checked&&c[g].id!=a&&f++,c[g].id!=a&&e++;if(d!=b)d.checked=e==f}function getSelect(a){if($(a).selectedIndex!=-1)return $(a).options[$(a).selectedIndex].text}
var remarkDisplay=function(){var a=[];return function(b,c,d,e){var f;$type(b)==="string"?f=$(b):(f=b,b=f.id);a[b]&&$clear(a[b]);var g;switch(e){case 0:g="success";break;case 1:g="error";break;case 2:g="warning"}f.removeClass("ui-tip-success").removeClass("ui-tip-warning").removeClass("ui-tip-error").addClass("ui-tip-"+g).setStyle("display","block").fade("in");$(b+"_label").setProperty("text",c);d&&(a[b]=function(){f&&f.fade("out")}.delay(d))}}();
function getMonthDays(a,b){function c(a){return a%100==0&&a%400==0||a%100!=0&&a%4==0?!0:!1}return b==4||b==6||b==9||b==11?30:b==2&&c(a)?29:b==2&&!c(a)?28:31}
function attachTimeInput(a){var b=[],b=[$(a+"0"),$(a+"1"),$(a+"2")],c=function(c,e){b[c]&&b[c].addEvents({keyup:function(f){chkTime(a,c,e,f);f.code==37&&(c==0&&obj[2]!=null?obj[2].select():c>0&&c<3&&b[c-1].select())},blur:function(){limit(this,e);this.value=this.value-0<10?"0"+(this.value-0):this.value},focus:function(){this.select()}})};a!=""&&(c(0,23),c(1,59),c(2,59))}
function attachDateInput(a,b){var c=[],d=[],c=[$(a+"0"),$(a+"1"),$(a+"2")],d=[$(b+"0"),$(b+"1"),$(b+"2")],e=function(b,e){c[b]&&c[b].addEvents({keyup:function(f){if(b==2){var i=getMonthDay(a);chkTime(a,b,i,f)}else chkTime(a,b,e,f);f.code==37?b>0&&b<3&&c[b-1].select():b==2&&d[0]!=null&&this.value.length>=2&&d[0].select()},blur:function(d){if(b==2){var e=getMonthDay(a);chkTime(a,b,e,d)}else c[b].value=c[b].value.replace(/[^\d]/g,"");checkDay(a)},focus:function(){this.select()}})},f=function(a,e){d[a]&&
d[a].addEvents({keyup:function(f){chkTime(b,a,e,f);f.code==37&&(a==0&&c[2]!=null?c[2].select():a>0&&a<3&&d[a-1].select())},blur:function(){limit(this,e);if(this.value=="")this.value="00";if(this.value.length==1)this.value="0"+this.value},focus:function(){this.select()}})};a!=""&&(e(0,2037),e(1,12),e(2,getMonthDay(a)));b!=""&&(f(0,23),f(1,59),f(2,59))}function clickElement(a){if(document.all)a.click();else{var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}
function openHelp(a){var b=1;currenDeviceType.contains("SD")&&(b=2);var c="";if(isDDNS())for(var c=getDDNSMessage(),d=c.resourcepath.split("_"),c="http://"+c.ddnshost+"/web",e=0;e<d.length;e++)c+="/"+d[e];window.open(Site.currentLanguage=="SimpChinese"?c+"/help/SimpChinese/"+a+"?device ="+b:c+"/help/English/"+a+"?device ="+b,"help"+rpcCore.sessionID,"width=601,height=500,menubar=no,status=no,toolbar=no,location=no,scrollbars=yes,resizable=no")}
function round1(a,b){var c=a%b;return c<b/2?a-c:a+b-c}function getReference(a,b,c,d,e,f){b<1&&(b=1);var b=b>149?50:b,g=(b+3-1)*a*cifPFrameMin;e=="H.264H"?g=(b+3-1)*a*2:e=="MJPG"&&(g=f?(b+3-1)*a*21:(b+3-1)*a*cifPFrameMin*3);e=g/b*c*d/101376;e>=4&&(e=round1(e,(1<<Math.log(e)/Math.log(2))/4));g=(b+3-1)*a*cifPFrameMax;a=g/b*c*d/101376;a>=4&&(a=round1(a,(1<<Math.log(a)/Math.log(2))/4));return[Math.round(e),Math.round(a)]}var spe_rebootDialog;
function isNeedReboot(a,b,c,d){var e=!1;if(JSON.decode(a).result){a=JSON.decode(a).params;if($type(a)=="array")for(var f=0;f<a.length;f++){if($type(a[f].params.options)=="array"&&(a[f].params.options.contains("NeedReboot")||a[f].params.options.contains("NeedRestart")))e=!0}else if($type(a.options)=="array"&&(a.options.contains("NeedReboot")||a.options.contains("NeedRestart")))e=!0;if(e){$("spe_isForNeedRbootId")&&$("spe_isForNeedRbootId").destroy();Browser.ie9||Browser.ie10?(e=document.createElement("div"),
e.setAttribute("id","spe_isForNeedRbootId")):e=new Element("div",{id:"spe_isForNeedRbootId"});document.body.appendChild(e);$("spe_isForNeedRbootId").innerHTML="";b='<div id="spe_showRebootDialog" class="ui-dialog"><div class="ui-dialog-title"><h1>title</h1><a class="ui-dialog-icon"></a></div><div class="ui-dialog-content fn-pad10"><div class="ui-autobox"><div class="ui-autobox-content"><i class="ui-dialog-surebox-icon"></i><span class="ui-dialog-surebox-text">'+tl(b)+'</span></div></div></div><div class="ui-button-box"><a id="spe_sureRebootButton" class="ui-button" href="javascript:;" style="display:none;">'+
tl("Ok")+'</a><a id="spe_cancelRebootButton" class="ui-button" href="javascript:;" style="display:none;">'+tl("w_Cancel")+"</a></div>";$("spe_isForNeedRbootId").innerHTML=b;spe_rebootDialog=new Dialog("spe_showRebootDialog",spe_IsNeedRebootFunc,"spe_sureRebootButton","spe_cancelRebootButton",tl("w_Reboot Device"));spe_rebootDialog.setPosition(400,200);try{$("m_ipcIntellent")&&$$("#m_ipcIntellent a")[0].hasClass("set-item-current")&&$("video1").setStyles({left:"-10000px",top:"-10000px"})}catch(g){}spe_rebootDialog.show();
if(d)$("spe_cancelRebootButton").style.display="inline-block";c?$("spe_sureRebootButton").style.display="inline-block":($("spe_cancelRebootButton").style.display="none",setTimeout("spe_IsNeedRebootFunc()",1E3))}}}
function spe_IsNeedRebootFunc(){$("spe_sureRebootButton").style.display=="inline-block"&&$("spe_isForNeedRbootId").destroy();(new MagicBox).reboot(function(){});window.setTimeout(function(){for(var a=location.href.split("/"),b="",c=0;c<a.length-1;c++)b+=a[c]+"/";location.replace(b)},1E4)}function nameImportLimt(a,b,c){a=$(a).value;$(b).setProperty("text","");/^[\w-]+$/.test(a)?$(b).setProperty("text",""):$(b).setProperty("text",tl(c))}
function nameImportLimtEx(a,b,c){a=$(a).value;$(b).setProperty("text","");/^[\w-.]+$/.test(a)?$(b).setProperty("text",""):$(b).setProperty("text",tl(c))}function NumberImportLimt(a,b,c){a=$(a).value;$(b).setProperty("text","");/^[\w-#*]+$/.test(a)?$(b).setProperty("text",""):$(b).setProperty("text",tl(c))}function promptImportLimt(a,b,c,d){a=$(a).value;$(b).setProperty("text","");expressionCheck(d,a)?$(b).setProperty("text",""):$(b).setProperty("text",tl(c))}
function checkedImportLimt(a,b){var c=$(a).value;return expressionCheck(b,c)}
function expressionCheck(a,b){var c=!0;switch(a){case 0:/^[\w-]+$/.test(b)||(c=!1);break;case 1:/^[\w-.]+$/.test(b)||(c=!1);break;case 2:/^[\w-#*]+$/.test(b)||(c=!1);break;case 3:if(/[\"]+/.test(b)||/[\']+/.test(b))c=!1;break;case 4:/[\"*<>?|\/]+/.test(b)&&(c=!1);break;case 5:if(/[\"]+/.test(b)||/[\']+/.test(b)||/[\u4E00-\u9FA5]+/.test(b))c=!1;break;case 6:if(/[\"]+/.test(b)||/[\']+/.test(b)||/[\u4E00-\u9FA5]+/.test(b)||/\s/.test(b))c=!1;break;case 7:/^[\w-.]+@[\w-]+(\.{1}[\w-]+)+$/.test(b)||(c=!1);
break;case 8:/^[\w]+$/.test(b)||(c=!1);break;case 9:/^[a-z0-9A-Z]*$/.test(b)||(c=!1);break;case 10:b!=""&&(/^[\w-\/]+$/.test(b)||(c=!1));break;case 11:b!=""&&(/^[\w-.]+$/.test(b)||(c=!1));break;case 12:b!=""&&(/^[\w]+$/.test(b)||(c=!1));break;case 13:if(/[\"]+/.test(b)||/[\']+/.test(b)||/[\u4E00-\u9FA5]+/.test(b)||/[\#]+/.test(b)||/[\\]+/.test(b))c=!1;break;case 14:/^[\w-\'\s]+$/.test(b)||(c=!1);break;case 15:/^[0-9]*$/.test(b)||(c=!1);break;case 16:/^[\u4E00-\u9FA5_a-zA-Z0-9]+$/.test(b)||(c=!1)}return c}
function estopPage(){var a=document.documentElement.clientHeight,b=document.documentElement.clientWidth,c=document.body.offsetHeight,a=c>a?c:a,c=document.getElementById("estopAll");c.style.height=a+"px";c.style.width=b+"px";c.style.display="block"}function cLength(a){return a.replace(/([0-9a-f]{1,4}:)|(:[0-9a-f]{1,4})/gi," ").length}
function isIPv4(a){a=$(a).value;return/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.test(a)&&(a=a.split("."),a[0]-0<=255&&a[1]-0<=255&&a[2]-0<=255&&a[3]-0<=255)?!0:!1}function isIPv6(a){return checkIPv6($(a).value)}
function checkIPv6(a){return(/^(([a-f\d]{1,4}:){7}([a-f\d]{1,4}){1})$/gi.test(a)||/^(([a-f\d]{1,4}:){1}(:[a-f\d]{1,4}){1,6})$/gi.test(a)||/^(([a-f\d]{1,4}:){2}(:[a-f\d]{1,4}){1,5})$/gi.test(a)||/^(([a-f\d]{1,4}:){3}(:[a-f\d]{1,4}){1,4})$/gi.test(a)||/^(([a-f\d]{1,4}:){4}(:[a-f\d]{1,4}){1,3})$/gi.test(a)||/^(([a-f\d]{1,4}:){5}(:[a-f\d]{1,4}){1,2})$/gi.test(a)||/^(([a-f\d]{1,4}:){6}(:[a-f\d]{1,4}){1})$/gi.test(a)||/^(:(:[a-f\d]{1,4}){1,7})$/gi.test(a)||/^(([a-f\d]{1,4}:){1,7}:)$/gi.test(a)||/^(::)$/g.test(a)||
/^(::([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(::ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(([0]{1,4}:){5}ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(([0]{1,4}:){0,3}([0]{1,4}){1}::ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(([0]{1,4}:){1}(:[0]{1,4}){1,3}:ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(([0]{1,4}:){2}(:[0]{1,4}){1,2}:ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(([0]{1,4}:){3}(:[0]{1,4}){1}:ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a)||/^(:(:[0]{1,4}){1,4}:ffff:([\d]{1,3}.){3}([\d]{1,3}){1})$/gi.test(a))&&
!(/^(::)$/g.test(a)||/^(:(:[0]{1,4}){1,7})$/g.test(a)||/^(([0]{1,4}:){7}([0]{1,4}){1})$/g.test(a)||/^(([0]{1,4}:){1}(:[0]{1,4}){1,6})$/g.test(a)||/^(([0]{1,4}:){2}(:[0]{1,4}){1,5})$/g.test(a)||/^(([0]{1,4}:){3}(:[0]{1,4}){1,4})$/g.test(a)||/^(([0]{1,4}:){4}(:[0]{1,4}){1,3})$/g.test(a)||/^(([0]{1,4}:){5}(:[0]{1,4}){1,2})$/g.test(a)||/^(([0]{1,4}:){6}(:[0]{1,4}){1})$/g.test(a)||/^(([0]{1,4}:){1,7}:)$/g.test(a)||/^((::[0]{0,3}1){1})$/g.test(a)||/^(:(:[0]{1,4}){1,6}(:[0]{0,3}1){1})$/g.test(a)||/^(([0]{1,4}:){7}([0]{0,3}1){1})$/g.test(a)||
/^(([0]{1,4}:){1}(:[0]{1,4}){0,5}(:[0]{0,3}1){1})$/g.test(a)||/^(([0]{1,4}:){2}(:[0]{1,4}){0,4}(:[0]{0,3}1){1})$/g.test(a)||/^(([0]{1,4}:){3}(:[0]{1,4}){0,3}(:[0]{0,3}1){1})$/g.test(a)||/^(([0]{1,4}:){4}(:[0]{1,4}){0,2}(:[0]{0,3}1){1})$/g.test(a)||/^(([0]{1,4}:){5}(:[0]{1,4}){0,1}(:[0]{0,3}1){1})$/g.test(a)||/^(([0]{1,4}:){6}(:[0]{1,4}){0}(:[0]{0,3}1){1})$/g.test(a)||/^((ff[a-f\d]{2}){1}(:[a-f\d]{1,4}){7})$/gi.test(a)||/^((ff[a-f\d]{2}:){1}(:[a-f\d]{1,4}){1,6})$/gi.test(a)||/^((ff[a-f\d]{2}:){1}([a-f\d]{1,4}:){1}(:[a-f\d]{1,4}){1,5})$/gi.test(a)||
/^((ff[a-f\d]{2}:){1}([a-f\d]{1,4}:){2}(:[a-f\d]{1,4}){1,4})$/gi.test(a)||/^((ff[a-f\d]{2}:){1}([a-f\d]{1,4}:){3}(:[a-f\d]{1,4}){1,3})$/gi.test(a)||/^((ff[a-f\d]{2}:){1}([a-f\d]{1,4}:){4}(:[a-f\d]{1,4}){1,2})$/gi.test(a)||/^((ff[a-f\d]{2}:){1}([a-f\d]{1,4}:){5}(:[a-f\d]{1,4}){1})$/gi.test(a)||/^((ff[a-f\d]{2}:){1}([a-f\d]{1,4}:){0,6}:)$/gi.test(a))}
var limitAttachPage={limiteTimely:function(a,b){var c=$(a),d;switch(b){case 0:d=/([^\w-.])+/;break;case 1:d=/([\'\"])+/;break;case 2:d=/[^\w-]/g;case 3:d=/[^0-9a-zA-Z]/g}c.removeEvents();c.addEvents({keyup:function(){var a=c.value.search(d);if(a!=-1)c.value=c.value.replace(d,""),limitAttachPage.setCaretPosition(c,a)},blur:function(){c.value=c.value.replace(d,"")}})},setCaretPosition:function(a,b){if(a.setSelectionRange)setTimeout(function(){a.setSelectionRange(b,b);a.focus()},0);else if(a.createTextRange){var c=
a.createTextRange();c.collapse(!0);c.moveStart("character",b);c.select()}},getCursortPosition:function(a){var b=0;if(document.selection)a.focus(),b=document.selection.createRange(),b.moveStart("character",-a.value.length),b=b.text.length;else if(a.selectionStart||a.selectionStart=="0")b=a.selectionStart;return b}},StringUtil={btSub:function(a,b,c,d){if(a===null||a==="")return"";var a=a.match(/(.{1})/g),e=[],f="",g=0;d&&(f=d);for(d=0;d<b;d++){if(a[g].replace(/[^\x00-\xff]/g,c).length>b-d)break;e.push(a[g]);
/^[\u0000-\u00ff]$/.test(a[g])||(c=="aa"?d++:d+=2);g++}return e.join("")+f},byteLength:function(a,b){return a.replace(/[^\x00-\xff]/g,b).length},substring:function(a,b,c){c=c==2?"aa":"aaa";return StringUtil.byteLength(a,c)>b?StringUtil.btSub(a,b,c):a}};function getDefaultRect(a,b,c,d){var e=a-c,a=e>0?c:a,c=b-d,b=c>0?d:b;return[a,b,a+Math.abs(e),b+Math.abs(c)]}
function overlayPlugins(a){var b=$(a).getCoordinates(),c=$("video1").getPosition();if($("video1").getStyle("top")==="0px"&&($("video1").setStyles({left:b.left-c.x,top:b.top-c.y,width:b.width,height:b.height,zIndex:"9999"}),b=$(a).getPosition(),c=$("video1").getPosition(),c.x!=b.x||c.y!=b.y)){var d=$("video1").getStyle("left").toInt(),e=$("video1").getStyle("top").toInt();$("video1").setStyles({left:d+b.x-c.x,top:e+b.y-c.y})}overlayPlugins.element=a}
var SliderEx=new Class({Extends:Slider,initialize:function(a,b,c){this.parent(a,b,c);var d,a={};switch(this.options.mode){case "vertical":d="height";break;case "horizontal":d="width"}this.half=this.half||this.knob.getStyle(d).toInt()/2;this.full=this.full||this.element.getStyle(d).toInt()-this.knob.getStyle(d).toInt()+this.options.offset*2;this.steps=this.options.steps||this.full;this.stepSize=Math.abs(this.range)/this.steps;this.stepWidth=this.stepSize*this.full/Math.abs(this.range);a[this.axis]=
[-this.options.offset,this.full-this.options.offset];this.drag.options.limit=a;if(this.options.snap)this.drag.options.grid=Math.ceil(this.stepWidth),this.drag.options.limit[this.axis][1]=this.full}}),FineSlider=new Class({sliderStep:1,initialize:function(a,b,c,d,e,f){this.element=$(a);var g=a.split("_");g.pop()&&g.push("label")&&(g=g.join("_"));var h=$(d)||$(g),d=a.split("_");d.pop()&&d.push("add")&&(d=d.join("_"));g=a.split("_");g.pop()&&g.push("reduce")&&(g=g.join("_"));this.addElement=$(e)||$(d);
this.reduceElement=$(f)||$(g);if(c.steps&&$type(c.range)=="array")this.sliderStep=Math.ceil((c.range[1]-c.range[0])/c.steps);if(!c.steps&&$type(c.range)=="array")c.steps=c.range[1]-c.range[0];if(!c.wheel)c.wheel=!0;if(!c.onChange)c.onChange=function(a){this.element.setProperty("title",a);h.setProperty("text",a)};this.slider=new SliderEx(a,b,c);this.steps=-1;this.addElement&&this.addElement.addEvent("click",this.add.bind(this));this.reduceElement&&this.reduceElement.addEvent("click",this.reduce.bind(this))},
add:function(){this.steps=this.element.getProperty("title")-0;this.steps>=this.slider.min&&this.steps<this.slider.max&&(this.steps+=this.sliderStep,this.slider.set(this.steps))},reduce:function(){this.steps=this.element.getProperty("title")-0;this.steps>this.slider.min&&this.steps<=this.slider.max&&(this.steps-=this.sliderStep,this.slider.set(this.steps))},set:function(a){a=a.limit(this.slider.min,this.slider.max);this.step=Math.round(a);this.slider.previousChange=this.step;this.slider.previousEnd=
this.step;this.slider.fireEvent("change",this.step);if(this.slider.step!==this.step)this.slider.step=this.step,this.slider.fireEvent("tick",this.slider.toPosition(this.step));return this}});function zeroPad(a,b){a+="";b=b||2;return a.length<b?zeroPad("0"+a,b):a}
(function(){function a(a){return d(parseInt(a).toString(16),2)}function b(a){var b=[],c=a.split("::");if(c.length==2){a=c[0].split(":");c=c[1].split(":");a.length===1&&a[0]===""&&(a=[]);c.length===1&&c[0]===""&&(c=[]);var d=8-(a.length+c.length);a.each(function(a){b.push(a)});d.each(function(){b.push(0)});c.each(function(a){b.push(a)})}else c.length==1&&(b=a.split(":"));return b}function c(a){return a.map(function(a){return d(a,4)}).join(":")}function d(a,b){var c="";(b-a.toString().length).each(function(){c+=
"0"});return c+a.toString()}var e=/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/g;this.v6ToCanonicalForm=function(d){var g=d.lastIndexOf(":"),h=d.slice(g+1);h.match(e)&&(h=h.split("."),h=a(h[0])+a(h[1])+":"+a(h[2])+a(h[3]),d=d.slice(0,g+1)+h);d=d.toLowerCase();g=b(d);return g.length==8?c(g):d}})();
function attachLimitCompare(a,b,c,d,e){var a=$(a),f=$(b);a.removeEvents("keyup");a.removeEvents("blur");a.addEvents({keyup:function(){limit(this,d)},blur:function(){limit(this,d);limitMin(this,c);if(e){if(this.value-0>f.value-0)this.value=f.value}else if(this.value-0<f.value-0)this.value=f.value}})}window.addEvent("domready",function(){document.addEvent("submit:relay(form)",function(a){if(!this.get("action"))return a.stop(),!1})});
function isEmptyRect(a){return $type(a)!=="array"?!0:a.length!==2?!0:$type(a[0])!=="array"?!0:$type(a[1])!=="array"?!0:a[0][0]||a[0][1]||a[1][0]||a[1][1]?!1:!0}(function(){window.pwdStrenthValidator=function(a){var b=a.length;return!/[^\d]/g.test(a)||!/[^a-zA-Z]/.test(a)||!/[a-zA-Z0-9]/.test(a)?b<=5?"weak":"middle":/\d/.test(a)&&/[a-zA-Z]/.test(a)&&/[^a-zA-Z0-9]/.test(a)?b>3?"strong":"middle":b<4?"weak":b<=8?"middle":"strong"}})();
