(function(){var i=Page.recordStorageConfig={Tab:[],init:function(){i.Tab.path.init();i.Tab.local.init();i.Tab.ftp.init();i.Tab.network.init();i.translate();i.bind();i.render()},translate:function(){$("rs_tab_title_path").set("text",tl("w_Storage Point"));$("rs_tab_title_local").set("text",tl("w_Local Storage"));$("rs_tab_title_ftp").set("text",tl("w_FTP"));$("rs_tab_title_network").set("text",tl("w_NAS"));$("rs_help").set("title",tl("w_help"))},render:function(){$$(".rs_tab_title.ui-tab-current").fireEvent("click")},
bind:function(){$$(".rs_tab_title").addEvent("click",i._onTabTitleClick);$("rs_help").addEvent("click",function(){openHelp("recordStorageConfig.htm")})},_onTabTitleClick:function(){var e=this.getProperty("data-for");i.Tab[e].render();$$(".rs_tab_title").removeClass("ui-tab-current");$$(".rs_tabs").setStyle("display","none");this.addClass("ui-tab-current");$("rs_tab_"+e).setStyle("display","block")}}})();
(function(){var i,e=[!1,!1,!1,!1,!1,!1,!1,!1,!1],b=[!1,!1,!1,!1,!1,!1,!1,!1,!1],f=!0,j=!1,g=Page.recordStorageConfig.Tab.path={init:function(){g.configManager=new ConfigManager;g.translate();g.bind();g._showAlarmInfo()},translate:function(){$$(".rs_tab_path_event_type").set("text",tl("w_Event Type"));$$(".rs_tab_path_event_type_timing").set("text",tl("w_Regular"));$$(".rs_tab_path_event_type_detect").set("text",tl("w_MD"));$$(".rs_tab_path_event_type_alarm").set("text",tl("w_Alarm"));$$(".rs_tab_path_locals").set("text",
tl("w_Local Storage"));$$(".rs_tab_path_ftp").set("text",tl("w_FTP"));$$(".rs_tab_path_remotes").set("text",tl("w_NAS"));$("rs_tab_path_video").set("text",tl("w_Record"));$("rs_tab_path_snap").set("text",tl("Capture Picture"));$("rs_tab_path_default").set("text",tl("w_DefaultConfig"));$("rs_tab_path_confirm").set("text",tl("w_Confirm"));$("rs_tab_path_refresh").set("text",tl("w_Refresh"))},render:function(){g._getConfigAndRenderElements()},bind:function(){$$("#page_recordStorageConfig input[id^=rs_record]").addEvent("click",
function(){g._onCheckBoxClick("record",this)});$$("#page_recordStorageConfig input[id^=rs_snapshot]").addEvent("click",function(){g._onCheckBoxClick("snapshot",this)});$("rs_tab_path_default").addEvent("click",g._onDefaultClick);$("rs_tab_path_confirm").addEvent("click",g._onConfirmClick);$("rs_tab_path_refresh").addEvent("click",g._onRefreshClick)},_showAlarmInfo:function(){1>ALARM_IN_NUMBER&&!hasSDCard?(j=!0,$$(".rs_tab_path_event_type_alarm").setStyle("display","none"),$$(".rs_tab_path_event_check_alarm").setStyle("display",
"none")):($$(".rs_tab_path_event_type_alarm").setStyle("display",""),$$(".rs_tab_path_event_check_alarm").setStyle("display",""));NASConfig&&$$(".rs_tab_path_remote_wrap").setStyle("display","");hasSDCard?$$(".rs_tab_path_local_wrap").setStyle("display",""):$$(".rs_tab_path_local_wrap").setStyle("display","none");for(var a=$$("#rs_tab_path_videotab table tr").filter(function(a){return a.style.display!="none"}),b=$$("#rs_tab_path_snaptab table tr").filter(function(a){return a.style.display!="none"}),
d=0;d<a.length;d++){var c=d%2?"":"ui-special-table-tr-odd";a[d].addClass(c);d==0&&a[0].addClass("record-table-head")}for(a=0;a<b.length;a++)c=a%2?"":"ui-special-table-tr-odd",b[a].addClass(c),a==0&&b[0].addClass("record-table-head")},_setVideoAndSnapShotArray:function(a){e[0]=a.TimingRecord.Local;e[3]=a.TimingRecord.FTP=!!a.TimingRecord.FTP;e[6]=a.TimingRecord.Remote;e[1]=a.VideoDetectRecord.Local;e[4]=a.VideoDetectRecord.FTP=!!a.VideoDetectRecord.FTP;e[7]=a.VideoDetectRecord.Remote;e[2]=a.AlarmRecord.Local;
e[5]=a.AlarmRecord.FTP=!!a.AlarmRecord.FTP;e[8]=a.AlarmRecord.Remote;b[0]=a.TimingSnapShot.Local;b[3]=a.TimingSnapShot.FTP=!!a.TimingSnapShot.FTP;b[6]=a.TimingSnapShot.Remote;b[1]=a.VideoDetectSnapShot.Local;b[4]=a.VideoDetectSnapShot.FTP=!!a.VideoDetectSnapShot.FTP;b[7]=a.VideoDetectSnapShot.Remote;b[2]=a.AlarmSnapShot.Local;b[5]=a.AlarmSnapShot.FTP=!!a.AlarmSnapShot.FTP;b[8]=a.AlarmSnapShot.Remote},_showRecordCheck:function(){for(var a=0;a<9;a++)$("rs_record_"+a).checked=e[a]},_showSnapShotCheck:function(){for(var a=
0;a<9;a++)$("rs_snapshot_"+a).checked=b[a]},_showSync:function(a){$("rs_tab_ftp_sync").checked=a.TimingRecord.AutoSync||a.VideoDetectRecord.AutoSync||a.AlarmRecord.AutoSync||a.TimingSnapShot.AutoSync||a.VideoDetectSnapShot.AutoSync||a.AlarmSnapShot.AutoSync;if(f)$("rs_tab_ftp_emergency").checked=a.TimingRecord.LocalForEmergency||a.VideoDetectRecord.LocalForEmergency||a.AlarmRecord.LocalForEmergency||a.TimingSnapShot.LocalForEmergency||a.VideoDetectSnapShot.LocalForEmergency||a.AlarmSnapShot.LocalForEmergency,
f=!1},_onCheckBoxClick:function(a,h){var d=h.id.replace(/[^\d]/g,"")-0,c,k;a==="record"?(c=e,k=b):(c=b,k=e);if(c[d]=h.checked)switch(d){case 0:case 1:case 2:if(c[3]||c[6])c[0]=!0;if(c[4]||c[7])c[1]=!0;if(c[5]||c[8])c[2]=!0;j&&(c[2]=!1,k[2]=!1);for(d=3;d<9;d++)c[d]=!1;break;case 3:case 4:case 5:if(c[0]||c[6])c[3]=!0;if(c[1]||c[7])c[4]=!0;if(c[2]||c[8])c[5]=!0;for(d=0;d<3;d++)c[d]=!1;for(d=6;d<9;d++)c[d]=!1;k[6]&&(k[3]=!0);k[7]&&(k[4]=!0);k[8]&&(k[5]=!0);j&&(c[5]=!1,k[5]=!1);for(d=6;d<9;d++)k[d]=!1;
break;case 6:case 7:case 8:if(c[0]||c[3])c[6]=!0;if(c[1]||c[4])c[7]=!0;if(c[2]||c[5])c[8]=!0;for(d=0;d<6;d++)c[d]=!1;k[3]&&(k[6]=!0);k[4]&&(k[7]=!0);k[5]&&(k[8]=!0);j&&(c[8]=!1,k[8]=!1);for(d=3;d<6;d++)k[d]=!1}g._showRecordCheck();g._showSnapShotCheck()},_onConfirmClick:function(){var a=i,h=$("rs_tab_ftp_emergency").checked,d=$("rs_tab_ftp_sync").checked;a.TimingRecord.Local=e[0];a.TimingRecord.FTP=e[3];a.TimingRecord.Remote=e[6];a.TimingRecord.LocalForEmergency=e[3]&&h;a.TimingRecord.AutoSync=e[3]&&
d;a.VideoDetectRecord.Local=e[1];a.VideoDetectRecord.FTP=e[4];a.VideoDetectRecord.Remote=e[7];a.VideoDetectRecord.LocalForEmergency=e[4]&&h;a.VideoDetectRecord.AutoSync=e[4]&&d;a.AlarmRecord.Local=e[2];a.AlarmRecord.FTP=e[5];a.AlarmRecord.Remote=e[8];a.AlarmRecord.LocalForEmergency=e[5]&&h;a.AlarmRecord.AutoSync=e[5]&&d;a.TimingSnapShot.Local=b[0];a.TimingSnapShot.FTP=b[3];a.TimingSnapShot.LocalForEmergency=b[3]&&h;a.TimingSnapShot.AutoSync=b[3]&&d;a.TimingSnapShot.Remote=b[6];a.VideoDetectSnapShot.Local=
b[1];a.VideoDetectSnapShot.FTP=b[4];a.VideoDetectSnapShot.LocalForEmergency=b[4]&&h;a.VideoDetectSnapShot.AutoSync=b[4]&&d;a.VideoDetectSnapShot.Remote=b[7];a.AlarmSnapShot.Local=b[2];a.AlarmSnapShot.FTP=b[5];a.AlarmSnapShot.LocalForEmergency=b[5]&&h;a.AlarmSnapShot.AutoSync=b[5]&&d;a.AlarmSnapShot.Remote=b[8];a.ManualRecord.Local=e[0]||e[1]||e[2];a.ManualRecord.LocalForEmergency=a.TimingRecord.LocalForEmergency||a.VideoDetectRecord.LocalForEmergency||a.AlarmRecord.LocalForEmergency;a.ManualRecord.AutoSync=
a.TimingRecord.AutoSync||a.VideoDetectRecord.AutoSync||a.AlarmRecord.AutoSync;a.ManualRecord.Remote=e[6]||e[7]||e[8]||e[3]||e[4]||e[5];a.EventRecord.Local=a.ManualRecord.Local;a.EventRecord.LocalForEmergency=a.ManualRecord.LocalForEmergency;a.EventRecord.AutoSync=a.ManualRecord.AutoSync;a.EventRecord.Remote=a.ManualRecord.Remote;a.ManualSnapShot.Local=b[0]||b[1]||b[2];a.ManualSnapShot.LocalForEmergency=a.TimingSnapShot.LocalForEmergency||a.VideoDetectSnapShot.LocalForEmergency||a.AlarmSnapShot.LocalForEmergency;
a.ManualSnapShot.AutoSync=a.TimingSnapShot.AutoSync||a.VideoDetectSnapShot.AutoSync||a.AlarmSnapShot.AutoSync;a.ManualSnapShot.Remote=b[6]||b[7]||b[8]||b[3]||b[4]||b[5];a.EventSnapShot.Local=a.ManualSnapShot.Local;a.EventSnapShot.LocalForEmergency=a.ManualSnapShot.LocalForEmergency;a.EventSnapShot.AutoSync=a.ManualSnapShot.AutoSync;a.EventSnapShot.Remote=a.ManualSnapShot.Remote;g.configManager.setConfig("RecordStoragePoint",[a],function(a){checkPostResult(a)?remarkDisplay("rs_tab_path_remark",tl("Succeed in saving configure"),
3E3,0):remarkDisplay("rs_tab_path_remark",tl("Saving failure"),3E3,1)});g.configManager.getConfig("NAS",function(c){var d,b;if(checkPostResult(c)){c=getTable(c);d=a.TimingRecord.FTP||a.VideoDetectRecord.FTP||a.AlarmRecord.FTP||a.TimingSnapShot.FTP||a.VideoDetectSnapShot.FTP||a.AlarmSnapShot.FTP;for(b=0;b<c.length;b++)if(c[b].Protocol!="FTP"&&d)c[b].Enable=!1;else if(c[b].Protocol=="FTP"&&!d)c[b].Enable=!1,$("rs_tab_ftp_enable").checked=!1,$("rs_tab_ftp_enable").disabled=!0,$("rs_tab_ftp_emergency").checked=
!1,$("rs_tab_ftp_emergency").disabled=!0;g.configManager.setConfig("NAS",c,$empty)}})},_onRefreshClick:function(){g._getConfigAndRenderElements(!0)},_onDefaultClick:function(){g.configManager.getDefault("RecordStoragePoint",function(a){checkPostResult(a)?(i=JSON.decode(a).params.table[0],g._setVideoAndSnapShotArray(i),g._showSync(i),g._showRecordCheck(),g._showSnapShotCheck(),remarkDisplay("rs_tab_path_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("rs_tab_path_remark",tl("Defaultfailure"),3E3,
1)})},_getConfigAndRenderElements:function(a){g.configManager.getConfig("RecordStoragePoint",function(b){checkPostResult(b)?(i=JSON.decode(b).params.table[0],g._setVideoAndSnapShotArray(i),g._showSync(i),g._showRecordCheck(),g._showSnapShotCheck(),a&&remarkDisplay("rs_tab_path_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("rs_tab_path_remark",tl("Operateingfailure"),3E3,1)})},getRecordStoragePoint:function(){return $unlink(i)}}})();
(function(){var i=[],e=[-1,-1],b=Page.recordStorageConfig.Tab.local={init:function(){hasSDCard?$("rs_tab_title_local").setStyle("display",""):$("rs_tab_title_local").setStyle("display","none");checkAuthority("MHardisk")?(b.storageDev=new StorageDev,b.formatDialog=new Dialog("rs_format_dialog",b._formatSDCard,"rs_format_confirm","rs_format_cancel",tl("w_Format")),b.formatDialog.setPosition(420,120),b.translate(),b.bind()):$("rs_tab_title_local").style.display="none"},translate:function(){$("rs_tab_local_name").set("text",
tl("w_DeviceName"));$("rs_tab_local_state").set("text",tl("w_State"));$("rs_tab_local_attribute").set("text",tl("w_Attribute"));$("rs_tab_local_space").set("text",tl("w_used_capacity")+"/"+tl("w_total_capacity"));$("rs_tab_local_read_only").set("text",tl("w_Set as read-only"));$("rs_tab_local_read_write").set("text",tl("w_Set as read-write"));$("rs_tab_local_hot_swap").set("text",tl("w_Hot pull and insert"));$("rs_tab_local_refresh").set("text",tl("w_Refresh"));$("rs_tab_local_format").set("text",
tl("w_Format"));$$("#rs_format_dialog .ui-dialog-title h1").set("text",tl("w_Format"));$("rs_format_confirm").set("text",tl("Ok"));$("rs_format_cancel").set("text",tl("Cancel"));$("rs_format_title").set("text",tl("w_cfmFormatReboot"))},render:function(f){b.formatDialog.close();e=[-1,-1];b.storageDev.getDeviceAllInfo(function(e,g){g.result?(f&&remarkDisplay("rs_tab_local_remark",tl("Operateingsuccess"),3E3,0),i=g.params,b._showDeviceList(f),b._addDeviceListEventLister(),$$("#rs_tab_local_device_0_0").fireEvent("click")):
(remarkDisplay("rs_tab_local_remark",tl("w_No SD Card"),3E3,2),$("rs_tab_local_device_list").innerHTML="")})},bind:function(){$("rs_tab_local_read_only").addEvent("click",b._onReadOnlyClick);$("rs_tab_local_read_write").addEvent("click",b._onReadWriteClick);$("rs_tab_local_hot_swap").addEvent("click",b._onHotSwapClick);$("rs_tab_local_refresh").addEvent("click",b._onRreshClick);$("rs_tab_local_format").addEvent("click",b._onFormatClick)},_showDeviceList:function(e){$("rs_tab_local_device_list").innerHTML=
"";var j='<table cellpadding="0" cellspacing="0" >';i.each(function(g,a){g.State==="Initializing"?(remarkDisplay("rs_tab_local_remark",tl("w_loadingSD"),6E3,2),b.render.delay(6E3,this,e)):(g.Detail||[]).each(function(b,d){if(b!==null){var c="width:"+(b.UsedBytes/b.TotalBytes).round(1)*100+"%;";j+='<tr id="rs_tab_local_device_'+a+"_"+d+'" class="trClass">';j+='<td class="fn-widp20">'+tl("w_localDisk")+(a+1)+"</td>";j+='<td class="fn-widp15">'+(b.IsError?tl("w_diskError"):tl("w_Status_ok"))+"</td>";
j+='<td class="fn-widp15">'+tl(b.Type)+"</td>";j+='<td>                                        <div class="ui-autobox fn-height20"><div class="ui-autobox-content"><div class="recordstorage-progress">                                            <p class="recordstorage-progress-used" style="'+c+'"></p>                                        </div><div class="fn-left fn-minwid150 fn-textleft">'+(b.UsedBytes/1048576).round(1)+"M/"+(b.TotalBytes/1048576).round(1)+"M                                    </div></div></div></td>";
j+="</tr>"}})});j+="</table>";$("rs_tab_local_device_list").innerHTML=j;$$("#rs_tab_local_device_list tr").removeClass("ui-table-tr-current");$$("#rs_tab_local_device_list tr:first-child").addClass("ui-table-tr-current")},_addDeviceListEventLister:function(){$$("#rs_tab_local_device_list tr").addEvent("click",function(){e=this.id.replace(/[^\d]*/,"").split("_");$$("#rs_tab_local_device_list tr").removeClass("ui-table-tr-current");this.addClass("ui-table-tr-current")})},_onRreshClick:function(){b.render(!0)},
_onReadOnlyClick:function(){b._setType("ReadOnly")},_onReadWriteClick:function(){b._setType("ReadWrite")},_setType:function(f){var j;e[0]===-1||e[1]===-1?remarkDisplay("rs_tab_local_remark",tl("w_select"),3E3,2):(j=i[e[0]].Detail[e[1]].Pointer,j==0?remarkDisplay("rs_tab_local_remark",tl("Operateingfailure"),3E3,1):(b.storageDev.setType(j,f)?remarkDisplay("rs_tab_local_remark",tl("Operateingsuccess"),3E3,0):remarkDisplay("rs_tab_local_remark",tl("Operateingfailure"),3E3,1),b.render()))},_onHotSwapClick:function(){var f;
e[0]===-1||e[1]===-1?remarkDisplay("rs_tab_local_remark",tl("w_select"),3E3,2):(f=i[e[0]].Pointer,f==0?remarkDisplay("rs_tab_local_remark",tl("Operateingfailure"),3E3,1):(b.storageDev.eject(f)?remarkDisplay("rs_tab_local_remark",tl("Operateingsuccess"),3E3,0):remarkDisplay("rs_tab_local_remark",tl("Operateingfailure"),3E3,1),b.render()))},_onFormatClick:function(){e[0]===-1||e[1]===-1?remarkDisplay("rs_tab_local_remark",tl("w_select"),3E3,2):b.formatDialog.show()},_formatSDCard:function(){var f=i[e[0]].Pointer;
b.formatDialog.close();f===0?remarkDisplay("rs_tab_local_remark",tl("Operateingfailure"),3E3,1):(b.storageDev.formatPatition(f,e[1])?(remarkDisplay("rs_tab_local_remark",tl("Operateingsuccess"),3E3,0),isNeedReboot('{"result":true,"params":{"options":["NeedReboot"]}}',"w_format SD Restart device",!1,!1)):(remarkDisplay("rs_tab_local_remark",tl("Operateingfailure"),3E3,1),isNeedReboot('{"result":true,"params":{"options":["NeedReboot"]}}',"w_needReboot",!1,!1)),b.render())}}})();
(function(){var i,e,b,f,j=["%00","1","10.61.2.129","\u5357\u5411\u5317","2","50","180","\u95ef\u7ea2\u706f","1","\u6d59APJ896","\u5c0f\u578b\u6c7d\u8f66(\u84dd\u5e95\u767d\u5b57)","\u5c0f\u578b\u8f66","\u9ec4\u8272","3","2","10.61.2.128","\u84dd\u8272","19_45_29_59","1547aref","***\u8def","***\u516c\u53f8","\u5168\u666f","PZC2AW01800060","1","3","30S","\u5de6\u8f6c"],g=["2013","01","06","15","27","30","110"],a=!1,h=Page.recordStorageConfig.Tab.ftp={init:function(){h.configManager=new ConfigManager;
h.translate();h.bind();if(!hasSDCard)$("rs_tab_ftp_emergency_wrap").style.display="none";if(support_scenes.contains("Traffic")&&/^SD/.test(currenDeviceType))a=!0,h.dialogNameHelp=new Dialog("store_ftp_J_PictureHelp",function(){h._offFtpNameHelp()},"storeFtpDialogConfirm","storeFtpDialogClose",tl("w_nameHelp")),h.dialogNameHelp.setPosition(680,0),$("TrafficFtp").removeClass("fn-hide")},translate:function(){$("rs_tab_ftp_enable_label").set("text",tl("w_Setup FTP"));$("rs_tab_ftp_address_label").set("text",
tl("w_Server Address"));$("rs_tab_ftp_port_label").set("text",tl("w_Port"));$("rs_tab_ftp_username_label").set("text",tl("w_User"));$("rs_tab_ftp_password_label").set("text",tl("w_password"));$("rs_tab_ftp_directory_label").set("text",tl("w_Remote directory"));$("rs_tab_ftp_emergency_label").set("text",tl("w_Exigency Storage(Local)"));$("rs_tab_ftp_sync_label").set("text",tl("w_Syn Data"));$("rs_tab_ftp_default").set("text",tl("w_DefaultConfig"));$("rs_tab_ftp_refresh").set("text",tl("w_Refresh"));
$("rs_tab_ftp_confirm").set("text",tl("w_Confirm"));$("mFtp_tab_ftp_name_reset").set("text",tl("w_Reset"));$("mFtp_tab_ftp_davname_reset").set("text",tl("w_Reset"));$("mFtp_tab_ftp_name_help").set("text",tl("w_help"));$("mFtp_tab_ftp_davname_help").set("text",tl("w_help"));$$("#page_recordStorageConfig h2[data-trans]").each(function(a){var c=a.getProperty("data-trans");a.set("text",tl(c))});$$("#page_recordStorageConfig p[data-trans]").each(function(a){var c=a.getProperty("data-trans");a.set("text",
tl(c))});$$("#page_recordStorageConfig span[data-trans]").each(function(a){var c=a.getProperty("data-trans");a.set("text",tl(c))})},render:function(){$("rs_tab_ftp_username_tip").setProperty("text","");$("rs_tab_ftp_password_tip").setProperty("text","");$("rs_tab_ftp_directory_tip").setProperty("text","");$("rs_tab_ftp_address_tip").setProperty("text","");h._getConfigAndRenderElements();support_scenes.contains("Traffic")&&/^SD/.test(currenDeviceType)&&h.dialogNameHelp.close()},bind:function(){$("rs_tab_ftp_enable").addEvent("click",
h._onEnableClick);$("rs_tab_ftp_default").addEvent("click",h._onDefaultClick);$("rs_tab_ftp_refresh").addEvent("click",h._onRefreshClick);$("rs_tab_ftp_confirm").addEvent("click",h._onConfirmClick);attachLimit("rs_tab_ftp_port",0,65535);$("rs_tab_ftp_directory").addEvent("keyup",function(){promptImportLimt("rs_tab_ftp_directory","rs_tab_ftp_directory_tip","w_pathError",10)});$$("#rs_tab_ftp_username, #rs_tab_ftp_password").addEvent("keyup",function(){promptImportLimt(this.id,this.id+"_tip","w_noInputMarks",
3)});$("rs_tab_ftp_address").addEvent("keyup",function(){promptImportLimt("rs_tab_ftp_address","rs_tab_ftp_address_tip","w_emailiperror",11)});$("mFtp_tab_ftp_name_reset").addEvent("click",function(){h._onFtpNameDefault("pic")});$("mFtp_tab_ftp_davname_reset").addEvent("click",function(){h._onFtpNameDefault("dav")});$("mFtp_tab_ftp_name_help").addEvent("click",h._onFtpNameHelp);$("mFtp_tab_ftp_davname_help").addEvent("click",h._onFtpNameHelp);showPathOnly("mFtp_tab_ftp_name_content1");$("mFtp_tab_ftp_name_content").addEvents({keyup:function(){if(this.value.test(/[\"*:<>?|\\]+/))this.value=
this.value.replace(/[\"*:<>?|\\]+/,"");if(this.value.length>300)this.value=this.value.slice(0,300);h._ftpNameFormatPreview("pic")},blur:function(){if(this.value=="")this.value=f.NamingFormat.Format;if(this.value.length>300)this.value=this.value.slice(0,300);h._ftpNameFormatPreview("pic")}});showPathOnly("mFtp_tab_ftp_davname_content1");$("mFtp_tab_ftp_davname_content").addEvents({keyup:function(){if(this.value.test(/[\"*:<>?|\\]+/))this.value=this.value.replace(/[\"*:<>?|\\]+/,"");if(this.value.length>
300)this.value=this.value.slice(0,300);h._ftpNameFormatPreview("dav")},blur:function(){if(this.value=="")this.value=f.VideoNamingFormat.Format;if(this.value.length>300)this.value=this.value.slice(0,300);h._ftpNameFormatPreview("dav")}})},_ftpNameFormatPreview:function(a){for(var c="",c=a=="pic"?$("mFtp_tab_ftp_name_content").value:$("mFtp_tab_ftp_davname_content").value,b="",e="",g=c.length,f=0;f<g;f++)if(f+2<g&&c.charAt(f)=="%"&&/[0-9]/g.test(c.charAt(f+1))&&/[0-9]/g.test(c.charAt(f+2)))c.charAt(f+
1)!=0&&(e+=c.charAt(f+1)),e+=c.charAt(f+2),e<27&&e>0?b+=j[e]:(b+=c.charAt(f),b+=c.charAt(f+1),b+=c.charAt(f+2)),e="",f+=2;else if(f+1<g&&c.charAt(f)=="%"&&/[a-zA-Z]/g.test(c.charAt(f+1))){var i=h._timedatavalue(c.charAt(f+1));i?b+=i:c.charAt(f+1)=="c"?b+="1":(b+=c.charAt(f),b+=c.charAt(f+1));f++}else f+1<g&&c.charAt(f)=="%"&&c.charAt(f+1)=="%"?(b+=c.charAt(f),f++):b+=c.charAt(f);a=="pic"?$("mFtp_tab_ftp_name_content1").value=b:$("mFtp_tab_ftp_davname_content1").value=b},_onFtpNameHelp:function(){h.dialogNameHelp.show()},
_offFtpNameHelp:function(){h.dialogNameHelp.close()},_onFtpNameDefault:function(a){h.configManager.getDefault("TrafficGlobal",function(c,b){b.result?(a=="pic"?f.NamingFormat=b.params.table.NamingFormat:f.VideoNamingFormat=b.params.table.VideoNamingFormat,h._renderTraffic()):remarkDisplay("rs_tab_ftp_remark",tl("Operateingfailure"),3E3,1)})},_timedatavalue:function(a){var c=0;switch(a){case "y":c=g[0];break;case "M":c=g[1];break;case "d":c=g[2];break;case "h":c=g[3];break;case "m":c=g[4];break;case "s":c=
g[5];break;case "S":c=g[6]}return c},_checkFtpName:function(){var a=f.NamingFormat.Format.length,c=f.NamingFormat.Format;if(c.charAt(a-4)!="."||c.charAt(a-3)!="j"||c.charAt(a-2)!="p"||c.charAt(a-1)!="g")return alert(tl("tip.Picture named jpg")),remarkDisplay("rs_tab_ftp_remark",tl("Saving failure"),3E3,1),!0;var c=f.VideoNamingFormat.Format,b=c.length,a=c.charAt(b-4)=="."&&c.charAt(b-3)=="d"&&c.charAt(b-2)=="a"&&c.charAt(b-1)=="v",c=c.charAt(b-4)=="."&&c.charAt(b-3)=="a"&&c.charAt(b-2)=="v"&&c.charAt(b-
1)=="i";return!a&&!c?(alert(tl("tip.video named dav")),remarkDisplay("rs_tab_ftp_remark",tl("Saving failure"),3E3,1),!0):!1},_renderTraffic:function(){$("mFtp_tab_ftp_name_content").value=f.NamingFormat.Format;$("mFtp_tab_ftp_davname_content").value=f.VideoNamingFormat.Format;h._ftpNameFormatPreview("pic");h._ftpNameFormatPreview("dav")},_renderElements:function(a,c){c=c||Page.recordStorageConfig.Tab.path.getRecordStoragePoint();c.TimingRecord.FTP||c.VideoDetectRecord.FTP||c.AlarmRecord.FTP||c.TimingSnapShot.FTP||
c.VideoDetectSnapShot.FTP||c.AlarmSnapShot.FTP?($("rs_tab_ftp_enable").disabled=!1,$("rs_tab_ftp_emergency").disabled=!1,$("rs_tab_ftp_sync").disabled=!1):(a.Enable=!1,$("rs_tab_ftp_enable").disabled=!0,$("rs_tab_ftp_emergency").checked=!1,$("rs_tab_ftp_emergency").disabled=!0,$("rs_tab_ftp_sync").checked=!1,$("rs_tab_ftp_sync").disabled=!0);$("rs_tab_ftp_enable").checked=a.Enable;$("rs_tab_ftp_port").value=a.Port;$("rs_tab_ftp_username").value=a.UserName;$("rs_tab_ftp_password").value=a.Password;
$("rs_tab_ftp_directory").value=a.Directory;$("rs_tab_ftp_emergency").checked=c.TimingRecord.LocalForEmergency||c.VideoDetectRecord.LocalForEmergency||c.AlarmRecord.LocalForEmergency||c.TimingSnapShot.LocalForEmergency||c.VideoDetectSnapShot.LocalForEmergency||c.AlarmSnapShot.LocalForEmergency;h._onEnableClick();$("rs_tab_ftp_address").value=a.Address;$$("#rs_tab_ftp .ui-tip-red").set("text","")},_onEnableClick:function(){$("rs_tab_ftp_enable").checked?$("rs_tab_ftp_emergency").disabled=!1:($("rs_tab_ftp_emergency").disabled=
!0,$("rs_tab_ftp_emergency").checked=!1)},_onDefaultClick:function(){$("rs_tab_ftp_username_tip").setProperty("text","");$("rs_tab_ftp_password_tip").setProperty("text","");$("rs_tab_ftp_directory_tip").setProperty("text","");$("rs_tab_ftp_address_tip").setProperty("text","");h.configManager.getDefault("NAS",function(a){var c;checkPostResult(a)?(a=getTable(a),a.each(function(a){a.Protocol==="FTP"&&(c=a)}),h._renderElements(c,b),remarkDisplay("rs_tab_ftp_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("rs_tab_ftp_remark",
tl("Defaultfailure"),3E3,1)})},_onRefreshClick:function(){$("rs_tab_ftp_username_tip").setProperty("text","");$("rs_tab_ftp_password_tip").setProperty("text","");$("rs_tab_ftp_directory_tip").setProperty("text","");$("rs_tab_ftp_address_tip").setProperty("text","");h._getConfigAndRenderElements(!0)},_onConfirmClick:function(){var d=b,c=$("rs_tab_ftp_emergency").checked;if(h._validateBeforSubmit()){e.Enable=$("rs_tab_ftp_enable").checked;e.Port=$("rs_tab_ftp_port").value-0;e.UserName=$("rs_tab_ftp_username").value;
e.Password=$("rs_tab_ftp_password").value;e.Directory=$("rs_tab_ftp_directory").value;e.Address=$("rs_tab_ftp_address").value;d.TimingRecord.AutoSync=$("rs_tab_ftp_sync").checked;d.TimingRecord.LocalForEmergency=d.TimingRecord.FTP&&c;d.VideoDetectRecord.LocalForEmergency=d.VideoDetectRecord.FTP&&c;d.AlarmRecord.LocalForEmergency=d.AlarmRecord.FTP&&c;d.TimingSnapShot.LocalForEmergency=d.TimingSnapShot.FTP&&c;d.VideoDetectSnapShot.LocalForEmergency=d.VideoDetectSnapShot.FTP&&c;d.AlarmSnapShot.LocalForEmergency=
d.AlarmSnapShot.FTP&&c;d.ManualRecord.LocalForEmergency=d.TimingRecord.LocalForEmergency||d.VideoDetectRecord.LocalForEmergency||d.AlarmRecord.LocalForEmergency;d.EventRecord.LocalForEmergency=d.ManualRecord.LocalForEmergency;d.ManualSnapShot.LocalForEmergency=d.TimingSnapShot.LocalForEmergency||d.VideoDetectSnapShot.LocalForEmergency||d.AlarmSnapShot.LocalForEmergency;d.EventSnapShot.LocalForEmergency=d.ManualSnapShot.LocalForEmergency;c=["NAS","RecordStoragePoint"];d=[i,[d]];if(a&&(c.push("TrafficGlobal"),
d.push(f),f.NamingFormat&&(f.NamingFormat.Format=$("mFtp_tab_ftp_name_content").value),f.VideoNamingFormat&&(f.VideoNamingFormat.Format=$("mFtp_tab_ftp_davname_content").value),h._checkFtpName()))return;h.configManager.setConfig(c,d,function(a){checkPostResult(a)?remarkDisplay("rs_tab_ftp_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("rs_tab_ftp_remark",tl("Saving failure"),3E3,1)})}},_getConfigAndRenderElements:function(d){var c=["NAS","RecordStoragePoint"];a&&c.push("TrafficGlobal");
h.configManager.getConfig(c,function(c,g){if(checkPostResult(c)){i=g.params[0].params.table;e=i.filter(function(a){return a.Protocol==="FTP"})[0];b=g.params[1].params.table[0];if(a){g.params[2].params&&(f=g.params[2].params.table);if(f){if(!f.NamingFormat)f.NamingFormat={Format:"\u914d\u7f6e\u83b7\u53d6\u5f02\u5e38/%c/%07/%y/%M/%d/%h/%04-%y%M%d%h%m%s%S-%07-%18-(%14).jpg"};if(!f.VideoNamingFormat)f.VideoNamingFormat={Format:"\u914d\u7f6e\u83b7\u53d6\u5f02\u5e38/%c/%07/%y/%M/%d/%h/%04-%y%M%d%h%m%s%S-%07-%18-(%14).dav"}}else f=
{NamingFormat:{Format:"\u914d\u7f6e\u83b7\u53d6\u5f02\u5e38/%c/%07/%y/%M/%d/%h/%04-%y%M%d%h%m%s%S-%07-%18-(%14).jpg"},VideoNamingFormat:{Format:"\u914d\u7f6e\u83b7\u53d6\u5f02\u5e38/%c/%07/%y/%M/%d/%h/%04-%y%M%d%h%m%s%S-%07-%18-(%14).dav"}};h._renderTraffic()}h._renderElements(e,b);d&&remarkDisplay("rs_tab_ftp_remark",tl("Operateingsuccess"),3E3,0)}else remarkDisplay("rs_tab_ftp_remark",tl("Operateingfailure"),3E3,1)})},_validateBeforSubmit:function(){if(!checkedImportLimt("rs_tab_ftp_username",3))return remarkDisplay("rs_tab_ftp_remark",
tl("w_noInputMarks"),3E3,1),!1;if(!checkedImportLimt("rs_tab_ftp_password",3))return remarkDisplay("rs_tab_ftp_remark",tl("w_noInputMarks"),3E3,1),!1;if(!checkedImportLimt("rs_tab_ftp_directory",10))if($("rs_tab_ftp_directory").value!="")return remarkDisplay("rs_tab_ftp_remark",tl("w_pathError"),3E3,1),!1;else $("rs_tab_ftp_directory_tip").setProperty("text","");return $("rs_tab_ftp_address").value.length>0&&!checkedImportLimt("rs_tab_ftp_address",11)?(remarkDisplay("rs_tab_ftp_remark",tl("w_emailiperror"),
3E3,1),!1):!0}}})();
(function(){var i,e,b,f,j,g=Page.recordStorageConfig.Tab.network={init:function(){if(NASConfig)$("rs_tab_title_network").setStyle("display",""),g.configManager=new ConfigManager,g._initProtocol(),g.translate(),g.bind()},translate:function(){$("rs_tab_network_enable_label").set("text",tl("w_Setup NAS"));$("rs_tab_network_address_label").set("text",tl("w_Server Address"));$("rs_tab_network_port_label").set("text",tl("w_Port"));$("rs_tab_network_username_label").set("text",tl("w_User"));$("rs_tab_network_password_label").set("text",
tl("w_password"));$("rs_tab_network_directory_label").set("text",tl("w_Remote directory"));$("rs_tab_network_defualt").set("text",tl("w_DefaultConfig"));$("rs_tab_network_refresh").set("text",tl("w_Refresh"));$("rs_tab_network_confirm").set("text",tl("w_Confirm"))},_initProtocol:function(){var a=(localPngHash.NAS_Protocol_Mask||"").toString(2);$("rs_tab_network_Protocol").empty();a&4&&$("rs_tab_network_Protocol").options.add(new Option("NFS","NFS"));a&2&&$("rs_tab_network_Protocol").options.add(new Option("ISCSI",
"ISCSI"));a&1&&$("rs_tab_network_Protocol").options.add(new Option("SMB","SMB"))},render:function(){g._getConfigAndRenderElements()},bind:function(){$("rs_tab_network_defualt").addEvent("click",g._onDefaultClick);$("rs_tab_network_refresh").addEvent("click",g._onRefreshClick);$("rs_tab_network_confirm").addEvent("click",g._onConfirmClick);$("rs_tab_network_Protocol").addEvent("change",function(){g._validateBeforSubmit()?(g._saveTempJson(),f=this.value,b=i.filter(function(a){return a.Protocol===f})[0],
g._renderElements(b,e)):this.value=f});attachLimit("rs_tab_network_port",0,65535);$$("#rs_tab_network_username, #rs_tab_network_password").addEvent("keyup",function(){promptImportLimt(this.id,this.id+"_tip","w_noInputMarks",3)});$("rs_tab_network_address").addEvent("keyup",function(){promptImportLimt("rs_tab_network_address","rs_tab_network_address_tip","w_emailiperror",11)});$("rs_tab_network_directory").addEvents({keyup:function(){StringUtil.byteLength(this.value,"aaa")>200?$(this.id+"_tip").setProperty("text",
tl("w_pathLong")):$(this.id+"_tip").setProperty("text","");this.value&&(/^[\w-.\/]+$/.test(this.value)?$(this.id+"_tip").setProperty("text",""):$(this.id+"_tip").setProperty("text",tl("w_pathErrorWithPoint")))},blur:function(){StringUtil.byteLength(this.value,"aaa")>200?$(this.id+"_tip").setProperty("text",tl("w_pathLong")):$(this.id+"_tip").setProperty("text","");this.value&&(/^[\w-.\/]+$/.test(this.value)?$(this.id+"_tip").setProperty("text",""):$(this.id+"_tip").setProperty("text",tl("w_pathErrorWithPoint")))}})},
_getConfigAndRenderElements:function(a){g.configManager.getConfig(["NAS","RecordStoragePoint"],function(h,d){checkPostResult(h)?(f=$("rs_tab_network_Protocol").value,i=d.params[0].params.table,b=i.filter(function(a){return a.Protocol===f})[0],e=d.params[1].params.table[0],g._renderElements(b,e),j=$unlink(i),a&&remarkDisplay("rs_tab_network_remark",tl("Operateingsuccess"),3E3,0)):remarkDisplay("rs_tab_network_remark",tl("Operateingfailure"),3E3,1)})},_renderElements:function(a,b){b=b||Page.recordStorageConfig.Tab.path.getRecordStoragePoint();
(hasRemote=b.TimingRecord.Remote||b.VideoDetectRecord.Remote||b.AlarmRecord.Remote||b.TimingSnapShot.Remote||b.VideoDetectSnapShot.Remote||b.AlarmSnapShot.Remote)?$("rs_tab_network_enable").disabled=!1:(a.Enable=!1,$("rs_tab_network_enable").disabled=!0);$("rs_tab_network_enable").checked=a.Enable;$("rs_tab_network_port").value=a.Port;$("rs_tab_network_username").value=a.UserName;$("rs_tab_network_password").value=a.Password;$("rs_tab_network_directory").value=a.Directory;$("rs_tab_network_address").value=
a.Address;$$("#rs_tab_network .ui-tip-red").set("text","")},_onDefaultClick:function(){g.configManager.getDefault("NAS",function(a){checkPostResult(a)?(f=$("rs_tab_network_Protocol").value,i=getTable(a),i.each(function(a){a.Protocol==="FTP"&&j.each(function(b){if(b.Protocol==="FTP")for(key in a)a[key]=b[key]})}),b=i.filter(function(a){return a.Protocol===f})[0],g._renderElements(b,e),remarkDisplay("rs_tab_network_remark",tl("Defaultsuccess"),3E3,0)):remarkDisplay("rs_tab_network_remark",tl("Defaultfailure"),
3E3,1)})},_onRefreshClick:function(){g._getConfigAndRenderElements(!0)},_saveTempJson:function(){b.Enable=$("rs_tab_network_enable").checked;b.Port=$("rs_tab_network_port").value-0;b.UserName=$("rs_tab_network_username").value;b.Password=$("rs_tab_network_password").value;b.Directory=$("rs_tab_network_directory").value;b.Address=$("rs_tab_network_address").value},_onConfirmClick:function(){g._validateBeforSubmit()&&(g._saveTempJson(),g.configManager.setConfig("NAS",i,function(a){checkPostResult(a)?
remarkDisplay("rs_tab_network_remark",tl("Succeed in saving configure"),3E3,0):remarkDisplay("rs_tab_network_remark",tl("Saving failure"),3E3,1)}))},_validateBeforSubmit:function(){if(!checkedImportLimt("rs_tab_network_username",3))return remarkDisplay("rs_tab_network_remark",tl("w_noInputMarks"),3E3,1),!1;if(!checkedImportLimt("rs_tab_network_password",3))return remarkDisplay("rs_tab_network_remark",tl("w_noInputMarks"),3E3,1),!1;if($("rs_tab_network_directory").value&&!/^[\w-.\/]+$/.test($("rs_tab_network_directory").value))return remarkDisplay("rs_tab_network_remark",
tl("w_pathErrorWithPoint"),3E3,1),!1;if($("rs_tab_network_address").value.length>0&&!checkedImportLimt("rs_tab_network_address",11))return remarkDisplay("rs_tab_network_remark",tl("w_emailiperror"),3E3,1),!1;if(StringUtil.byteLength($("rs_tab_network_directory").value,"aaa")>200)remarkDisplay("rs_tab_network_remark",tl("w_pathLong"),3E3,1);else return!0}}})();
