var CHANNEL_NUMBER=-1,REMOTE_CHANNELS=-1,ALARM_IN_NUMBER=-1,ALARM_OUT_NUMBER=-1,ALARM_IN_PIRALARM=!1,ALARM_FLASH=!1,authorityList=authorityList,PAL_NTSC="PAL",rtspPort=rtspPort,isIE=navigator.appName.indexOf("Microsoft")!=-1,PTZ_ALARM=!0,ExtraStreamNum=1,hasSDCard=!0,username_cfg="",username_current="",bool_3g=!1,bool_4g=!1,bool_802=!1,bool_vpn=!1,bool_sdcamera=!1,bool_PTZfunction=!1,bool_light=!1,bool_wiper=!1,bool_get3GNet=!1,bool_get4GNet=!1,bool_wifi=!1,bool_audio=!0,bool_ATM=bool_PTZfunction=
bool_sdcamera=!1,deviceType=null,VSPType="None",bool_k6=!1,NASConfig=!0,webCaps=webCaps||getWebCapsConfig(),currenDeviceType=webCaps.deviceType,g_LoginId=g_LoginId,hasPtz=!0,ishasIntellent=!1,support_scenes=["Normal"],bool_getWps=!1,temperaturesSupport=!1,ipcIvsType=null,ipcNewIVS=[],ipcNewIvsType=[],g_audioProperties=!1,audio_url="",audio_urlDefault="",g_SystemInfoNew=!1,isA5S=!1,limiteMaxBite=null,ptzCap=ptzCap||{},bool_flowrate=!1,SensorInfo="Normal",bool_GB28181=!1,IVSStyle="web",analyseSenceRuleMap=
{},PageSet={init:function(){if(!rpcCore.sessionID)top.location="/";this.translate();this.bind();this.getData();this.displaySettings();showFirstSetting()},translate:function(){$$("#camera_label").set("text",tl("w_Camera Setup"));$$("#l_camera_label").set("text",tl("w_Camera Attribute"));$$("#l_intellent_camera_label").set("text",tl("w_Camera Attribute"));$$("#l_lepton_camera_label").set("text",tl("w_Camera Attribute"));$$("#l_tau_camera_label").set("text",tl("w_Camera Attribute"));$$("#l_encode_label").set("text",
tl("w_Video"));$$("#l_audio_label").set("text",tl("w_Audio"));$$("#intellent_label").set("text",tl("w_IVS Set"));$$("#l_intellent_label").set("text",tl("w_IVS"));$$("#ipcIntellent_label").set("text",tl("w_IVS Set"));$$("#l_ipcIntellent").set("text",tl("w_IVS"));$$("#network_label").set("text",tl("w_Network Settings"));$$("#l_tcpip_label").set("text",tl("w_TCP/IP Settings"));$$("#l_connectns_label").set("text",tl("w_Connect Settings"));$$("#l_pppoe_label").set("text",tl("w_PPPOE"));$$("#l_ddns_label").set("text",
tl("w_DDNS Settings"));$$("#l_ipauth_label").set("text",tl("w_IP Purview"));$$("#l_email_label").set("text",tl("w_Mail Settings"));$$("#l_upnp_label").set("text",tl("w_UPNP"));$$("#l_snmp_label").set("text",tl("w_SNMPv1/v2"));$$("#l_qos_label").set("text",tl("w_QOS"));$$("#l_bonjour_label").set("text",tl("w_Bonjour"));$$("#l_broadcast_label").set("text",tl("w_Multicast"));$$("#l_autoreg_label").set("text",tl("w_Auto Register"));$$("#l_wifi_label").set("text",tl("w_WIFI"));$$("#l_3g_label").set("text",
tl("w_3G"));$$("#l_ieee802_label").set("text",tl("w_IEEE802"));$$("#l_vpn_label").set("text",tl("w_VPN Settings"));$$("#l_ATM_label").set("text",tl("w_ATMOsd"));$$("#ptzConfig_label").set("text",tl("Ptz"));$$("#l_pact_label").set("text",tl("w_Protocol"));$$("#l_function_label").set("text",tl("w_Function"));$$("#m_light_config_label").set("text",tl("w_OutdeviceManage"));$$("#l_IRLightSet_label").set("text",tl("w_IRLight"));$$("#l_wiperSet_label").set("text",tl("w_RainBrush"));$$("#affair_label").set("text",
tl("w_Event manage"));$$("#l_videtect_label").set("text",tl("w_Video Check"));$$("#l_ipcFaceNew").set("text",tl("w_faceDetection"));$$("#l_alarmAudioset_label").set("text",tl("w_audioDetect"));$$("#l_ipcIntellentNew").set("text",tl("w_IVS_Analyse"));$$("#l_alarmset_label").set("text",tl("w_AlarmConf"));$$("#l_abnormal_label").set("text",tl("w_ABNORMITY"));$$("#snapRecord_label").set("text",tl("w_Memory Manage"));$$("#l_recordplan_label").set("text",tl("w_Timetable"));$$("#l_storage_label").set("text",
tl("w_memory"));$$("#l_recordctrl_label").set("text",tl("w_Recording Control"));$$("#system_label").set("text",tl("w_Sysmanager"));$$("#l_localset_label").set("text",tl("w_Local Config"));$$("#l_usrmanage_label").set("text",tl("w_User Management"));$$("#l_ptz_label").set("text",tl("w_PtzConfig_auth"));$$("#l_comm_label").set("text",tl("w_ComConf_auth"));$$("#l_default_label").set("text",tl("w_Default Setting"));$$("#l_cfgbackup_label").set("text",tl("w_Collocate I/O"));$$("#l_automtain_label").set("text",
tl("w_AutoMaintain_auth"));$$("#l_upgrade_label").set("text",tl("w_Firmware Upgrade"));$$("#infoSet_label").set("text",tl("w_System Info"));$$("#l_version_label").set("text",tl("w_Edition Info"));$$("#l_log_label").set("text",tl("w_Log"));$$("#l_onlineusr_label").set("text",tl("w_Onlineuser"));$$("#l_vspcfg_label").set("text",tl("w_VspCfg"));$$("#l_ldap_label").set("text",tl("w_ldap"));$$("#l_platform_label").set("text",tl("w_access_platform"));$$("#l_ipcIntelTraf").set("text",tl("w_intelTraffic"));
$$("#l_remote_label").set("text",tl("w_remote"));$$("#l_fan_label").set("text",tl("w_ptzfan"));$$("#l_heaterSet_label").set("text",tl("w_heater"));$$("#l_flowrate_label").set("text",tl("w_flowrate"));$$("#l_ipcIntellentCar").set("text",tl("w_carDetection"))},bind:function(){$$("#set li a").addEvent("click",function(){if(!this.hasClass("set-item-current")){this.getProperty("date-change")=="ipcIntellentConfig"&&(ipcIvsType=="FaceDetection"?this.setProperty("data-filename","ipcFacedectetionConfig"):
ipcIvsType=="Normal"?this.setProperty("data-filename","ipcIntellentConfig"):ipcIvsType=="VideoDiagnosis"&&this.setProperty("data-filename","ipcVideoDiagnosisConfig"));var a=this.getProperty("data-filename"),c=$$("#set li a.set-item-current").getProperty("data-filename");c.length>0&&(c=Page[c[0]])&&$type(c.leave)=="function"&&c.leave();$("b_record")?$("b_record").hasClass("main-top-icon-vedio-current")||$("ocx")&&$("ocx").DisConnectRealVideo(0):$("ocx")&&$("ocx").DisConnectRealVideo(0);$("video1").setStyles({top:"0px",
left:"0px"});$$("#set li a").removeClass("set-item-current");this.addClass("set-item-current");if(a)Site.currentPage.is={},Site.currentPage.is[a]=!0,getHtml(a)}});$$("#l_vspcfg").addEvent("click",function(){getPlatformHtml(VSPType)});$$(".set-menu").addEvent("click",function(){var a=this.hasClass("set-menu-current");$$(".set-menu").removeClass("set-menu-current").getNext("ul").setStyle("display","none");a||this.addClass("set-menu-current").getNext("ul").setStyle("display","block")})},getData:function(){getProductDef();
getWirelessAnd3GAbility();getAudioAbility();getChannelNumInfo();getUserAuthorityList();getIntellent();getVideoStd();this.getFishEyeAblitity();getSensorInfo()},displaySettings:function(){displaySettingsBasedOnConfiguration();displaySettingsBasedOnDeviceAbility();displaySettingsBasedOnUserAuthority()},getFishEyeAblitity:function(){(g_isHasfisheye===void 0||g_isHasfisheye===null)&&(new VideoInput).getCaps(function(a){a=JSON.decode(a);a.result&&(g_isHasfisheye=!!a.params.caps.FishEye&&checkAuthority("VideoInputConfig"))},
0)},render:function(){Browser.chrome&&window.addEvent("resize",PageSet.resize)},leave:function(){window.removeEvent("resize",PageSet.resize);filename=$$("#set a.set-item-current").getProperty("data-filename");filename[0]&&$type(Page[filename].leave)=="function"&&Page[filename].leave()},resize:function(){if(Browser.chrome){var a=$("video1");if(a.getStyle("top")!=="0px"){var c=a.getStyle("height").toInt(),d=a.getStyle("left").toInt(),b=a.getStyle("top").toInt();if($(overlayPlugins.element)){var e=$(overlayPlugins.element).getPosition(),
f=a.getPosition();a.setStyles({left:d+e.x-f.x,top:b+e.y-f.y})}setTimeout(function(){a.setStyle("height",c+1);setTimeout(function(){a.setStyles({height:c})},5)},0)}}}};
function displaySettingsBasedOnConfiguration(){isEnable("show_auto_register")||disposeElement("m_autoreg");/simpchinese/i.test(Cookie.read("DHLangCookie30"))||(disposeElement("m_autoreg"),disposeElement("m_platform"));isEnable("show_comm_config")||disposeElement("m_comm");isEnable("show_SNMP_config")||disposeElement("m_SNMP");isEnable("show_bonjour_config")||disposeElement("m_bonjour");isEnable("is_show_LDAP")||disposeElement("m_ldapconfig");NASConfig=isEnable("show_NAS_config")?!0:!1;bool_k6=isEnable("is_k6_DeviceType")?
!0:!1;isEnable("is_show_HTTPS")||disposeElement("m_https");isDDNS()&&disposeElement("m_SysUpdate");isEnable("is_show_platform")||disposeElement("m_platform");isEnable("is_8M_Flash")&&(disposeElement("m_SNMP"),disposeElement("m_ieee802"),disposeElement("m_intellentset"),disposeElement("b_audio"),disposeElement("m_3g"),disposeElement("m_ATM"),disposeElement("m_ldapconfig"),disposeElement("m_vpn"),disposeElement("m_ptz_config"),disposeElement("m_wifi"),disposeElement("m_PPPoE"))}
function displaySettingsBasedOnDeviceAbility(){hasPtz||(disposeElement("ptzSet"),disposeElement("ptzproSet"));!hasPtz&&!bool_PTZfunction&&disposeElement("ptzfuncSet");currenDeviceType.contains("IPC-HDB3200C")&&disposeElement("ptzSet");if(VSPType=="GENETEC"||VSPType=="YXSHOW"||VSPType=="PSIA"||VSPType=="YXISHOW"||VSPType=="HSWX"||VSPType=="AMCREST")VSPType="None";VSPType&&VSPType.toLowerCase()!="none"?$("l_vspcfg_label").set("text",tl(VSPType)):disposeElement("m_vsp");(currenDeviceType.contains("SD")||
currenDeviceType.contains("CA-")||SensorInfo!="Normal")&&disposeElement("m_camera");(deviceType.contains("SD")||deviceType.contains("CA-")||SensorInfo!="Normal")&&disposeElement("m_camera");bool_4g||bool_get4GNet?$$("#l_3g_label").set("text",tl("w_4G")):(!bool_get3GNet||!bool_3g)&&disposeElement("m_3g");bool_wifi||disposeElement("m_wifi");bool_audio||disposeElement("b_audio");bool_802||disposeElement("m_ieee802");bool_vpn||disposeElement("m_vpn");bool_ATM||disposeElement("m_ATM");ALARM_IN_NUMBER==
0&&disposeElement("m_alarm");(!g_audioMangerCap.audioMangerCap||!g_audioInputNum)&&disposeElement("m_alarmAudio");(!bool_sdcamera||SensorInfo!="Normal")&&disposeElement("m_intellent_camera");bool_PTZfunction?disposeElement("ptzSet"):disposeElement("m_ptz_config");!bool_light&&!bool_wiper&&(currenDeviceType.contains("SD")?ptzCap&&ptzCap.PtzFan&&ptzCap.PtzHeater&&!ptzCap.PtzFan.Support&&!ptzCap.PtzHeater.Support&&disposeElement("m_light_config_wrap"):disposeElement("m_light_config_wrap"));(!ptzCap||
!ptzCap.PtzFan||!ptzCap.PtzFan.Support)&&disposeElement("fanSet");(!ptzCap||!ptzCap.PtzHeater||!ptzCap.PtzHeater.Support)&&disposeElement("heaterSet");bool_light||disposeElement("IRLightSet");bool_wiper||disposeElement("wiperSet");ishasIntellent?currenDeviceType.contains("SD")&&IVSStyle!="web"&&IVSStyle!="SD"&&disposeElement("m_intellentset"):disposeElement("m_intellentset");(!IPCIntellentShow||isEnable("is_385_intellent"))&&disposeElement("m_ipcIntellentset");(!ipcNewIvsType.contains("Normal")&&
IPCIntellentShow||!isEnable("is_385_intellent"))&&(!currenDeviceType.contains("SD")||!(IVSStyle!="web"&&IVSStyle=="IPC"))&&disposeElement("m_ipcIntellentNew");(!ipcNewIvsType.contains("Traffic")||!IPCIntellentShow)&&disposeElement("m_intelTraf");(!ipcNewIvsType.contains("FaceDetection")&&IPCIntellentShow||!isEnable("is_385_intellent"))&&disposeElement("m_ipcFaceNew");(!IPCIntellentShow||!ipcNewIVS.SupportedRules||!(ipcNewIVS.SupportedRules.contains("ParkingDetection")&&isEnable("is_385_intellent")!==
!1))&&disposeElement("m_ipcIntellentCar");bool_flowrate||disposeElement("m_ipcFlowrate");bool_sdcamera||disposeElement("m_intellent_camera");bool_PTZfunction||disposeElement("m_ptz_config");ALARM_IN_NUMBER==0&&disposeElement("m_alarm");SensorInfo!="Lepton"&&disposeElement("lepton_camera");SensorInfo!="Tau"&&disposeElement("tau_camera")}
function displaySettingsBasedOnUserAuthority(){$("set").getElements("li").each(function(a){checkAuthority(a.getProperty("auth"))||disposeElement(a)});!checkAuthority("QueryLog")&&!checkAuthority("DelLog")&&disposeElement("m_logManageConfig")}
function getUserAuthorityList(){var a=new UserManager;if(username_cfg!="")username_current=username_cfg;else try{username_current=settings.username}catch(c){var d=Cookie.read("DhWebCookie");username_current=JSON.decode(d).username}authorityList||a.getUserInfo(username_current,function(a,c){authorityList=c.params.user.AuthorityList},!1)}function checkAuthority(a){return!a?!0:authorityList.contains(a)}
function getProductDef(){var a=new MagicBox;a.getProductDef(["HasPtz","IsPtzAlarm","3G","VSP","MaxExtraStream","IsLocalStore","IEEE802_1X","VPN","SupportedWPS","CameraAttribute","PtzFunctionMenu","LightingControl","RainBrushControl","CifPFrameSize","AudioFileManager","AudioProperties","Device","VolumeDetect","MaxMainStreamBitrate","4G","VideoAnalyse","ATM","PTZFunctionViaApp","GB28181","IntelliUI"],function(a,d){if(d.result){var b=d.params;if(b[0].result)hasPtz=b[0].params.definition;if(b[1].result)PTZ_ALARM=
b[1].params.definition;if(b[2].result)bool_3g=b[2].params.definition;if(b[3].result)VSPType=b[3].params.definition;if(b[4].result)ExtraStreamNum=b[4].params.definition;if(b[5].result)hasSDCard=b[5].params.definition;if(b[6].result)bool_802=b[6].params.definition;if(b[7].result)bool_vpn=b[7].params.definition;if(b[8].result)bool_getWps=b[8].params.definition;if(b[9].result)bool_sdcamera=b[9].params.definition.Support;if(b[10].result)bool_PTZfunction=b[10].params.definition.Support;if(b[11].result)bool_light=
b[11].params.definition.Support,b[11].params.definition.FarLightNumber==0&&b[11].params.definition.NearLightNumber==0&&(bool_light=!1);if(b[12].result)bool_wiper=b[12].params.definition.Support;b[13].result&&(cifPFrameMin=b[13].params.definition[0],cifPFrameMax=b[13].params.definition[1]);if(b[14].result){var e=b[14].params.definition.PlayRootPath.split(";");audio_url=e[1];audio_urlDefault=e[0]}if(b[15].result)g_audioProperties=b[15].params.definition.Support;if(b[16].result)deviceType=b[16].params.definition;
if(b[18].result)limiteMaxBite=b[18].params.definition;if(b[19].result)bool_4g=b[19].params.definition;b[20].result&&(b[20].params.definition.SupportScenes||[]).contains("Traffic")&&$("m_intellent_traffic").removeClass("fn-hide");if(b[21].result)bool_ATM=b[21].params.definition;b[22].result&&b[22].params.definition==!0&&disposeElement("ptzproSet");if(b[23].result)bool_GB28181=b[23].params.definition;if(b[24].result)IVSStyle=(IVSStyle=b[24].params.definition)?IVSStyle:"web"}},!1);(new BaceBoard).getCaps(function(a,
d){d.result&&(temperaturesSupport=(d.params.caps.Temperatures||[]).length<1?!1:!0)});a.getSystemInfoNew(function(a){if(JSON.decode(a).result&&JSON.decode(a).params.info)g_SystemInfoNew=JSON.decode(a).params.info},!1);(new PtzCtrl).getCurrentProtocolCaps(function(a){if(JSON.decode(a).result&&JSON.decode(a).params)ptzCap=JSON.decode(a).params.caps,ptzCap==null&&(ptzCap={})},0,!1)}
function getWirelessAnd3GAbility(){(new NetApp).getNetInterfaces(function(a,c){c.result&&c.params.netInterface.each(function(a){a.Type==="Wireless"&&a.Name==="eth2"&&(bool_wifi=!0);a.Name==="3G"&&(bool_get3GNet=!0);a.Name==="4G"&&(bool_get4GNet=!0)})},!1)}function getAudioAbility(){var a=new AudioInput;g_audioInputNum+1&&g_audioInputNum!=null?g_audioInputNum==0&&(bool_audio=!1):a.getCollect(function(a,d){d.result&&d.params.channels==0&&(bool_audio=!1)},!1)}
function getChannelNumInfo(){var a=new RPCCall,c=a.getRequest("devVideoInput.getChannels"),d=a.getRequest("alarm.getInSlots"),b=a.getRequest("alarm.getOutSlots"),e=c+","+d+","+b,e=a.getRequest("alarm.getAlarmCaps");a.doMutiCall(c+","+d+","+b+","+e,function(a,b){if(b.result){var c=b.params;CHANNEL_NUMBER=c[0].result-0;ALARM_IN_NUMBER=c[1].result?c[1].params.inputs-0:0;ALARM_OUT_NUMBER=c[2].result?c[2].params.outputs-0:0;if(c[3].params)ALARM_IN_PIRALARM=c[3].params.caps.AlarmPir,ALARM_FLASH=c[3].params.caps.Flash;
isEnable("is_8M_Flash")&&(ALARM_OUT_NUMBER=ALARM_IN_NUMBER=0)}},!1)}function disposeElement(a){(a=$type(a)==="string"?$(a):a)&&a.dispose()}function showFirstSetting(){for(var a=0,c,d=$("set").getElements("div"),a=0;a<d.length;a++)if(c=d[a].getElements("li"),c.length!==0){d[a].getFirst("a").fireEvent("click");c[0].getFirst("a").fireEvent("click");break}}function getVideoStd(){(new ConfigManager).getConfig("VideoStandard",function(a){PAL_NTSC=getTable(a)})}
function getIntellent(){(new VideoAnalyseDevice).getVideoAnalyseCap(function(a){if(JSON.decode(a).result)ipcNewIVS=JSON.decode(a).params.caps,ipcNewIvsType=ipcNewIVS.SupportedScene||[],bool_flowrate=IPCIntellentShow&&ipcNewIvsType.contains("NumberStat")&&isEnable("is_385_intellent")&&checkAuthority("IntelliConf")},0,!1);typeof isIntellent=="boolean"||typeof IPCIntellentShow=="boolean"?(ishasIntellent=isIntellent,$("m_intellentset").style.display=ishasIntellent?"":"none",$("m_intellent").style.display=
ishasIntellent?"":"none",$("m_ipcIntellentset").style.display=IPCIntellentShow?"":"none"):(new MagicBox).getProductDef(["VideoAnalyse","IntelliTracker"],function(a,c){if(c.result){var d=c.params;isIntellent=d[0].params&&d[0].params.definition.Support;/IPC/.test(currenDeviceType)&&isIntellent?(IPCIntellentShow=!0,isIntellent=!1):/^SD/.test(currenDeviceType)&&isIntellent?(IPCIntellentShow=!1,isIntellent=!0):isIntellent=IPCIntellentShow=!1;ishasIntellent=isIntellent;$("m_intellentset").style.display=
ishasIntellent?"":"none";$("m_intellent").style.display=ishasIntellent?"":"none";$("m_ipcIntellentset").style.display=IPCIntellentShow?"":"none"}},!1);(IPCIntellentShow||isIntellent)&&(new ConfigManager).getConfig("VideoAnalyseGlobal",function(a,c){if(c.result&&c.params.table!=null)ipcIvsType=c.params.table[0].Scene.Type,c.params.table.each(function(a,b){analyseSenceRuleMap[a.Scene.Type]=b})},!1)}
function getSensorInfo(){(new VideoInput).getCapsEx(function(a){if(JSON.decode(a).result&&(a=JSON.decode(a).params.caps,a.SensorInfo))SensorInfo=a.SensorInfo.Type,SensorInfo!="Normal"&&$$("#l_videtect_label").set("text",tl("w_Video Detection"))},0,"ALL",!1)};
